
LOAD DATA 
CHARACTERSET WE8ISO8859P1
INTO TABLE LOAD.CARGASUBSEGMENTACAO
APPEND
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	NRDOCUMENTO 	CHAR,
	TIPODOCUMENTO 	INTEGER EXTERNAL,
	CDSISTEMAORIGEMSUBSEGMENTACAO 	INTEGER EXTERNAL,
	SGSUBSEGMENTO 	CHAR
)
