#ifndef CARREGATI
#define CARREGATI

#define XML_OUT_ROOT        "TelaInicialVO"
#define XML_OUT_PROP        "cliente.fo.vivo.com.br/vo"

#define XML_OUT_NO_TICLIENTE    "TICliente"
#define XML_OUT_NO_TILINHA      "TILinha"
#define XML_OUT_NO_TIFATU       "TIFaturamento"
#define XML_OUT_NO_ENDERECO     "EnderecoBaseVO"
#define XML_OUT_NO_TIDOCUME     "TIDocumento"
#define XML_OUT_NO_USUARIOLIN	"UsuarioLinhaVO"
#define XML_OUT_NO_CARTEIRA     "CarterizacaoVO"
#define XML_OUT_NO_SEGMENTA     "SegmentacaoVO"
#define XML_OUT_NO_UF           "UFVO"
#define XML_OUT_NO_PAIS         "PaisVO"
#define XML_OUT_NO_GESTOR       "Gestor"

#define XML_OUT_NRLINHA_DE      "nrLinhaFiltro"
#define XML_OUT_NRLINHA_ATE     "nrLinhaFiltroAte"
#define XML_OUT_IDTIPOLINHA     "idTipoLinhaFiltro"
#define XML_OUT_IDSTATUSLIN     "idStatusLinhaFiltro"
#define XML_OUT_IDPESSOAFIL     "idPessoaFiltro"
#define XML_OUT_IDLINHAFIL      "idLinhaFiltro"
#define XML_OUT_INDIVULGA       "inDivulgaNumeroFiltro"
#define XML_OUT_DATAULTALT      "dtUltimaAtualizacaoFiltro"

#define XML_OUT_IDTIPO      "id"
#define XML_OUT_DESCRICAO   "descricao"

#define XML_OUT_IDPESSOA            "idPessoa"
#define XML_OUT_INTPPESSOA          "inTipoPessoa"
#define XML_OUT_DTCHURN             "dtChurn"
#define XML_OUT_DSCHURN             "dsChurn"
#define XML_OUT_NMPESSOA            "nmNome"
#define XML_OUT_NRTELEFONE          "nrTelefone"
#define XML_OUT_IDLINHA             "idLinha"
#define XML_OUT_NRCODAREA           "nrCodArea"
#define XML_OUT_NRLINHA             "nrLinha"
#define XML_OUT_DSESTADOLINHA       "dsEstadoLinha"
#define XML_OUT_DSTIPOLINHA         "dsTipoLinha"
#define XML_OUT_QTDLINHAATIVA       "qtdLinhasAtivas"
#define XML_OUT_QTDLINHAINATIVA     "qtdLinhasInativas"
#define XML_OUT_QTDLINHAS           "qtdLinhas"

#define XML_OUT_IDENDERECO          "idEndereco"
#define XML_OUT_NMLOGRADOURO        "dsEndereco"
#define XML_OUT_NUMERO              "nrEndereco"
#define XML_OUT_COMPLEMENTO         "dsComplemento"
#define XML_OUT_NMBAIRRO            "dsBairro"
#define XML_OUT_CEP                 "nrCEP"
#define XML_OUT_MUNICIPIO           "dsCidade"

#define XML_OUT_IDUF                "idUF"
#define XML_OUT_SGUF                "sgUF"
#define XML_OUT_DSUF                "nmUF"

#define XML_OUT_IDPAIS              "idPais"
#define XML_OUT_SGPAIS              "sgPais"
#define XML_OUT_DSPAIS              "dsPais"
#define XML_OUT_NACIONALIDADE       "dsNacionalidade"

#define XML_OUT_DSPLANOSERVICO      "dsPlanoServico"
#define XML_OUT_DSSTATUSLINHA       "dsStatusLinha"
#define XML_OUT_DTHABILITACAO       "dtHabilitacao"
#define XML_OUT_INDIVULGANUMERO     "inDivulgaNumero"
#define XML_OUT_DTTERMINOCONTRATO   "dtTerminoContrato"
#define XML_OUT_DSTIPOCONTRATO      "dsTipoContrato"
#define XML_OUT_DATAULTIMAALT       "dtUltimaAtualizacao"
#define XML_OUT_IDTPCARTEIRA        "idTipoCarteira"
#define XML_OUT_CODIGO              "codigo"
#define XML_OUT_IDTPCARTEIRA        "idTipoCarteira"

#define XML_OUT_NMGESTOR            "nmGestor"

#define XML_OUT_NMUSUARIO	        "nmUsuario"
#define XML_OUT_IDDOCUM		        "idDocumento"
#define XML_OUT_TPDOCUM		        "dsTipoDocumento"
#define XML_OUT_NRDOCUM		        "nrDocumento"
#define XML_OUT_TPCONTATO	        "dsTipoContato"
#define XML_OUT_NRCONTATO	        "nrContato"
#define XML_OUT_VLRENTAB	        "vlRentabilidade"
#define XML_OUT_DSCARGO		        "dsCargo"

#define XML_OUT_TOTALLINHAS         "qtLinhasLocalizadas"
#define XML_IN_NRLINHA              "nrLinha"
#define XML_IN_IDLINHATELEFONICA    "idLinhaTelefonica"
#define XML_OUT_TOTALRETORNADA      "qtLinhasRetornadas"

#define XML_OUT_IDSERVICO	"idServico"
#define XML_OUT_INPLANO		"inPlanoServico"
#define XML_OUT_IDPACOTE	"idPacote"
#define XML_OUT_NMSERVICO	"nmServico"
#define XML_OUT_DTEXPIRA	"dtExpiracao"


#endif
