set echo on
set serveroutput on

spool relGestorAltSenha.txt

SELECT 'CNPJ|RAZAOSOCIAL|NOMEDOGESTOR|CPFDOGESTOR|TELEFONECADASTRADO|DATAULTIMAAUTENTICACAO' FROM DUAL;

SELECT DISTINCT
PM.NRDOCUMENTOEMPRESA || '|' || 
EM.NMEMPRESA || '|' ||
PG.NMPESSOAGESTOR || '|' || 
PG.NRDOCUMENTO || '|' ||
SG.NRLINHA || '|' ||
TO_CHAR((SELECT MAX(DTAUTENTICACAO) FROM CUSTOMER.AUTENTICACAOGESTORPJ AG WHERE AG.IDSENHAGESTORPJ = SG.IDSENHAGESTORPJ ), 'DD/MM/YYYY HH24:MI:SS') AS DATAULTIMAAUTENTICACAO
FROM CUSTOMER.PESSOAGESTOR PG
    JOIN CUSTOMER.PESSOAGESTORMASTER PM ON PM.NRDOCUMENTOGESTOR = PG.NRDOCUMENTO
    JOIN (SELECT PE.NMPESSOA AS NMEMPRESA, DC.NRDOCUMENTO
             FROM CUSTOMER.DOCUMENTO DC
             JOIN PESSOADOCUMENTO PD ON PD.IDDOCUMENTO = DC.IDDOCUMENTO
             JOIN CUSTOMER.PESSOA PE ON PE.IDPESSOA = PD.IDPESSOA
             WHERE  PE.IDTIPOPESSOA = 2
            ) EM ON EM.NRDOCUMENTO = PM.NRDOCUMENTOEMPRESA
    JOIN CUSTOMER.SENHAGESTORPJ SG ON SG.NRDOCUMENTO = PG.NRDOCUMENTO
	JOIN CUSTOMER.AUTORIZADOGESTORPJ AG ON AG.NRDOCUMENTOEMPRESA =  PM.NRDOCUMENTOEMPRESA
WHERE SG.INSENHAEXPIRADA <> 1
AND SG.DTALTERACAO BETWEEN (SELECT CAST( SYSDATE AS DATE) - 7 FROM DUAL) AND SYSDATE;
	
spool off

set echo off
set serveroutput off

	
	