//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.09 at 07:15:42 PM BRST 
//


package br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.impl;

public class AtendimentoVOTypeImpl implements br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.AtendimentoVOType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _NrOrdemVenda;
    protected java.lang.String _CdServico;
    protected java.lang.String _IdCanal;
    protected java.lang.String _CdStatusRejeicao;
    protected boolean has_InConsultor;
    protected int _InConsultor;
    protected java.lang.String _IdGrupoAbertura;
    protected java.lang.String _IdContato;
    protected boolean has_TpOperacao;
    protected int _TpOperacao;
    protected java.lang.String _DsComentario;
    protected java.lang.String _NrTelefone;
    protected java.lang.String _NrProtocolo;
    protected java.lang.String _IdSistema;
    protected java.lang.String _IdUsuario;
    public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.AtendimentoVOType.class);
    }

    public java.lang.String getNrOrdemVenda() {
        return _NrOrdemVenda;
    }

    public void setNrOrdemVenda(java.lang.String value) {
        _NrOrdemVenda = value;
    }

    public java.lang.String getCdServico() {
        return _CdServico;
    }

    public void setCdServico(java.lang.String value) {
        _CdServico = value;
    }

    public java.lang.String getIdCanal() {
        return _IdCanal;
    }

    public void setIdCanal(java.lang.String value) {
        _IdCanal = value;
    }

    public java.lang.String getCdStatusRejeicao() {
        return _CdStatusRejeicao;
    }

    public void setCdStatusRejeicao(java.lang.String value) {
        _CdStatusRejeicao = value;
    }

    public int getInConsultor() {
        return _InConsultor;
    }

    public void setInConsultor(int value) {
        _InConsultor = value;
        has_InConsultor = true;
    }

    public java.lang.String getIdGrupoAbertura() {
        return _IdGrupoAbertura;
    }

    public void setIdGrupoAbertura(java.lang.String value) {
        _IdGrupoAbertura = value;
    }

    public java.lang.String getIdContato() {
        return _IdContato;
    }

    public void setIdContato(java.lang.String value) {
        _IdContato = value;
    }

    public int getTpOperacao() {
        return _TpOperacao;
    }

    public void setTpOperacao(int value) {
        _TpOperacao = value;
        has_TpOperacao = true;
    }

    public java.lang.String getDsComentario() {
        return _DsComentario;
    }

    public void setDsComentario(java.lang.String value) {
        _DsComentario = value;
    }

    public java.lang.String getNrTelefone() {
        return _NrTelefone;
    }

    public void setNrTelefone(java.lang.String value) {
        _NrTelefone = value;
    }

    public java.lang.String getNrProtocolo() {
        return _NrProtocolo;
    }

    public void setNrProtocolo(java.lang.String value) {
        _NrProtocolo = value;
    }

    public java.lang.String getIdSistema() {
        return _IdSistema;
    }

    public void setIdSistema(java.lang.String value) {
        _IdSistema = value;
    }

    public java.lang.String getIdUsuario() {
        return _IdUsuario;
    }

    public void setIdUsuario(java.lang.String value) {
        _IdUsuario = value;
    }

    public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
        return new br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.impl.AtendimentoVOTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "nrProtocolo");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _NrProtocolo), "NrProtocolo");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "cdServico");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _CdServico), "CdServico");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idSistema");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdSistema), "IdSistema");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsComentario");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsComentario), "DsComentario");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idGrupoAbertura");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdGrupoAbertura), "IdGrupoAbertura");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idCanal");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdCanal), "IdCanal");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idUsuario");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdUsuario), "IdUsuario");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_IdContato!= null) {
            context.startElement("", "idContato");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _IdContato), "IdContato");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_InConsultor) {
            context.startElement("", "inConsultor");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _InConsultor)), "InConsultor");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_NrOrdemVenda!= null) {
            context.startElement("", "nrOrdemVenda");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NrOrdemVenda), "NrOrdemVenda");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CdStatusRejeicao!= null) {
            context.startElement("", "cdStatusRejeicao");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CdStatusRejeicao), "CdStatusRejeicao");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_NrTelefone!= null) {
            context.startElement("", "nrTelefone");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NrTelefone), "NrTelefone");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_TpOperacao) {
            context.startElement("", "tpOperacao");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _TpOperacao)), "TpOperacao");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.AtendimentoVOType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun."
+"msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLco"
+"m/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~"
+"\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004nam"
+"et\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.dat"
+"atype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.m"
+"sv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv."
+"datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype"
+".xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/S"
+"tring;L\u0000\btypeNameq\u0000~\u0000\u001eL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/"
+"xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchem"
+"at\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$P"
+"reserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpacePro"
+"cessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullS"
+"etExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPa"
+"ir\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\fnamespaceURIq\u0000~\u0000\u001expq\u0000~\u0000\"q\u0000~"
+"\u0000!sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 co"
+"m.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameC"
+"lassq\u0000~\u0000\u0012xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000ps"
+"q\u0000~\u0000\u0016ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\u001bq\u0000~\u0000!t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProces"
+"sor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000\'sq\u0000~\u0000(q\u0000~\u00003q\u0000~\u0000!sr\u0000#com.su"
+"n.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\f"
+"namespaceURIq\u0000~\u0000\u001exr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000co"
+"m.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0003sq\u0000~\u0000.\u0001psq\u0000~\u00007t\u0000\u000bnrProtocolot\u0000\u0000sq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~"
+"\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\tcdServicoq\u0000~\u0000Asq\u0000~\u0000\u0011"
+"pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\t"
+"idSistemaq\u0000~\u0000Asq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000"
+"0q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\fdsComentarioq\u0000~\u0000Asq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019s"
+"q\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000fidGrupoAberturaq\u0000"
+"~\u0000Asq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000="
+"sq\u0000~\u00007t\u0000\u0007idCanalq\u0000~\u0000Asq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~"
+"\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\tidUsuarioq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/"
+"p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\ti"
+"dContatoq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0016ppsr\u0000 c"
+"om.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.da"
+"tatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom"
+"/sun/msv/datatype/xsd/XSDatatypeImpl;xq\u0000~\u0000\u001bq\u0000~\u0000!t\u0000\u0003intq\u0000~\u00005s"
+"r\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#"
+"com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet"
+"\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWit"
+"hValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd"
+".DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueChec"
+"kFlagL\u0000\bbaseTypeq\u0000~\u0000sL\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype"
+"/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001exq\u0000~\u0000\u001dppq\u0000~\u00005\u0000\u0001sr\u0000*com.su"
+"n.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000wppq\u0000~\u00005"
+"\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000rq\u0000~\u0000"
+"!t\u0000\u0004longq\u0000~\u00005sq\u0000~\u0000vppq\u0000~\u00005\u0000\u0001sq\u0000~\u0000}ppq\u0000~\u00005\u0000\u0000sr\u0000$com.sun.msv.d"
+"atatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000rq\u0000~\u0000!t\u0000\u0007integerq\u0000~\u00005"
+"sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I"
+"\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexicalConst"
+"raintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000zppq\u0000~\u00005\u0001\u0000sr\u0000#com.sun.msv.datatype"
+".xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001bq\u0000~\u0000!t\u0000\u0007decimalq\u0000~\u00005q\u0000~\u0000\u008bt\u0000\u000e"
+"fractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000\u0085t\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090"
+"\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000"
+"\u0085t\u0000\fmaxInclusivesq\u0000~\u0000\u008f\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000\u0080q\u0000~\u0000\u008esr\u0000\u0011java.lang.Intege"
+"r\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000\u0090\u0080\u0000\u0000\u0000q\u0000~\u0000\u0080q\u0000~\u0000\u0092sq\u0000~\u0000\u0094\u007f\u00ff\u00ff\u00ffq\u0000~\u0000\'sq\u0000~\u0000"
+"(q\u0000~\u0000uq\u0000~\u0000!sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000binCon"
+"sultorq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq"
+"\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\fnrOrdemVendaq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~"
+"\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009"
+"q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0010cdStatusRejeicaoq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p"
+"\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\nnr"
+"Telefoneq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u0000*pp"
+"sq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\ntpOperacaoq\u0000~\u0000Aq\u0000~\u0000=sr\u0000\""
+"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/L"
+"com/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun."
+"msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rs"
+"treamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;"
+"xp\u0000\u0000\u0000,\u0001pq\u0000~\u0000oq\u0000~\u0000\u00b3q\u0000~\u0000\bq\u0000~\u0000\fq\u0000~\u0000\tq\u0000~\u0000\rq\u0000~\u0000\u0007q\u0000~\u0000+q\u0000~\u0000Dq\u0000~\u0000Jq\u0000"
+"~\u0000Pq\u0000~\u0000Vq\u0000~\u0000\\q\u0000~\u0000bq\u0000~\u0000iq\u0000~\u0000\u0015q\u0000~\u0000Cq\u0000~\u0000Iq\u0000~\u0000Oq\u0000~\u0000Uq\u0000~\u0000[q\u0000~\u0000aq\u0000"
+"~\u0000hq\u0000~\u0000\u0098q\u0000~\u0000\u009fq\u0000~\u0000\u009eq\u0000~\u0000\u000eq\u0000~\u0000\u00a6q\u0000~\u0000\u00a5q\u0000~\u0000\u00adq\u0000~\u0000\u00acq\u0000~\u0000\u00b4q\u0000~\u0000\u000bq\u0000~\u0000mq\u0000"
+"~\u0000\u00b1q\u0000~\u0000fq\u0000~\u0000\u009cq\u0000~\u0000\u00a3q\u0000~\u0000\u00aaq\u0000~\u0000\u0006q\u0000~\u0000\u0005q\u0000~\u0000\u000fq\u0000~\u0000\nq\u0000~\u0000\u0010x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------------------------");
        }

        protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return br.com.indrasistemas.vivoservices.atendimento.ordemvenda.tuxgateway.entrada.impl.AtendimentoVOTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        if (("idSistema" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("idCanal" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("dsComentario" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  39 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  21 :
                        if (("idContato" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  30 :
                        if (("cdStatusRejeicao" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 31;
                            return ;
                        }
                        state = 33;
                        continue outer;
                    case  3 :
                        if (("cdServico" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  33 :
                        if (("nrTelefone" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 34;
                            return ;
                        }
                        state = 36;
                        continue outer;
                    case  27 :
                        if (("nrOrdemVenda" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 28;
                            return ;
                        }
                        state = 30;
                        continue outer;
                    case  12 :
                        if (("idGrupoAbertura" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("nrProtocolo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  36 :
                        if (("tpOperacao" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 37;
                            return ;
                        }
                        state = 39;
                        continue outer;
                    case  24 :
                        if (("inConsultor" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  18 :
                        if (("idUsuario" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  29 :
                        if (("nrOrdemVenda" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 30;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("idUsuario" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("dsComentario" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  39 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  17 :
                        if (("idCanal" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("inConsultor" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  8 :
                        if (("idSistema" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("nrProtocolo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  35 :
                        if (("nrTelefone" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 36;
                            return ;
                        }
                        break;
                    case  38 :
                        if (("tpOperacao" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 39;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("cdServico" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  32 :
                        if (("cdStatusRejeicao" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 33;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("idContato" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  14 :
                        if (("idGrupoAbertura" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  39 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  39 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            state = 2;
                            eatText1(value);
                            return ;
                        case  39 :
                            revertToParentFromText(value);
                            return ;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  19 :
                            state = 20;
                            eatText2(value);
                            return ;
                        case  4 :
                            state = 5;
                            eatText3(value);
                            return ;
                        case  16 :
                            state = 17;
                            eatText4(value);
                            return ;
                        case  31 :
                            state = 32;
                            eatText5(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText6(value);
                            return ;
                        case  28 :
                            state = 29;
                            eatText7(value);
                            return ;
                        case  30 :
                            state = 33;
                            continue outer;
                        case  34 :
                            state = 35;
                            eatText8(value);
                            return ;
                        case  33 :
                            state = 36;
                            continue outer;
                        case  27 :
                            state = 30;
                            continue outer;
                        case  13 :
                            state = 14;
                            eatText9(value);
                            return ;
                        case  25 :
                            state = 26;
                            eatText10(value);
                            return ;
                        case  37 :
                            state = 38;
                            eatText11(value);
                            return ;
                        case  7 :
                            state = 8;
                            eatText12(value);
                            return ;
                        case  36 :
                            state = 39;
                            continue outer;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  22 :
                            state = 23;
                            eatText13(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NrProtocolo = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdUsuario = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CdServico = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdCanal = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CdStatusRejeicao = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsComentario = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NrOrdemVenda = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NrTelefone = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdGrupoAbertura = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _InConsultor = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_InConsultor = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText11(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TpOperacao = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_TpOperacao = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText12(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdSistema = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText13(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdContato = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
