LOAD DATA 
APPEND
INTO TABLE LINHA.LINHAOFERTA
FIELDS TERMINATED BY '|'
 OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CDAREAREGISTRO position(1:2) INTEGER EXTERNAL(2)
   ,NRLINHA position(3) INTEGER EXTERNAL(10)
)

