SET SQLPROMPT '';
SET TERMOUT ON;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

VARIABLE VO_CDERRO NUMBER
VARIABLE VO_DSERRO VARCHAR2(512)

DECLARE
	V_IDUSUARIO NUMBER := '&1';
BEGIN
	MERGE
	/*+ PARALLEL(8) */
	INTO CUSTOMER.DOCUMENTOOFERTA D 
	USING (
	  SELECT /*+ PARALLEL(8) */
		NRCPF
	  FROM 
	    LOAD.CARGADOCUMENTOOFERTA_A
	) L 
	ON (D.NRDOCUMENTO = L.NRCPF AND D.IDTIPODOCUMENTO = 1)
	WHEN MATCHED THEN 
	  UPDATE
	  SET D.IDUSUARIOALTERACAO = V_IDUSUARIO,
		  D.DTULTIMAALTERACAO = SYSDATE,
		  D.INSTATUS = 1
	WHEN NOT MATCHED THEN 
	  INSERT (
		IDDOCUMENTOOFERTA,
		IDTIPODOCUMENTO,
		INSTATUS,
		NRDOCUMENTO, 
		IDUSUARIOALTERACAO,
		DTULTIMAALTERACAO
	  ) VALUES (
		CUSTOMER.DOCUMENTOOFERTASQ.NEXTVAL,
		1,
		1,
		L.NRCPF, 
		V_IDUSUARIO,
		SYSDATE
	  )
	;

	COMMIT;
	:VO_CDERRO := 0;
	:VO_DSERRO := 'SUCESSO';
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		:VO_CDERRO := 99;
		:VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRICAO DO ERRO: ' || SQLERRM;
END;
/

SET TIMING OFF;

select CHR(10) from dual;
select 'VO_CDERRO', :VO_CDERRO from dual;
select 'VO_DSERRO', :VO_DSERRO from dual;

EXIT :VO_CDERRO;

