
CREATE TABLE LOAD.CARGADOCUMENTOOFERTA_A (
	NRCPF 	VARCHAR(255),
	DTACAO 	date
);

COMMENT ON TABLE LOAD.CARGADOCUMENTOOFERTA_A IS 'Entidade para receber o arquivo de ativacao gabrielaativacao_aaaammddhh24mmss_nnnn.txt';
COMMENT ON COLUMN LOAD.CARGADOCUMENTOOFERTA_A.NRCPF IS 'Esta informação deve ser chave do arquivo';
COMMENT ON COLUMN LOAD.CARGADOCUMENTOOFERTA_A.DTACAO IS 'Esta informacao deve ser preenchida com a data em que ocorreu a ativacao ou desativacao do cliente no parceiro';

ALTER TABLE LOAD.CARGADOCUMENTOOFERTA_A 
ADD CONSTRAINT CARGADOCUMENTOOFERTA_ACK1
CHECK (LENGTH(NRCPF) = 11);

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_A TO INDRALOG;


CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGADOCUMENTOOFERTA_A
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGADOCUMENTOOFERTA_A';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO BATCHPRO;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_A TO INDRALOG;

