#Install header files
#This makefile copy client header file
#
#Module Name:
#    makefile
#
#Abstract:
#	Copy RouterClient header file to staging
#
#Author:
#    Ivan Mentone 2004-07-30
#
#Environment:
#    Router Core
#
#Revision History:
#	
#
.SILENT:
build:

clean:

install:
	echo Installing Header file: RouterClient.h
	rm -f $(TUXDIR_DES)/include/RouterClient.h
	cp include/RouterClient.h $(TUXDIR_DES)/include/RouterClient.h
	
all:
