OPTIONS (ERRORS=9999)
LOAD DATA
	INTO TABLE CUSTOMER.BLACKLISTDADOS
	FIELDS TERMINATED BY "|" TRAILING NULLCOLS
	(
		IDBLACKLISTDADOS SEQUENCE(MAX, 1), 
		NRC "TRANSLATE (:NRC,'0'||TRANSLATE (:NRC,'x0123456789','x'),'0')", 
		SGTECNOLOGIA "TRIM(TRANSLATE(:SGTECNOLOGIA,'0'||TRANSLATE(:SGTECNOLOGIA,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-', ' '),'0'))", 
		DTINSERCAO "sysdate"
	)
