set echo off
set feed off
set pages 0
set lines 32767
set trimspool on
set timing off
set termout off
set verify off
 
spool data/&1

SELECT 'COD_FTTX|CHAVE_END|NOME_CONDOMINIO|CLASSE SOCIAL|TIPO DE CONDOMÍNIO|SEGMENTO|LAYOUT DO CONDOMÍNIO|PRIORIDADE|SEGMENTACAO_MKT|COD_LOG|CHAVE_CEP|QTDE_BLOCOS|QTDE_APTOS|CNL|AREA_TELEFONICA|ENDERECO|NUMERO|NUMERO 2|CEP|BAIRRO|CIDADE|REGIAO|UF|STATUS_INFRA|DATA_CONCL_INFRA|CAPACIDADE_EQUIPAMENTO|FIBRA_LIVRE|PERCENTUAL_OCUPACAO|OPERAÇÃO COMERCIAL|QTDE_ANDARES_BLOCO|QTDE_APTO_ANDAR|QTDE_DORM_APTO|METRAGEM_APTOS|IDADE_EDIFICIO|SINDICO_NOME|SINDICO_APTO|SINDICO_TEL_RES|SINDICO_TEL_COML|SINDICO_TEL_CEL|ZELADOR_NOME|ZELADOR_APTO|ZELADOR_TEL_RES|ZELADOR_TEL_CEL|ZELADOR_TEL_COML|ZELADOR_TEL_PORTARIA|LONGITUDE|LATITUDE|OBS|NOME_ PROSPECTOR|NOME_EPS_PROSPECTOR|USUARIO_PROSPECTOR|NUM_CART|MOTIVO_TABULAÇÃO_PROSPECÇÃO|SUBMOTIVO_TABULAÇÃO_PROSPECÇÃO|DATA_TABULAÇÃO_PROSPECÇÃO' FROM DUAL;

SELECT 
        COND.CDFTTX || '|' || 
        COND.CDCNL || COND.CDLOGRADOUROCSO || COND.NRLOGRADOURO || '|' ||
        COND.NMCONDOMINIO || '|' ||
        COND.SGCLASSESOCIAL || '|' ||
        COND.DSTIPOCONDOMINIO || '|' ||
        COND.SGSEGMENTOAREA || '|' ||
        COND.DSLAYOUTCONDOMINIO || '|' ||
        COND.NRPRIORIDADEATENDIMENTO || '|' ||
        COND.SGSEGMENTOSERASA || '|' ||
        COND.CDLOGRADOUROCSO || '|' ||
        COND.CDCEP || COND.NRLOGRADOURO || '|' ||
        COND.QTBLOCO || '|' ||
        COND.QTAPARTAMENTO || '|' ||
        COND.CDCNL || '|' ||
        COND.SGAREATELEFONICA || '|' ||
        COND.DSLOGRADOURO || '|' ||
        COND.NRLOGRADOURO || '|' ||
        COND.NRLOGRADOUROSECUNDARIO || '|' ||
        COND.CDCEP || '|' ||
        COND.DSBAIRROLOGRADOURO || '|' ||
        COND.DSCIDADELOGRADOURO || '|' ||
        COND.DSREGIAOLOGRADOURO || '|' ||
        COND.SGUF || '|' ||
        COND.INSTATUSINFRAESTRUTURA || '|' ||
        TO_CHAR(COND.DTCONCLUSAOINFRAESTRUTURA, 'DD/MM/YYYY HH24:MI:SS') || '|' ||
        COND.QTFIBRALIMITE || '|' ||
        COND.QTFIBRALIVRE || '|' ||
        COND.PCOCUPACAO || '|' ||
        COND.DSOPERACAOCOMERCIAL || '|' ||
        COND.QTAPARTAMENTOANDAR || '|' ||
        COND.QTDORMITORIOAPARTAMENTO || '|' ||
        COND.QTMETRAGEMAPARTAMENTO || '|' ||
        COND.QTIDADECONDOMINIO || '|' ||
        COND.QTAPARTAMENTOANDAR || '|' ||
        COND.NMSINDICO || '|' ||
        COND.NRAPARTAMENTOSINDICO || '|' ||
        COND.NRTELRESSINDICO || '|' ||
        COND.NRTELCOMSINDICO || '|' ||
        COND.NRTELCELSINDICO || '|' ||
        COND.NMZELADOR || '|' ||
        COND.NRAPARTAMENTOZELADOR || '|' ||
        COND.NRTELRESZELADOR || '|' ||
        COND.NRTELCOMZELADOR || '|' ||
        COND.NRTELCELZELADOR || '|' ||
        COND.NRTELPORTCONDOMINIO || '|' ||
        COND.NRLONGITUDE || '|' ||
        COND.NRLATITUDE || '|' ||
        COND.DSOBSERVACAO || '|' ||
        CARTP.NMPROSPECTOR || '|' ||
        CARTP.DSFORNECEDORPROSPECTOR || '|' ||
        CARTP.CDUSUARIOPROSPECTOR || '|' ||
        CARTP.NRCARTEIRAPROSPECTOR || '|' ||
        (SELECT MOT.DSMOTIVOTABULACAO
            FROM SFA.SUBMOTIVOTABULACAO SUBMOT, SFA.MOTIVOTABULACAO MOT
            WHERE CARTP.IDSUBMOTIVOTABULACAO = SUBMOT.IDSUBMOTIVOTABULACAO
                AND SUBMOT.IDMOTIVOTABULACAO = MOT.IDMOTIVOTABULACAO) || '|' ||
        (SELECT SUBMOT.DSSUBMOTIVOTABULACAO
            FROM SFA.SUBMOTIVOTABULACAO SUBMOT
            WHERE CARTP.IDSUBMOTIVOTABULACAO = SUBMOT.IDSUBMOTIVOTABULACAO) || '|' ||
        TO_CHAR(CARTP.DTSUBMOTIVOTABULACAO, 'DD/MM/YYYY HH24:MI:SS')       
FROM SFA.CONDOMINIO COND, SFA.CARTEIRAPROSPECT CARTP
    WHERE CARTP.IDCONDOMINIO = COND.IDCONDOMINIO
      AND CARTP.DTULTIMAALTERACAO >= (SYSDATE - 7);
     
spool off

exit;