
set time on
set timing on
set echo on
spool CUSTOMER.BLACKLISTDADOS.log


CREATE TABLE CUSTOMER.BLACKLISTDADOS
(
	IDBLACKLISTDADOS	NUMBER			NOT NULL,
	NRC					VARCHAR2(255)	NOT NULL,
	SGTECNOLOGIA		VARCHAR2(255)	NOT NULL,
	DTINSERCAO			DATE			NOT NULL,
	CONSTRAINT BLACKLISTDADOSPK PRIMARY KEY (
		IDBLACKLISTDADOS, 
		NRC,
		SGTECNOLOGIA
	) ENABLE
);

COMMENT ON COLUMN CUSTOMER.BLACKLISTDADOS.IDBLACKLISTDADOS IS 'Identificador unico do registro';
COMMENT ON COLUMN CUSTOMER.BLACKLISTDADOS.NRC IS 'NRC';
COMMENT ON COLUMN CUSTOMER.BLACKLISTDADOS.SGTECNOLOGIA IS 'Sigla da tecnologia';
COMMENT ON COLUMN CUSTOMER.BLACKLISTDADOS.DTINSERCAO IS 'Data em que o registro foi inserido na tabela';

GRANT INSERT,SELECT,UPDATE,DELETE ON CUSTOMER.BLACKLISTDADOS TO BATCHPRO;
GRANT INSERT,SELECT,UPDATE,DELETE ON CUSTOMER.BLACKLISTDADOS TO BATCHHV;
GRANT INSERT,SELECT,UPDATE,DELETE ON CUSTOMER.BLACKLISTDADOS TO BATCHDES;


spool off
set echo off
set time off
set timing off
