
set time on
set timing on
set echo on
spool SP_TRUNCBLACKLISTDADOS.log


CREATE OR REPLACE PROCEDURE CUSTOMER.SP_TRUNCBLACKLISTDADOS
IS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER.BLACKLISTDADOS';
END;
/

GRANT EXECUTE ON CUSTOMER.SP_TRUNCBLACKLISTDADOS TO BATCHPRO;
GRANT EXECUTE ON CUSTOMER.SP_TRUNCBLACKLISTDADOS TO BATCHHV;
GRANT EXECUTE ON CUSTOMER.SP_TRUNCBLACKLISTDADOS TO BATCHDES;


spool off
set echo off
set time off
set timing off
