//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.30 at 04:41:53 PM GMT-03:00 
//


package br.com.indrasistemas.vivoservices.atendimento.servicos.desbloqueio.tuxgateway.saida;


/**
 * Java content class for msg element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/atendimento/servicos/desbloqueio/tuxgateway/saida/desbloqueioOUT.xsd line 5)
 * <p>
 * <pre>
 * &lt;element name="msg" type="{}msgType"/>
 * </pre>
 * 
 */
public interface Msg
    extends javax.xml.bind.Element, br.com.indrasistemas.vivoservices.atendimento.servicos.desbloqueio.tuxgateway.saida.MsgType
{


}
