//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.21 at 06:03:02 PM BRST 
//


package br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm;


/**
 * Java content class for CombosType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/administracaosistema/usuario/manter/tuxgateway/entrada/grvidm/IDMPerfilVO.xsd line 54)
 * <p>
 * <pre>
 * &lt;complexType name="CombosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="nmSelect">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Grupo"/>
 *             &lt;enumeration value="Operadora"/>
 *             &lt;enumeration value="Perfil"/>
 *             &lt;enumeration value="ItemMenu"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CombosType {


    /**
     * Gets the value of the NmSelect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the NmSelect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNmSelect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.CombosType.NmSelect}
     * 
     */
    java.util.List getNmSelect();


    /**
     * Java content class for nmSelect element declaration.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/administracaosistema/usuario/manter/tuxgateway/entrada/grvidm/IDMPerfilVO.xsd line 56)
     * <p>
     * <pre>
     * &lt;element name="nmSelect">
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="Grupo"/>
     *     &lt;enumeration value="Operadora"/>
     *     &lt;enumeration value="Perfil"/>
     *     &lt;enumeration value="ItemMenu"/>
     *   &lt;/restriction>
     * &lt;/element>
     * </pre>
     * 
     */
    public interface NmSelect
        extends javax.xml.bind.Element
    {


        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getValue();

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setValue(java.lang.String value);

    }

}
