//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.21 at 06:03:02 PM BRST 
//


package br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm;


/**
 * Java content class for ListaType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/administracaosistema/usuario/manter/tuxgateway/entrada/grvidm/IDMPerfilVO.xsd line 68)
 * <p>
 * <pre>
 * &lt;complexType name="ListaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nmSelect" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Disponivel" type="{}ItemType"/>
 *         &lt;element name="Selecionado" type="{}ItemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ListaType {


    /**
     * Gets the value of the nmSelect property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNmSelect();

    /**
     * Sets the value of the nmSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNmSelect(java.lang.String value);

    /**
     * Gets the value of the selecionado property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType}
     */
    br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType getSelecionado();

    /**
     * Sets the value of the selecionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType}
     */
    void setSelecionado(br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType value);

    /**
     * Gets the value of the disponivel property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType}
     */
    br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType getDisponivel();

    /**
     * Sets the value of the disponivel property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType}
     */
    void setDisponivel(br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.grvidm.ItemType value);

}
