SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

SPOOL &1;
SELECT 	/*+ parallel(lt,16) parallel(lb,16) */
    AR.CDAREAREGISTRO||LB.NRLINHA ||';'||
    PEPUP.CDPERMISSAOPUP ||';'||
    PUP.DTULTIMAALTERACAO
FROM
    LINHA.PERMISSAOLINHAPUP PUP,
    LINHA.PERMISSAOPUP PEPUP,
    LINHA.LINHATELEFONICA LT,
    LINHA.LINHABASE LB,
    APOIO.AREAREGISTRO AR
WHERE
    PUP.SGPERMISSAOPUP = PEPUP.SGPERMISSAOPUP
AND PEPUP.CDPERMISSAOPUP != '-1'
AND PUP.IDLINHATELEFONICA = LT.IDLINHATELEFONICA
AND LT.IDLINHABASE = LB.IDLINHABASE
AND LB.IDAREAREGISTRO = AR.IDAREAREGISTRO
AND LT.IDSISTEMAORIGEM IN (1,2,3,11)
AND LB.NRDIGITOLINHA IS NULL
AND LT.DTEXPIRACAO IS NULL
AND PUP.INATIVO = 0
;
SPOOL OFF;

EXIT 0
