/*#########################################################
#  BATCH......: expurgoParamProgRelacionamento
#  Criado por.: Williams Santos 26/10/2016
#  Funcional..: Dener
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE

    TYPE T_PARAMPR IS RECORD
    (          
        ROWIDOC    ROWID                                                          
    );
   
   TYPE TB_PARAMPR IS TABLE OF T_PARAMPR INDEX BY BINARY_INTEGER;  
   V_PARAMPR TB_PARAMPR;
   
   V_TEMPO_EXPURGO NUMBER := 90;
   
   CURSOR crs is
   SELECT ROWID AS ROWIDOC
     FROM VIVOVALORIZA.PARAMPROGRELACIONAMENTO PPR
    WHERE TRUNC(PPR.DTULTIMAALTERACAO) <= TRUNC(SYSDATE-V_TEMPO_EXPURGO);

    V_LIMITE      NUMBER := 5000;
    V_DONE        BOOLEAN;    

BEGIN

    OPEN crs;
    LOOP    
    FETCH crs BULK COLLECT INTO V_PARAMPR LIMIT V_LIMITE;
        V_DONE := crs%NOTFOUND;

        FORALL R IN 1 .. V_PARAMPR.COUNT
        DELETE VIVOVALORIZA.PARAMPROGRELACIONAMENTO PPR
         WHERE PPR.ROWID = V_PARAMPR(R).ROWIDOC;
         
        COMMIT;
        EXIT WHEN (V_DONE);
        
    END LOOP;

END;
/

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT