<!--Generated by Weblogic Workshop-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="netui-tags-template.tld" prefix="netui-template"%>
<%@ taglib uri="netui-tags-databinding.tld" prefix="netui-data"%>
<%@ taglib uri="netui-tags-html.tld" prefix="netui"%>

<html>
  <head>
    <netui:base />
    <title><netui-template:attribute name="FrontOffice - Administração do Sistema"/></title>
    <link href="<%=request.getContextPath()%>/resources/css/frontoffice.css" type="text/css" rel="stylesheet"/>
    <link href="<%=request.getContextPath()%>/resources/css/xtree.css" type="text/css" rel="stylesheet"/>
    <!-- link rel="StyleSheet" href="dtree.css" type="text/css" / -->

    <script type="text/javascript" src="<%=request.getContextPath()%>/resources/scripts/abas.js"></script>
    <script type="text/javascript" src="<%=request.getContextPath()%>/resources/scripts/xtree.js"></script>
    
  </head>
  <body topmargin="0" leftmargin="0">
    <netui-template:includeSection name="bodySection">    
    </netui-template:includeSection>
  </body>
</html>
