<!--Generated by Weblogic Workshop-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="netui-tags-template.tld" prefix="netui-template"%>
<%@ taglib uri="netui-tags-databinding.tld" prefix="netui-data"%>
<%@ taglib uri="netui-tags-html.tld" prefix="netui"%>
<html>
<head>
    <netui:base />
    <title><netui-template:attribute name="FrontOffice - Gestão do Usuário"/></title>
    <link rel="STYLESHEET" type="text/css" href="<%=request.getContextPath()%>/resources/css/frontoffice.css">        
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/resources/css/xtree.css"/>
    <script language="javascript"  src="<%=request.getContextPath()%>/resources/scripts/prototype.js" ></script>
    <script language="javascript"  src="<%=request.getContextPath()%>/resources/scripts/frameweb.js" ></script>
    <script language="javascript"  src="<%=request.getContextPath()%>/resources/scripts/vivoheader.js" ></script>
    <script language="javascript"  src="<%=request.getContextPath()%>/resources/scripts/vivomenu.js" ></script>
    <script type="text/javascript" src="<%=request.getContextPath()%>/resources/scripts/xtree.js"></script>
    <netui-template:includeSection name="headerSection"></netui-template:includeSection>
</head>
<body topmargin="0" leftmargin="0">
    <netui-template:includeSection name="bodySection"></netui-template:includeSection>
</body>
</html>
