/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Eder Jani Martins (11/02/2015)
  Alterado por: Lucas Gomes(03/09/2015)
  Funcional..: Marcia Santana Silva
***********************************************************/
SET SQLPROMPT ''
SET TERMOUT OFF
SET FEEDBACK OFF
SET ECHO OFF
SET AUTOTRACE OFF
SET FLUSH ON
SET HEADING OFF
SET TIME OFF
SET TIMING OFF
SET TRIMOUT ON
SET TRIMSPOOL ON
SET PAUSE OFF
SET SHOWMODE OFF
SET SQLBLANKLINES OFF
SET SQLNUMBER OFF
SET TAB OFF
SET VERIFY OFF
SET WRAP OFF
SET FEED OFF
SET NEWPAGE NONE
SET SERVEROUTPUT ON SIZE UNLIMITED
set echo off trimspool on pagesize 0 underline off feedback off verify off termout off timing off time off linesize 4000;
SET LINESIZE 32767
SPOOL &1

/* ------------------------------------ MEUVIVODW_ATD  ------------------------------------*/
BEGIN
	LOAD.PRC_MEUVIVODW_TRUNCA_TABELA('ATD');
END;
/

DECLARE
	V_DATA_CRITERIO1 VARCHAR2(255);
	V_DATA_CRITERIO2 VARCHAR2(255);
	V_DATA_CRITERIO3 VARCHAR2(255);
BEGIN
	V_DATA_CRITERIO1 := '&2';
	V_DATA_CRITERIO2 := '&3';
	V_DATA_CRITERIO3 := '&4';

	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_ATD
	SELECT /*+ PARALLEL (64) */
		   AA.IDATENDIMENTO,
		   AA.IDATENDIMENTOPROTOCOLO,
		   AA.IDCANAL,
		   AA.IDCONTATO,
		   AA.IDPESSOALINHAHISTORICO,
		   AA.IDTIPOLINHA,
		   AA.IDTIPOCARTEIRA,
		   AA.DTABERTURA,
		   AA.DTULTIMAALTERACAO
	FROM ATENDIMENTO.ATENDIMENTO AA
	WHERE AA.DTABERTURA >= TO_DATE(V_DATA_CRITERIO1 || ' 00:00:00','yyyymmdd hh24:mi:ss')
	  AND AA.DTABERTURA <  
			CASE
				WHEN (TO_DATE(V_DATA_CRITERIO1, 'YYYYMMDD')+V_DATA_CRITERIO2-1) > TO_DATE(V_DATA_CRITERIO3, 'YYYYMMDD') THEN
					TO_DATE(V_DATA_CRITERIO1 || ' 00:00:00','yyyymmdd hh24:mi:ss')+(TO_DATE(V_DATA_CRITERIO3, 'YYYYMMDD')-TO_DATE(V_DATA_CRITERIO1, 'YYYYMMDD')+1)
				ELSE
					TO_DATE(V_DATA_CRITERIO1 || ' 00:00:00','yyyymmdd hh24:mi:ss')+V_DATA_CRITERIO2
			END;
END;
/

/* ------------------------------------ MEUVIVODW_ATD_PRT  ------------------------------------*/
BEGIN
	LOAD.PRC_MEUVIVODW_TRUNCA_TABELA('ATD_PRT');
END;
/

BEGIN
	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_ATD_PRT
	SELECT /*+ PARALLEL (32) */
		   MA.IDATENDIMENTO,
		   MA.IDATENDIMENTOPROTOCOLO,
		   MA.IDCANAL,
		   MA.IDCONTATO,
		   MA.IDPESSOALINHAHISTORICO,
		   MA.IDTIPOLINHA,
		   MA.IDTIPOCARTEIRA,
		   MA.DTABERTURA AS DTABERTURA_A,
		   MA.DTULTIMAALTERACAO,
		   AP.CDAREAREGISTRO,
		   AP.NRTELEFONE,
		   AP.IDLINHATELEFONICA,
		   AP.IDPESSOADEPARA,
		   AP.DTABERTURA AS DTABERTURA_AP,
		   AP.CDCONTA,
		   AP.IDSISTEMAORIGEM
	FROM LOAD.MEUVIVODW_ATD MA,
		 ATENDIMENTO.ATENDIMENTOPROTOCOLO AP
	WHERE AP.IDATENDIMENTOPROTOCOLO = MA.IDATENDIMENTOPROTOCOLO;
END;
/

COMMIT;

/* ------------------------------------ SPOOL  ------------------------------------*/

SELECT /*+ PARALLEL (16) */
       CP.SGSERVICO
       ||'|'||CP.DSSERVICO
       ||'|'||CP.IDCONTATO
       ||'|'||MV.IDPESSOALINHAHISTORICO
       ||'|'||MV.CDAREAREGISTRO
       ||'|'||MV.NRTELEFONE
       ||'|'||MV.IDLINHATELEFONICA
       ||'|'||MV.IDPESSOADEPARA
       ||'|'||MV.CDCONTA
       ||'|'||MV.IDTIPOLINHA
       ||'|'||MV.IDTIPOCARTEIRA
       ||'|'||MV.IDCANAL
       ||'|'||TO_CHAR(MV.DTABERTURAATD, 'dd/mm/yyyy hh24:mi:ss' )
       ||'|'||TO_CHAR(MV.DTABERTURAPRT, 'dd/mm/yyyy hh24:mi:ss' )
       ||'|'||MV.IDATENDIMENTO
       ||'|'||MV.IDATENDIMENTOPROTOCOLO
       ||'|'||DECODE(  C.NMPATH, NULL, ';;;;;',
					CASE WHEN
							LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)) < 6
						THEN
							CASE WHEN
									LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)) < 5
								 THEN
									REPLACE(
										RPAD(C.NMPATH,LENGTH(C.NMPATH) + (5 - (LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)))), '/'),'/',';')
								 ELSE
									REPLACE(C.NMPATH,'/',';')
								 END
						ELSE
							REPLACE(SUBSTR(C.NMPATH, 0, INSTR(C.NMPATH, '/', 1, 6)-1),'/',';')
					END
				   )
 FROM LOAD.MEUVIVODW_ATD_PRT MV
INNER JOIN APOIO.CANAL AC
   ON AC.IDCANAL = MV.IDCANAL
INNER JOIN CONTATOADM.CONTATO C
   ON C.IDCONTATO = MV.IDCONTATO
 LEFT JOIN CONTATOADM.CONFIGURAPALITAGEM CP
   ON CP.IDCONTATO = C.IDCONTATO 
  AND CP.IDSISTEMAORIGEM = MV.IDSISTEMAORIGEM
WHERE AC.NMCANAL IN ('TAV','VOL','VOLE','Meu Vivo Mobile','Meu Vivo Lojas','Meu Vivo Site Mobile','Meu Vivo Site Mobile Fixa');
/

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
