/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
   LOAD.TRUNC_MEUVIVODW_DOC_CONTAS;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

INSERT INTO LOAD.MEUVIVODW_DOC_CONTAS (RID, NRDOCUMENTO, IDPESSOADEPARA, CDCONTA)
SELECT /*+ FULL(DW) PARALLEL(128) */
    DW.ROWID AS RID,
    DC.NRDOCUMENTO NRDOCUMENTO,
    PP.IDPESSOADEPARA,
    CDCONTA
FROM
    LOAD.MEUVIVODW_01 DW
    JOIN CUSTOMER.CONTA CC USING (CDCONTA)
    JOIN CUSTOMER.PESSOACONTA PC USING (IDCONTA)
    JOIN CUSTOMER.PESSOADEPARA PP ON (PC.IDPESSOADEPARA = PP.IDPESSOADEPARA)
    JOIN CUSTOMER.PESSOADOCUMENTO PD USING (IDPESSOA)
    JOIN CUSTOMER.DOCUMENTO DC USING (IDDOCUMENTO)
    JOIN APOIO.TIPODOCUMENTO TP USING (IDTIPODOCUMENTO)
    LEFT JOIN LOAD.MEUVIVODW_DOC_MARCAS DW3 ON DW3.RID = DW.ROWID
WHERE
    TP.SGCLASSIFICACAO IN ('CPF','CNPJ')
    AND DW3.NRDOCUMENTO IS NULL;

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
