/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

/* ------------------------------------ MEUVIVODW_DOC_MARCAS  ------------------------------------*/
BEGIN
    LOAD.TRUNC_MEUVIVODW_DOC_MARCAS;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

INSERT INTO LOAD.MEUVIVODW_DOC_MARCAS (RID, NRDOCUMENTO, DSNOME, DSEMAIL)
SELECT /*+ FULL(DW) PARALLEL(64) */
    DW.ROWID AS RID,
    LOMAR.NRDOCUMENTO,
    LOMAR.DSNOME,
    LOMAR.DSEMAIL
FROM
    LOAD.MEUVIVODW_01 DW
    JOIN ACESSO.LINHASMARCAS LIMAR ON (TO_CHAR(LIMAR.CDAREAREGISTRO) = DW.CDAREAREGISTRO AND TO_CHAR(LIMAR.NRLINHA) = DW.NRTELEFONE)
    JOIN ACESSO.LOGINMARCAS LOMAR USING (IDLOGIN);

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
