/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
	LOAD.PRC_MEUVIVODW_TRUNCA_TABELA('ATD_PRT');
END;
/

BEGIN
	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_ATD_PRT
	SELECT /*+ PARALLEL (32) */
		   MA.IDATENDIMENTO,
		   MA.IDATENDIMENTOPROTOCOLO,
		   MA.IDCANAL,
		   MA.IDCONTATO,
		   MA.IDPESSOALINHAHISTORICO,
		   MA.IDTIPOLINHA,
		   MA.IDTIPOCARTEIRA,
		   MA.DTABERTURA AS DTABERTURA_A,
		   MA.DTULTIMAALTERACAO,
		   AP.CDAREAREGISTRO,
		   AP.NRTELEFONE,
		   AP.IDLINHATELEFONICA,
		   AP.IDPESSOADEPARA,
		   AP.DTABERTURA AS DTABERTURA_AP,
		   AP.CDCONTA,
		   AP.IDSISTEMAORIGEM
	FROM LOAD.MEUVIVODW_ATD MA,
		 ATENDIMENTO.ATENDIMENTOPROTOCOLO AP
	WHERE AP.IDATENDIMENTOPROTOCOLO = MA.IDATENDIMENTOPROTOCOLO;
END;
/

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
