/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
    LOAD.TRUNC_MEUVIVODW_TMP_OUT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

INSERT INTO LOAD.MEUVIVODW_TMP_OUT (RID, DSNOME, DSEMAIL, NRDOCUMENTO, CDAREAREGISTRO, NRLINHA, SGSERVICO, DSSERVICO, IDCANAL, NMCANAL, INTRAFEGODADOS, INSALDOPONTO,
INATENDIMENTOAGENDADO, DTABERTURA, DTULTIMAALTERACAO, IDATENDIMENTO, IDATENDIMENTOPROTOCOLO, NMPATH)
SELECT /*+ PARALLEL(64) */
    DW.ROWID AS RID,
    REPLACE(DW_LM.DSNOME,';','') AS DSNOME,
    REPLACE(DW_LM.DSEMAIL,';','') AS DSEMAIL,
    CASE
        WHEN DW_LM.NRDOCUMENTO  IS NOT NULL THEN DW_LM.NRDOCUMENTO
        WHEN DW_CT.NRDOCUMENTO  IS NOT NULL THEN DW_CT.NRDOCUMENTO
        WHEN DW_PDP.NRDOCUMENTO IS NOT NULL THEN DW_PDP.NRDOCUMENTO
        ELSE NULL
    END AS NRDOCUMENTO,
    DW.CDAREAREGISTRO,
    DW.NRTELEFONE AS NRLINHA,
    DW.SGSERVICO,
    DW.DSSERVICO,
    DW.IDCANAL,
    (SELECT NMCANAL FROM APOIO.CANAL WHERE IDCANAL = DW.IDCANAL) AS NMCANAL,
    DECODE(DW.SGSERVICO, 'ConsultaTrafegoDados',1,0) AS ConsultaTrafegoDados,
    DECODE(DW.SGSERVICO, 'ContatoSaldoPonto',1,0) AS ContatoSaldoPonto,
    DECODE(DW.SGSERVICO, 'ContatoAtendimentoAgendado',1,0) AS ContatoAtendimentoAgendado,
    DW.DTABERTURA,
    DW.DTULTIMAALTERACAO,
    DW.IDATENDIMENTO,
    DW.IDATENDIMENTOPROTOCOLO,
    DW.NMPATH
FROM
    LOAD.MEUVIVODW_01 DW
    LEFT JOIN LOAD.MEUVIVODW_DOC_PESSOA DW_PDP ON (DW.ROWID = DW_PDP.RID)
    LEFT JOIN LOAD.MEUVIVODW_DOC_CONTAS DW_CT  ON (DW.ROWID = DW_CT.RID)
    LEFT JOIN LOAD.MEUVIVODW_DOC_MARCAS DW_LM  ON (DW.ROWID = DW_LM.RID);
/

COMMIT;

--DELETE /*+ PARALLEL(64) */ FROM LOAD.MEUVIVODW_TMP_OUT DW WHERE ROWID != (SELECT MIN(ROWID) FROM LOAD.MEUVIVODW_TMP_OUT WHERE RID = DW.RID);
--/

--COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
