/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Eder Jani Martins (11/02/2015)
  Alterado por: Lucas Gomes(03/09/2015)
  Alterado por: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum / Antecessor: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
	LOAD.PRC_MEUVIVODW_TRUNCA_TABELA('01');
END;
/

BEGIN
	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_01 (SGSERVICO, DSSERVICO, IDCONTATO, IDPESSOALINHAHISTORICO, CDAREAREGISTRO, NRTELEFONE, IDLINHATELEFONICA, IDPESSOADEPARA, 
												IDTIPOLINHA, IDTIPOCARTEIRA, IDCANAL, DTABERTURA, DTULTIMAALTERACAO, IDATENDIMENTO, IDATENDIMENTOPROTOCOLO, NMPATH, CDCONTA)
	SELECT /*+ PARALLEL (16) */
		   CP.SGSERVICO,
		   CP.DSSERVICO,
		   CP.IDCONTATO,
		   MV.IDPESSOALINHAHISTORICO,
		   MV.CDAREAREGISTRO,
		   MV.NRTELEFONE,
		   MV.IDLINHATELEFONICA,
		   MV.IDPESSOADEPARA,
		   MV.IDTIPOLINHA,
		   MV.IDTIPOCARTEIRA,
		   MV.IDCANAL,
		   MV.DTABERTURAATD, 
		   MV.DTABERTURAPRT,
		   MV.IDATENDIMENTO,
		   MV.IDATENDIMENTOPROTOCOLO,
		   DECODE(  C.NMPATH, NULL, ';;;;;',
					CASE WHEN
							LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)) < 6
						THEN
							CASE WHEN
									LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)) < 5
								 THEN
									REPLACE(
										RPAD(C.NMPATH,LENGTH(C.NMPATH) + (5 - (LENGTH(C.NMPATH) - LENGTH(REPLACE(C.NMPATH,'/', NULL)))), '/'),'/',';')
								 ELSE
									REPLACE(C.NMPATH,'/',';')
								 END
						ELSE
							REPLACE(SUBSTR(C.NMPATH, 0, INSTR(C.NMPATH, '/', 1, 6)-1),'/',';')
					END
				   ),
		   MV.CDCONTA
	 FROM LOAD.MEUVIVODW_ATD_PRT MV
	INNER JOIN APOIO.CANAL AC
	   ON AC.IDCANAL = MV.IDCANAL
	INNER JOIN CONTATOADM.CONTATO C
	   ON C.IDCONTATO = MV.IDCONTATO
	 LEFT JOIN CONTATOADM.CONFIGURAPALITAGEM CP
	   ON CP.IDCONTATO = C.IDCONTATO
	  AND CP.IDSISTEMAORIGEM = MV.IDSISTEMAORIGEM
	WHERE AC.NMCANAL IN ('TAV','VOL','VOLE','Meu Vivo Mobile','Meu Vivo Lojas','Meu Vivo Site Mobile','Meu Vivo Site Mobile Fixa');
END;
/

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
