/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
    LOAD.TRUNC_MEUVIVODW_NRTEL;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN

INSERT INTO LOAD.MEUVIVODW_NRTELEFONE(
        IDATENDIMENTO, 
        CDAREAREGISTRO, 
        NRTELEFONE
        )
SELECT  
        MV1.IDATENDIMENTO,
        PLH.CDAREAREGISTRO,
        PLH.NRLINHA
FROM
        LOAD.MEUVIVODW_01 MV1
JOIN    APOIO.CANAL AC
ON      AC.IDCANAL = MV1.IDCANAL
JOIN    CUSTOMER.PESSOALINHAHISTORICO PLH
ON      PLH.IDPESSOALINHAHISTORICO = MV1.IDPESSOALINHAHISTORICO
JOIN    LINHA.LINHATELEFONICA LT
ON      LT.IDLINHATELEFONICA  = PLH.IDLINHATELEFONICA
WHERE
        AC.NMCANAL = 'VOLE'
AND     MV1.NRTELEFONE IS NULL
AND     LT.IDLINHABASE IS NOT NULL
AND		LT.IDLINHABASE <> 0;

COMMIT;

END;
/

BEGIN
    MERGE INTO LOAD.MEUVIVODW_01 MV1
     USING (SELECT DISTINCT
				   MNT.IDATENDIMENTO, 
                   MNT.CDAREAREGISTRO, 
                   MNT.NRTELEFONE
              FROM LOAD.MEUVIVODW_NRTELEFONE MNT
           ) MNT
        ON (MV1.IDATENDIMENTO = MNT.IDATENDIMENTO)
      WHEN MATCHED THEN
    UPDATE SET MV1.CDAREAREGISTRO = MNT.CDAREAREGISTRO,
               MV1.NRTELEFONE = MNT.NRTELEFONE;
    COMMIT;
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
