/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
	LOAD.PRC_MEUVIVODW_TRUNCA_TABELA('ATD');
END;
/

DECLARE
    V_DATA_CRITERIO VARCHAR2(255);
BEGIN
	V_DATA_CRITERIO := '&1';

	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_ATD
	SELECT /*+ PARALLEL (64) */
		   AA.IDATENDIMENTO,
		   AA.IDATENDIMENTOPROTOCOLO,
		   AA.IDCANAL,
		   AA.IDCONTATO,
		   AA.IDPESSOALINHAHISTORICO,
		   AA.IDTIPOLINHA,
		   AA.IDTIPOCARTEIRA,
		   AA.DTABERTURA,
		   AA.DTULTIMAALTERACAO
	FROM ATENDIMENTO.ATENDIMENTO AA
	WHERE AA.DTABERTURA >= TO_DATE(V_DATA_CRITERIO || ' 00:00:00','DD/MM/YYYY HH24:MI:SS')
	  AND AA.DTABERTURA <  TO_DATE(V_DATA_CRITERIO || ' 00:00:00','DD/MM/YYYY HH24:MI:SS') + 1;
END;
/

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
