LOAD DATA 
APPEND
INTO TABLE LOAD.MEUVIVODW_01
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	SGSERVICO,
	DSSERVICO,
	IDCONTATO,
	IDPESSOALINHAHISTORICO,
	CDAREAREGISTRO,
	NRTELEFONE,
	IDLINHATELEFONICA,
	IDPESSOADEPARA,
	CDCONTA,
	IDTIPOLINHA,
	IDTIPOCARTEIRA,
	IDCANAL,
	DTABERTURA DATE 'DD/MM/YYYY HH24:MI:SS',
	DTULTIMAALTERACAO DATE 'DD/MM/YYYY HH24:MI:SS',
	IDATENDIMENTO,
	IDATENDIMENTOPROTOCOLO,
	NMPATH
)
