LOAD DATA 
APPEND
INTO TABLE LOAD.MEUVIVODW_02
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
	DSNOME,
    DSEMAIL,
    NRDOCUMENTO,
    CDAREAREGISTRO,
    NRLINHA,
    CDFIXOMOVEL,
    DSCANAL,
    INDATIVOFB,
    INSTATUS,
    INATIVO,
    QTERROLOGIN,
    DTCADASTRO,
    HHCADASTRO,
    DTULTIMOACESSO,
    HHULTIMOACESSO,
    INPLATAFORMA,
    DSTIPOCARTEIRA,
    DSSEGMENTACAO
)
