/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Lucas Gomes(26/01/2016)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
    LOAD.TRUNC_MEUVIVODW_DOC_PESSOA;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

INSERT INTO LOAD.MEUVIVODW_DOC_PESSOA (RID, NRDOCUMENTO)
SELECT /*+ FULL(DW) PARALLEL(64) */
    DW.ROWID AS RID,
    DC.NRDOCUMENTO NRDOCUMENTO
FROM
    LOAD.MEUVIVODW_01 DW
    JOIN CUSTOMER.PESSOADEPARA PDP USING (IDPESSOADEPARA)
    JOIN CUSTOMER.PESSOADOCUMENTO PD USING (IDPESSOA)
    JOIN CUSTOMER.DOCUMENTO DC USING (IDDOCUMENTO)
    JOIN APOIO.TIPODOCUMENTO TP USING (IDTIPODOCUMENTO)
    LEFT JOIN LOAD.MEUVIVODW_DOC_MARCAS DW2 ON DW2.RID = DW.ROWID
    LEFT JOIN LOAD.MEUVIVODW_DOC_CONTAS DW3 ON DW3.RID = DW.ROWID
WHERE
    TP.SGCLASSIFICACAO IN ('CPF','CNPJ')
    AND DW2.NRDOCUMENTO IS NULL
    AND DW3.NRDOCUMENTO IS NULL;

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
