/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Eder Jani Martins (11/02/2015)
  Alterado por: Lucas Gomes(03/09/2015)
  Funcional..: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
	V_ROWCOUNT NUMBER;

BEGIN
	/*
		Busca os dados de login do cliente baseado nos dados da tabela LOAD.MEUVIVODW_01 
		O resultado sera inserido em LOAD.MEUVIVODW_02
	*/
	INSERT /*+ APPEND */ INTO LOAD.MEUVIVODW_02
		(
			DSNOME,
			DSEMAIL,
			NRDOCUMENTO,
			CDAREAREGISTRO,
			NRLINHA,
			CDFIXOMOVEL,
			DSCANAL,
			IDCANAL,
			NMCANAL,
			INDATIVOFB,
			INSTATUS,
			INATIVO,
			QTERROLOGIN,
			DTCADASTRO,
			HHCADASTRO,
			DTULTIMOACESSO,
			HHULTIMOACESSO,
			INPLATAFORMA,
			DSTIPOCARTEIRA,
			DSSEGMENTACAO
		)
	SELECT /*+ PARALLEL(32) */
	       DISTINCT
           REPLACE(LOMAR.DSNOME,';',''),
		   REPLACE(LOMAR.DSEMAIL,';',''),
	       LOMAR.NRDOCUMENTO,
	       LIMAR.CDAREAREGISTRO,
	       LIMAR.NRLINHA,
	       DECODE(LIMAR.CDFIXOMOVEL, NULL, ' ', LIMAR.CDFIXOMOVEL ) AS CDFIXOMOVEL, 
	       LOMAR.CANAL,
		   MVDW.IDCANAL,
		   (SELECT NMCANAL FROM APOIO.CANAL WHERE IDCANAL = MVDW.IDCANAL) AS NMCANAL,
	       DECODE( LOMAR.INDATIVOFB, NULL, 0, LOMAR.INDATIVOFB) AS INDATIVOFB,
	       LOMAR.STATUS,
	       LOMAR.INATIVO,
	       LOMAR.QTERROLOGIN,
	       TO_CHAR(LOMAR.DTULTIMAALTERACAO, 'DD/MM/YYYY') AS DATA_CADASTRO,
	       TO_CHAR(LOMAR.DTULTIMAALTERACAO, 'hh24:mi:ss') AS HORA_CADASTRO,
	       (SELECT TO_CHAR( MAX(DTULTIMAALTERACAO), 'DD/MM/YYYY') FROM ACESSO.HISTORICOLOGINMARCAS HLOMAR WHERE HLOMAR.IDLOGIN = LOMAR.IDLOGIN) AS DTULTIMOACESSO,
	       (SELECT TO_CHAR( MAX(DTULTIMAALTERACAO), 'hh24:mi:ss') FROM ACESSO.HISTORICOLOGINMARCAS HLOMAR WHERE HLOMAR.IDLOGIN = LOMAR.IDLOGIN) AS HHULTIMOACESSO,
	       'MEUVIVO' AS INPLATAFORMA,
	       (SELECT DSTIPOCARTEIRA FROM APOIO.TIPOCARTEIRA TC WHERE TC.IDTIPOCARTEIRA = MVDW.IDTIPOCARTEIRA ) DSTIPOCARTEIRA,
	       (SELECT DSSEGMENTACAO FROM CUSTOMER.SEGMENTACAOCONSOLIDADA SC, APOIO.SEGMENTACAO S WHERE SC.NRDOCUMENTO = LOMAR.NRDOCUMENTO AND S.IDSEGMENTACAO = SC.IDSEGMETNACAOCLIENTE ) AS DSSEGMENTACAO 
	FROM ACESSO.LINHASMARCAS LIMAR,
	     ACESSO.LOGINMARCAS LOMAR,
	     LOAD.MEUVIVODW_01 MVDW
	WHERE LIMAR.IDLOGIN = LOMAR.IDLOGIN (+)
	  AND LIMAR.CDAREAREGISTRO (+) = MVDW.CDAREAREGISTRO
	  AND LIMAR.NRLINHA (+) = MVDW.NRTELEFONE;

	V_ROWCOUNT:=SQL%ROWCOUNT;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inseridas em LOAD.MEUVIVODW_02: '||V_ROWCOUNT);
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
