/***********************************************************
  BATCH......: meuVivoDW
  Criado por.: Eder Jani Martins (11/02/2015)
  Alterado por: Lucas Gomes(03/09/2015)
  Alterado por: Lucas Gomes(26/01/2016)
  Funcional..:  Erika Brum / Antecessor: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

INSERT INTO LOAD.MEUVIVODW_02
    (DSNOME,
         DSEMAIL,
         NRDOCUMENTO,
         CDAREAREGISTRO,
         NRLINHA,
         SGSERVICO,
         DSSERVICO,
         IDCANAL,
         NMCANAL,
         INCONSULTATRAFEGODADOS,
         INCONTATOSALDOPONTO,
         INCONTATOATENDIMENTOAGENDADO,
         DTABERTURA,
         DTULTIMAALTERACAO,
     IDATENDIMENTO,
     IDATENDIMENTOPROTOCOLO,
     NMPATH)
SELECT /*+ PARALELL(64)*/
    DSNOME,
    DSEMAIL,
    NRDOCUMENTO,
    CDAREAREGISTRO,
    NRLINHA,
    SGSERVICO,
    DSSERVICO,
    IDCANAL,
    NMCANAL,
    INTRAFEGODADOS,
    INSALDOPONTO,
    INATENDIMENTOAGENDADO,
    DTABERTURA,
    DTULTIMAALTERACAO,
    IDATENDIMENTO,
    IDATENDIMENTOPROTOCOLO,
    NMPATH
FROM
    LOAD.MEUVIVODW_TMP_OUT DW
WHERE ROWID IN (SELECT MIN(ROWID) FROM LOAD.MEUVIVODW_TMP_OUT MT WHERE MT.RID = DW.RID);

COMMIT;

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
