CREATE OR REPLACE PACKAGE CUSTOMER.PKG_RELATORIOROAMING
IS
    PROCEDURE TRUNCAR_TEMPORARIAS;
    PROCEDURE TRUNCAR_RELATORIO_ATUALIZACAO;
    PROCEDURE VERIFICA_DIAS_RETROATIVOS (
                        I_MIN_ATUALIZACAO   IN  NUMBER,
                        O_DIAS_RETROATIVOS  OUT NUMBER
                    );
    PROCEDURE GERA_RELATORIO_FULL;
    PROCEDURE IDENTIFICA_ATUALIZACOES(
                        I_DIA_RETROATIVO_DE  IN  NUMBER DEFAULT -1,
                        I_DIA_RETROATIVO_ATE IN  NUMBER DEFAULT  0,
                        I_MIN_ATUALIZACAO    IN  NUMBER DEFAULT  0,
                        I_MAX_RETROATIVO     IN  NUMBER DEFAULT  0
                    );
    PROCEDURE GERA_RELATORIO_ATUALIZACOES;

END PKG_RELATORIOROAMING;
/

CREATE OR REPLACE PACKAGE BODY CUSTOMER.PKG_RELATORIOROAMING
IS
    PROCEDURE TRUNCAR_TEMPORARIAS
    IS
    BEGIN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER.TMPRELATORIOROAMING';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER.TMPATUALIZACAOROAMING';
    END TRUNCAR_TEMPORARIAS;

    PROCEDURE TRUNCAR_RELATORIO_ATUALIZACAO
    IS
    BEGIN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER.TMPRELATUALIZACAOROAMING';
    END TRUNCAR_RELATORIO_ATUALIZACAO;

    PROCEDURE VERIFICA_DIAS_RETROATIVOS (
                        I_MIN_ATUALIZACAO   IN  NUMBER,
                        O_DIAS_RETROATIVOS  OUT NUMBER
    )
    IS
    BEGIN
        SELECT
            NVL(TRUNC(MAX(DTGERACAORELATORIO) - SYSDATE),-1)
        INTO
            O_DIAS_RETROATIVOS
        FROM
            CUSTOMER.TMPRELATUALIZACAOROAMING
        WHERE
            QTLINHASGERADAS > I_MIN_ATUALIZACAO;
    EXCEPTION
        WHEN OTHERS THEN
            O_DIAS_RETROATIVOS := -1;
    END VERIFICA_DIAS_RETROATIVOS;

    PROCEDURE GERA_RELATORIO_FULL
    IS
    BEGIN
        INSERT  /*+ APPEND */ INTO CUSTOMER.TMPRELATORIOROAMING (RNUM,REGISTRO)
        SELECT /*+ PARALLEL(LT) PARALLEL(LB) PARALLEL(PL) PARALLEL(PDP) PARALLEL(P) */
            ROWNUM AS RNUM,
            AR.CDAREAREGISTRO || LB .NRLINHA || ';' ||
            TO_CHAR(LT.DTHABILITACAO, 'YYYYMMDD') || ';' ||
            TO_CHAR(LT.DTEXPIRACAO, 'YYYYMMDD') || ';' ||
            TL.IDCLASSIFICACAOTIPOLINHA || ';' ||
            TP.SGTIPOPESSOA AS REGISTRO
        FROM
            LINHA.LINHATELEFONICA LT
            JOIN APOIO.SISTEMAORIGEM SO ON (LT.IDSISTEMAORIGEM = SO.IDSISTEMAORIGEM)
            JOIN APOIO.TIPOLINHA TL USING (IDTIPOLINHA)
            JOIN LINHA.LINHABASE LB USING (IDLINHABASE)
            JOIN APOIO.AREAREGISTRO AR USING (IDAREAREGISTRO)
            JOIN CUSTOMER.PESSOALINHA PL USING (IDLINHATELEFONICA)
            JOIN CUSTOMER.PESSOADEPARA PDP USING (IDPESSOADEPARA)
            JOIN CUSTOMER.PESSOA P USING (IDPESSOA)
            JOIN APOIO.TIPOPESSOA TP USING (IDTIPOPESSOA)
        WHERE
            PL.IDTIPORELACIONAMENTO = 2
            AND SO.CDORIGEM = 'MOVEL'
            AND LT.DTHABILITACAO IS NOT NULL
            AND TP.SGTIPOPESSOA IN ('PF','PJ')
            AND TL.IDCLASSIFICACAOTIPOLINHA IN ('POS','PRE','CTR');

    END GERA_RELATORIO_FULL;

    PROCEDURE IDENTIFICA_ATUALIZACOES (
                        I_DIA_RETROATIVO_DE  IN  NUMBER DEFAULT -1,
                        I_DIA_RETROATIVO_ATE IN  NUMBER DEFAULT  0,
                        I_MIN_ATUALIZACAO    IN  NUMBER DEFAULT  0,
                        I_MAX_RETROATIVO     IN  NUMBER DEFAULT  0
    )
    IS
        V_DIA_RETROATIVO_DE NUMBER;
        V_DTDE DATE := TRUNC(SYSDATE+I_DIA_RETROATIVO_DE);
        V_DTATE DATE := TRUNC(SYSDATE+I_DIA_RETROATIVO_ATE);

    BEGIN

        -- CASO O I_MIN_ATUALIZACAO SEJA DEFAULT A VERIFICACAO DE EXECUCAO RETROATIVA EH IGNORADA
        IF I_MIN_ATUALIZACAO != 0 THEN
            VERIFICA_DIAS_RETROATIVOS(I_MIN_ATUALIZACAO,V_DIA_RETROATIVO_DE);
            V_DTDE := TRUNC(SYSDATE+V_DIA_RETROATIVO_DE);

            IF I_MAX_RETROATIVO != 0 AND ABS(V_DIA_RETROATIVO_DE) > I_MAX_RETROATIVO THEN
                RAISE_APPLICATION_ERROR(-20001,'A quantidade de dias processados excede o limite parametrizado');
            END IF; 

        END IF;

        INSERT INTO CUSTOMER.TMPATUALIZACAOROAMING(RID)
        SELECT /*+ PARALLEL(LT,8) */
               LT.ROWID AS RID
          FROM LINHA.LINHATELEFONICA LT
               JOIN APOIO.SISTEMAORIGEM SO USING (IDSISTEMAORIGEM)
         WHERE LT.DTULTIMAALTERACAO >= V_DTDE
           AND LT.DTULTIMAALTERACAO < V_DTATE
           AND SO.CDORIGEM = 'MOVEL'
        UNION
        SELECT /*+ PARALLEL(LT,8) PARALLEL(LB,8) */
               LT.ROWID AS RID
          FROM LINHA.LINHATELEFONICA LT
               JOIN LINHA.LINHABASE LB USING (IDLINHABASE,IDSISTEMAORIGEM)
               JOIN APOIO.SISTEMAORIGEM SO USING (IDSISTEMAORIGEM)
         WHERE LB.DTULTIMAALTERACAO >= V_DTDE
           AND LB.DTULTIMAALTERACAO < V_DTATE
           AND SO.CDORIGEM = 'MOVEL';
    END IDENTIFICA_ATUALIZACOES;

    PROCEDURE GERA_RELATORIO_ATUALIZACOES
    IS
    BEGIN
        INSERT /*+ APPEND */ INTO  CUSTOMER.TMPRELATORIOROAMING (RNUM,REGISTRO)
        SELECT /*+ PARALLEL(LT) PARALLEL(LB) PARALLEL(PL) PARALLEL(PDP) PARALLEL(P) */
            ROWNUM AS RNUM,
            AR.CDAREAREGISTRO || LB .NRLINHA || ';' ||
            TO_CHAR(LT.DTHABILITACAO, 'YYYYMMDD') || ';' ||
            TO_CHAR(LT.DTEXPIRACAO, 'YYYYMMDD') || ';' ||
            TL.IDCLASSIFICACAOTIPOLINHA || ';' ||
            TP.SGTIPOPESSOA AS REGISTRO
        FROM
            LINHA.LINHATELEFONICA LT
            JOIN CUSTOMER.TMPATUALIZACAOROAMING RO ON (RO.RID = LT.ROWID)
            JOIN APOIO.TIPOLINHA TL USING (IDTIPOLINHA)
            JOIN LINHA.LINHABASE LB USING (IDLINHABASE)
            JOIN APOIO.AREAREGISTRO AR USING (IDAREAREGISTRO)
            JOIN CUSTOMER.PESSOALINHA PL USING (IDLINHATELEFONICA)
            JOIN CUSTOMER.PESSOADEPARA PDP USING (IDPESSOADEPARA)
            JOIN CUSTOMER.PESSOA P USING (IDPESSOA)
            JOIN APOIO.TIPOPESSOA TP USING (IDTIPOPESSOA)
        WHERE
            PL.IDTIPORELACIONAMENTO = 2
            AND LT.DTHABILITACAO IS NOT NULL
            AND TP.SGTIPOPESSOA IN ('PF','PJ')
            AND TL.IDCLASSIFICACAOTIPOLINHA IN ('POS','PRE','CTR');
    END GERA_RELATORIO_ATUALIZACOES;

END PKG_RELATORIOROAMING;
/


------------------------------------------------------
-- GRANT PARA O USUARIO DE EXECUCAO
------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CUSTOMER.PKG_RELATORIOROAMING TO BATCHPRO';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CUSTOMER.PKG_RELATORIOROAMING TO BATCHHV';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON CUSTOMER.PKG_RELATORIOROAMING TO BATCHDES';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

