
LOAD DATA 
CHARACTERSET WE8ISO8859P1
INFILE *
INTO TABLE LOAD.CARGAPROTOCOLOTV
APPEND
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
	NAOUSADA FILLER,
	IDPESSOASISTEMAORIGEM	INTEGER EXTERNAL,
	IDSISTEMAORIGEM	INTEGER EXTERNAL,
	IDATENDIMENTOPROTOCOLOMIGRACAO	INTEGER EXTERNAL,
	DTABERTURA	TIMESTAMP,
	DTENCERRAMENTO	TIMESTAMP,
	NMCONTATO	CHAR "TRIM(:NMCONTATO)",
	CDAREAREGISTROORIGEM	INTEGER EXTERNAL,
	NRTELEFONEORIGEM	CHAR
)

