
DROP PROCEDURE LOAD.LOG_CARGAPROTOCOLOSTV;
DROP PROCEDURE LOAD.TRUNC_CARGACLIENTETV;
DROP PROCEDURE LOAD.TRUNC_CARGAPROTOCOLOTV;
DROP PROCEDURE LOAD.TRUNC_CARGAATENDIMENTOTV;

DROP TABLE LOAD.CARGAPROTOCOLOSTVLOG;
DROP TABLE LOAD.CARGACLIENTETV;
DROP TABLE LOAD.CARGAPROTOCOLOTV;
DROP TABLE LOAD.CARGAATENDIMENTOTV;


DELETE FROM APOIO.PARAMETRO WHERE CDPARAMETRO = 'CARGAPROTOCOLOSTV_HORARIO_LIMITE_EXEC';
DELETE FROM ATENDIMENTO.SISTEMORIGEMMIGRACAO WHERE IDSISTEMAORIGEM=98;
DELETE FROM ATENDIMENTO.SISTEMORIGEMMIGRACAO WHERE IDSISTEMAORIGEM=99;
COMMIT;

