
CREATE TABLE LOAD.CARGACLIENTETV (
	IDPESSOASISTEMAORIGEM	NUMBER,
	IDSISTEMAORIGEM	NUMBER,
	NMPESSOA	VARCHAR2(255),
	IDTIPOPESSOA	NUMBER,
	IDSEXO	NUMBER,
	IDDOCUMENTOSISTEMAORIGEM	NUMBER,
	IDTIPODOCUMENTO	NUMBER,
	NRDOCUMENTO	VARCHAR2(255),
	IDCOMUNICACAOSISTEMAORIGEM	VARCHAR2(255),
	EMAIL	VARCHAR2(255),
	IDCOMUMICSISTEMAORIGEMTELEFONE 	VARCHAR2(255),
	TELEFONE	NUMBER,
	NMCONTATO	VARCHAR2(255),
	STATUS 		NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE LOAD.CARGACLIENTETV IS 'Tabela espelho para arquivo de cliente';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDPESSOASISTEMAORIGEM IS 'Identificador único do cliente no sistema de origem.'; 
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDSISTEMAORIGEM IS 'Identificador do sistema de origem a que o dado pertence.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.NMPESSOA IS 'Nome completo do assinante.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDTIPOPESSOA IS 'Código do tipo da PESSOA que se relaciona com a tabela APOIO.TIPOPESSOA, permitindo identificar se a PESSOA é FÍSICA ou JURÍDICA.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDSEXO IS 'Identificador do Sexo da Pessoa Física,  que se relaciona com a tabela APOIO.SEXO, permitindo identificar a descrição do sexo que pertence esta PESSOA,.Ex: Masculino , Feminino.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDDOCUMENTOSISTEMAORIGEM IS 'Identificador do documento no sistema origem.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDTIPODOCUMENTO IS 'Identificador do Tipo de documento do Assinante. ';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.NRDOCUMENTO IS 'Número do documento do Assinante.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDCOMUNICACAOSISTEMAORIGEM IS 'Identificador do dado de comunicação no sistema do que ele é originário.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.EMAIL IS 'E-mail de contato';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.IDCOMUMICSISTEMAORIGEMTELEFONE IS 'Identificador do dado de comunicação no sistema do que ele é originário.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.TELEFONE IS 'Número do telefone de contato';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.NMCONTATO IS 'Nome de pessoa para contato caso o tipo de comunicação seja Telefone de Recado. Uso para pré-pago.';
COMMENT ON COLUMN LOAD.CARGACLIENTETV.STATUS IS 'Status do registro: 0 para pendente de processamento, e 1 para processado';

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGACLIENTETV TO INDRALOG;

CREATE TABLE LOAD.CARGAPROTOCOLOTV (
	IDPESSOASISTEMAORIGEM	NUMBER,
	IDSISTEMAORIGEM	NUMBER,
	IDATENDIMENTOPROTOCOLOMIGRACAO	NUMBER,
	DTABERTURA	TIMESTAMP(6),
	DTENCERRAMENTO	TIMESTAMP(6),
	NMCONTATO	VARCHAR2(1000),
	CDAREAREGISTROORIGEM	NUMBER(2),
	NRTELEFONEORIGEM	VARCHAR2(20),
	STATUS 	NUMBER(1) DEFAULT 0
);


COMMENT ON TABLE LOAD.CARGAPROTOCOLOTV IS 'Tabela espelho para arquivo de protocolo';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.IDPESSOASISTEMAORIGEM IS 'Identificador único do cliente no sistema de origem.';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.IDSISTEMAORIGEM IS 'Identificador do sistema de onde os dados são originários.';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.IDATENDIMENTOPROTOCOLOMIGRACAO IS 'Essa coluna deve identificar o protocolo de atendimento, é unico por atendimento (Chave primária).';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.DTABERTURA IS 'Essa coluna deve conter a data da abertura do protocolo, data de criação.';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.DTENCERRAMENTO IS 'Essa coluna deve conter a data do encerramento do procotolo, ou seja, não existem processos pendente para o mesmo.';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.NMCONTATO IS 'Este campo identifica a pessoa com quem o atendente Vivo está interagindo. Poderá ser persistido diretamente com o nome do Titular da conta  ou com o nome de outra pessoa que esteja interagindo com o atendente';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.CDAREAREGISTROORIGEM IS '"Este campo identifica o DDD do número de telefone que originou a chamada. Poderá conter um número Vivo ou um número não Vivo. 11 - Sao Paulo; 21 - Rio de Janeiro"';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.NRTELEFONEORIGEM IS 'Este campo identifica o número de telefone que originou a chamada. Poderá conter um número Vivo ou um número não Vivo.';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOTV.STATUS IS 'Status do registro: 0 para pendente de processamento, e 1 para processado';

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOTV TO INDRALOG;

CREATE TABLE LOAD.CARGAATENDIMENTOTV (
	IDSISTEMAORIGEM	NUMBER,
	IDATENDIMENTOPROTOCOLOMIGRACAO	NUMBER,
	NMCONTATO	VARCHAR2(1000),
	OBSATENDIMENTO	VARCHAR2(4000),
	NMCLIENTEUSUARIO	VARCHAR2(255),
	NMTIPOCLIENTE	VARCHAR2(255),
	NMCPF_CNPJ	VARCHAR2(50),
	NMEMAILCONTATO	VARCHAR2(500),
	NMTELEFONECONTATO	VARCHAR2(30),
	NMPROCESSO	VARCHAR2(255),
	CDOS	NUMBER,
	IDCANAL	NUMBER,
	STATUS 	NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE LOAD.CARGAATENDIMENTOTV IS 'Tabela espelho para arquivo de atendimento';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.IDSISTEMAORIGEM IS 'Identificador do Assinante no sistema de origem.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.IDATENDIMENTOPROTOCOLOMIGRACAO IS 'Essa coluna deve identificar o protocolo de atendimentom, é unico por atendimento (Chave primária).';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMCONTATO IS 'Nome do usuário de contato que efetuou a abertura do processo que pode ser um cliente vivo ou usuário vivo ou prospect.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.OBSATENDIMENTO IS 'Observação que o atendente do call-center montou sobre o contato inicial com o contato.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMCLIENTEUSUARIO IS 'Nome Cliente ou Usuário ao qual pertence a assinatura que esta com o processo.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMTIPOCLIENTE IS 'Tipo de Cliente';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMCPF_CNPJ IS 'Código do cpf ou cnpj sem mascara.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMEMAILCONTATO IS 'E-Mail do contato que gerou o processo.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMTELEFONECONTATO IS 'Telefone que gerou o contato onde originou a criação do processo.';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.NMPROCESSO IS 'Nome do Processo / Path';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.CDOS IS 'Número da OS';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.IDCANAL IS 'ID do canal de atendimento de abertura do protocolo';
COMMENT ON COLUMN LOAD.CARGAATENDIMENTOTV.STATUS IS 'Status do registro: 0 para pendente de processamento, e 1 para processado';

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAATENDIMENTOTV TO INDRALOG;


CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGACLIENTETV
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGACLIENTETV';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO BATCHPRO;
GRANT EXECUTE ON LOAD.TRUNC_CARGACLIENTETV TO INDRALOG;

CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGAPROTOCOLOTV
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGAPROTOCOLOTV';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO BATCHPRO;
GRANT EXECUTE ON LOAD.TRUNC_CARGAPROTOCOLOTV TO INDRALOG;

CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGAATENDIMENTOTV
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGAATENDIMENTOTV';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO BATCHPRO;
GRANT EXECUTE ON LOAD.TRUNC_CARGAATENDIMENTOTV TO INDRALOG;


CREATE TABLE LOAD.CARGAPROTOCOLOSTVLOG (
	DTLOG 	TIMESTAMP DEFAULT SYSTIMESTAMP,
	MSGLOG 	VARCHAR(1024)
);

COMMENT ON TABLE LOAD.CARGAPROTOCOLOSTVLOG IS 'Tabela de armazenamento dos logs de processamento do batch cargaProtocolosTV';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOSTVLOG.DTLOG IS 'Data da mensagem';
COMMENT ON COLUMN LOAD.CARGAPROTOCOLOSTVLOG.MSGLOG IS 'Conteudo da mensagem';

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAPROTOCOLOSTVLOG TO INDRALOG;


CREATE OR REPLACE PROCEDURE LOAD.LOG_CARGAPROTOCOLOSTV (VI_MSGLOG IN VARCHAR2, VI_PRINTDATE IN BOOLEAN DEFAULT TRUE)
IS
	V_DTLOG TIMESTAMP := SYSTIMESTAMP;
	V_STRLEN NUMBER := LENGTH(VI_MSGLOG);
	V_STRSTEP NUMBER := 255;
	V_STRPOS NUMBER := 1;
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	IF VI_PRINTDATE
	THEN
		DBMS_OUTPUT.PUT(V_DTLOG||' -- ');
	END IF;

	IF V_STRLEN <= V_STRSTEP
	THEN
		DBMS_OUTPUT.PUT_LINE(VI_MSGLOG);
	ELSE
		WHILE (V_STRPOS + V_STRSTEP) <= V_STRLEN
		LOOP
			DBMS_OUTPUT.PUT(SUBSTR(VI_MSGLOG, V_STRPOS, V_STRSTEP));
			V_STRPOS := V_STRPOS + V_STRSTEP;
		END LOOP;
		DBMS_OUTPUT.PUT_LINE(SUBSTR(VI_MSGLOG, V_STRPOS));
	END IF;
	
	INSERT INTO LOAD.CARGAPROTOCOLOSTVLOG (DTLOG, MSGLOG) VALUES (V_DTLOG, VI_MSGLOG);
	COMMIT;
END;
/

GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO LOAD;
GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO BATCHDES;
GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO BATCHHV;
GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO BATCHHC;
GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO BATCHPRO;
GRANT EXECUTE ON LOAD.LOG_CARGAPROTOCOLOSTV TO INDRALOG;


Insert into APOIO.PARAMETRO (IDPARAMETRO,CDPARAMETRO,DSPARAMETRO,DSVALORPARAMETRO,IDUSUARIOALTERACAO,DTULTIMAALTERACAO) values (APOIO.PARAMETROSQ.NEXTVAL,'CARGAPROTOCOLOSTV_HORARIO_LIMITE_EXEC','Define horario limite para execucao do batch cargaProtocolosTV, Mascara: HH24:MI','19:00','125693',SYSDATE);
INSERT INTO ATENDIMENTO.SISTEMORIGEMMIGRACAO (IDSISTEMAORIGEM, NMAREAREGISTRO, DESCRICAOSISTEMA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO) VALUES (98, 'SP', 'SIA', 125693, SYSDATE);
INSERT INTO ATENDIMENTO.SISTEMORIGEMMIGRACAO (IDSISTEMAORIGEM, NMAREAREGISTRO, DESCRICAOSISTEMA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO) VALUES (99, 'SP', 'NSIA', 125693, SYSDATE);
commit;


