SET TERMOUT ON;
SET SQLPROMPT '';
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SET TIMING OFF;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

VARIABLE VO_CDERRO NUMBER
VARIABLE VO_DSERRO VARCHAR2(512)
VARIABLE VO_QUANTIDADE_PARTICOES NUMBER

DECLARE

	V_QUANTIDADE_PARTICOES NUMBER;

BEGIN

	SELECT PARTITION_COUNT 
	  INTO V_QUANTIDADE_PARTICOES
	  FROM ALL_PART_TABLES
     WHERE OWNER = 'LINHA'
       AND TABLE_NAME = 'PLANOSERVLINHAPESSOASUBSEG';
		
	:VO_QUANTIDADE_PARTICOES := V_QUANTIDADE_PARTICOES;	 
	:VO_CDERRO := 0;
    :VO_DSERRO := 'Sucesso';   
	 
EXCEPTION
	WHEN OTHERS THEN
		:VO_CDERRO := 99;
		:VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRIÇÃO DO ERRO: ' || SQLERRM;
END;
/

select CHR(10) from dual;
select 'VO_CDERRO', :VO_CDERRO from dual;
select 'VO_DSERRO', :VO_DSERRO from dual;
select 'VO_QUANTIDADE_PARTICOES', :VO_QUANTIDADE_PARTICOES from dual;

exit 0