LOAD DATA 
REPLACE
INTO TABLE CATALOGOPRS_OW.VIVONETLOCALIDADE_LDR
FIELDS TERMINATED BY ';'
 OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	CDLOCALIDADE,
	NMLOCALIDADE,
	SGUF,
	NMMUNICIPIO,
	CDAREAREGISTRO,
	IDUSUARIOALTERACAO,
	DTULTIMAALTERACAO "to_date(:DTULTIMAALTERACAO,'dd/mm/yyyy hh24:mi:ss')",
	SGLOCALIDADE
)
