LOAD DATA
INFILE *
BADFILE "../error/dadosRejeitados.bad"
APPEND
INTO TABLE CUSTOMER.DADOSAJATOSIA 
FIELDS TERMINATED BY "|"
(
	IDDADOSAJATO    	SEQUENCE(MAX, 1),
    NRDOCUMENTO			"UPPER(TRIM(:nrdocumento))",
    INDACAO				"UPPER(TRIM(:indacao))"
)
