LOAD DATA
INTO TABLE LOAD.CARGABUSERVICOBANDALARGA
REPLACE
FIELDS TERMINATED BY ';' 
TRAILING NULLCOLS
( CDSERVICO,
  NMCOMERCIAL,
  SGTECNOLOGIA,
  NMTECNOLOGIA,
  CDTIPOSERVICO,
  DSTIPOSERVICO,
  NMSISTEMA,
  CDPS,
  CDCLASSESERVICOADICIONAL,
  CDTIPOEQUIPAMENTO,
  INPLANO,
  IDUSUARIOALTERACAO "333",
  DTULTIMAALTERACAO SYSDATE  
)
