/*#########################################################
#  BATCH......: expurgoEndereco
#  Criado por.: Denis Hideki 12/02/2016
#  Funcional..: Loiana Moura
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

BEGIN
	
	DBMS_OUTPUT.PUT_LINE(CHR(10)||'Inicio de processamento de Expurgo: '||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));

	DELETE FROM ADM_PROJECT.ATUALIZA_ENDERECO AE
		WHERE AE.DAT_ATUALIZACAO < ADD_MONTHS(SYSDATE, -1); 

	COMMIT;	

	DBMS_OUTPUT.PUT_LINE(CHR(10)||'Fim de processamento de Expurgo: '||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));

END;
/
SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT