LOAD DATA 
APPEND
INTO TABLE LINHA.LINHAPME
FIELDS TERMINATED BY '|'
 OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CDDOCUMENTO CHAR(14)
   ,NRLINHA INTEGER EXTERNAL(10)
   ,DSPLANO CHAR(60)
   ,NRPONTO INTEGER EXTERNAL(6)
)

