
enum { SUCESSO
     , ERRO_CARGA_CONTATOS
     , ERRO_CARGA_PALITAGEM
     , ERRO_DATA_INICIO
     , ERRO_DATA_FIM
     , ERRO_NIVEL
     , ERRO_REL_NIVEL_0
     , ERRO_ARVORE
     , ERRO_AGRUPAMENTO
     , ERRO_DATA_INVALIDA
     , ERRO_TOTAL
     , ERRO_CHAVE_INVALIDA
     , ERRO_FALTA_SG_UF
     , ERRO_INIT_DATA
     , ERRO_FALTA_CONTATO
     , ERRO_INDEFINIDO
    };

