/***********************************************************
  BATCH......: relressarcimprocedente
  Criado por.: Eder Jani Martins (08/05/2015)
  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
    V_ROWCOUNT NUMBER;
	V_90DIAS   DATE DEFAULT SYSDATE-90;

BEGIN
	DBMS_OUTPUT.PUT_LINE('Data considerada para apagar os registros: '||TO_CHAR(V_90DIAS, 'DD/MM/YYYY HH24:MI:SS'));

	-- Apaga a tabela filho: ATENDIMENTO.RESSARCIMENTOBILLING
	DELETE FROM ATENDIMENTO.RESSARCIMENTOBILLING RB
	WHERE EXISTS 
	( 
		SELECT 1 
		  FROM ATENDIMENTO.PEDIDORESSARCIMENTO PR 
		 WHERE PR.IDPEDIDORESSARCIMENTO = RB.IDPEDIDORESSARCIMENTO
		   AND PR.DTULTIMAALTERACAO < SYSDATE-90
	);
    V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas apagadas em ATENDIMENTO.RESSARCIMENTOBILLING: '||V_ROWCOUNT);

	-- Apaga a tabela pai: ATENDIMENTO.PEDIDORESSARCIMENTO
	DELETE FROM ATENDIMENTO.PEDIDORESSARCIMENTO PR
	WHERE PR.DTULTIMAALTERACAO < SYSDATE-90;

    V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas apagadas em ATENDIMENTO.PEDIDORESSARCIMENTO: '||V_ROWCOUNT);
	COMMIT;
END;
/

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
