/*#########################################################
#  BATCH......: cargaDadosCorreiosSRE
#  Criado por.: Denis Hideki 04/03/2016
#  Funcional..: Loiana Moura
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT


DECLARE

	BEGIN
		DBMS_OUTPUT.ENABLE (buffer_size => NULL);

		DBMS_OUTPUT.PUT_LINE(CHR(10)||'INICIO PKG_CARGADADOSCORREIOS ' ||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));
	   
	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGACENTRODISTRIBUICAO');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGACENTRODISTRIBUICAO;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGALOCALIDADE');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGALOCALIDADE;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGABAIRRO');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGABAIRRO;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGATIPOLOGRADOURO');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGATIPOLOGRADOURO;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGATITULOLOGRADOURO');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGATITULOLOGRADOURO;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGALOGRADOUROS');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGALOGRADOUROS;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGAGRANDESUSUARIOS');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGAGRANDESUSUARIOS;

	   	DBMS_OUTPUT.PUT_LINE('PRC_CARGACXPOSTCOMUNITARIA');
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_CARGACXPOSTCOMUNITARIA;

		DBMS_OUTPUT.PUT_LINE(CHR(10)||'FIM PKG_CARGADADOSCORREIOS ' ||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));
	END;
/
SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT