OPTIONS (SKIP=1)
LOAD DATA
APPEND
INTO TABLE ADM_PROJECT.TEMP_TITULO_LOGRAD_DNE
TRAILING NULLCOLS
(
	ID_TITULO_LOGRADOURO 				POSITION(2:4) 	NULLIF ID_TITULO_LOGRADOURO=BLANKS,
	DNE_ID_TITULO_LOGRADOURO 			POSITION(5:8) 	NULLIF DNE_ID_TITULO_LOGRADOURO=BLANKS,
	NOME_TITULO_LOGRADOURO 				POSITION(9:73) 	"TRIM(:NOME_TITULO_LOGRADOURO)",
	ABREVIATURA_TITULO_LOGRADOURO 		POSITION(81:96)	"TRIM(:ABREVIATURA_TITULO_LOGRADOURO)"
)