OPTIONS (SKIP=1)
LOAD DATA
APPEND
INTO TABLE ADM_PROJECT.TEMP_TIPO_LOGRAD_DNE
TRAILING NULLCOLS
(
	ID_TIPO_LOGRADOURO 				POSITION(2:4) 	NULLIF ID_TIPO_LOGRADOURO=BLANKS,
	DNE_ID_TIPO_LOGRADOURO 			POSITION(5:7)	NULLIF DNE_ID_TIPO_LOGRADOURO=BLANKS,
	NOME_TIPO_LOGRADOURO 			POSITION(8:73)	"TRIM(:NOME_TIPO_LOGRADOURO)",
	ABREVIATURA_TIPO_LOGRADOURO		POSITION(80:96)	"TRIM(:ABREVIATURA_TIPO_LOGRADOURO)"
)