/*#########################################################
#  BATCH......: cargaDadosCorreiosSRE
#  Criado por.: Denis Hideki 04/03/2016
#  Funcional..: Loiana Moura
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT


DECLARE

	BEGIN
		DBMS_OUTPUT.ENABLE (buffer_size => NULL);

		DBMS_OUTPUT.PUT_LINE(CHR(10)||'INICIO PRC_TRUNCTEMPCARGA ' ||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));
	   
	   	ADM_PROJECT.PKG_CARGADADOSCORREIOS.PRC_TRUNCTEMPCARGA;

		DBMS_OUTPUT.PUT_LINE(CHR(10)||'FIM PRC_TRUNCTEMPCARGA ' ||TO_CHAR(SYSDATE,'DD/MM/RRRR HH24:MI:SS'));
	END;
/
SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT