LOAD DATA
APPEND
INTO TABLE LOAD.PLANOSERVICOLINHA_TMP 
FIELDS TERMINATED BY ";"
TRAILING NULLCOLS
(
   IDSERVICO ,
   IDLINHASISTEMAORIGEM "LTRIM(:IDLINHASISTEMAORIGEM,'0')" ,
   IDSERVLINHASISTORIGEM "LTRIM(:IDSERVLINHASISTORIGEM,'0')" ,
   CODIGOPRODATIS ,
   DTBAIXA   "to_date(:DTBAIXA, 'rrrrmmdd')" 
)
