/**
 * ServicoPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoServico.sn;

public interface ServicoPortType extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoParametrizacaoResponse buscarListaServicoParametrizacao(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoParametrizacaoRequest buscarListaServicoParametrizacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarServicoParametrizacaoResponse alterarServicoParametrizacao(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarServicoParametrizacaoRequest alterarServicoParametrizacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarCategoriaListaServicoResponse alterarCategoriaListaServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarCategoriaListaServicoRequest alterarCategoriaListaServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaQtdeMaxAtivacaoResponse buscarListaQtdeMaxAtivacao(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaQtdeMaxAtivacaoRequest buscarListaQtdeMaxAtivacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoPendValidacaoResponse buscarListaServicoPendValidacao(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoPendValidacaoRequest buscarListaServicoPendValidacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.ExportarServicoResponse exportarServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.ExportarServicoRequest exportarServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.ValidarListaServicoPorIdResponse validarListaServicoPorId(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.ValidarListaServicoPorIdRequest validarListaServicoPorIdRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoResponse buscarListaServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoRequest buscarListaServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoTarifaPorIdServicoResponse buscarListaServicoTarifaPorIdServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoTarifaPorIdServicoRequest buscarListaServicoTarifaPorIdServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaRestricoesPorServicoResponse buscarListaRestricoesPorServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaRestricoesPorServicoRequest buscarListaRestricoesPorServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaAtributoPorIdServicoResponse buscarListaAtributoPorIdServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaAtributoPorIdServicoRequest buscarListaAtributoPorIdServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarDetalhesServicoPorIdPlanoResponse buscarDetalhesServicoPorIdPlano(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarDetalhesServicoPorIdPlanoRequest buscarDetalhesServicoPorIdPlanoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarDetalhesServicoResponse buscarDetalhesServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarDetalhesServicoRequest buscarDetalhesServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaTipoServicoResponse buscarListaTipoServico(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaTipoServicoRequest buscarListaTipoServicoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoPorSvTypeCodeResponse buscarListaServicoPorSvTypeCode(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoPorSvTypeCodeRequest buscarListaServicoPorSvTypeCodeRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoParametrizacaoSemPagResponse buscarListaServicoParametrizacaoSemPag(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.BuscarListaServicoParametrizacaoSemPagRequest buscarListaServicoParametrizacaoSemPagRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarAtivacaoWiFiResponse alterarAtivacaoWiFi(br.com.vivo.catalogoPRS.ws.catalogoServico.sn.AlterarAtivacaoWiFiRequest alterarAtivacaoWiFiRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoServico.mc.geral.ErroInfo;
}
