OPTIONS (SKIP=1, ROWS=100, ERRORS=9999)
LOAD DATA
	INTO TABLE CUSTOMER.BLACKLISTCREDITO
	FIELDS TERMINATED BY "|" TRAILING NULLCOLS
	(TIPODOCUMENTO, NRDOCUMENTO, PRODUTO, IDMENSAGEM, DTATUALIZACAO "sysdate")
