/***********************************************************
  BATCH......: RELRESSARCIMENTO
  Criado por.: Eder Jani Martins (04/05/2015)
  Funcional..: Erika Brum
***********************************************************/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
	V_LINHA	VARCHAR2(2000);

	CURSOR CURSOR_APEDIDO IS 
	SELECT IDPEDIDORESSARCIMENTO 
		   ||'|'|| CDAREAREGISTRO||NRLINHA 
		   ||'|'|| TO_CHAR( DTINICIOINTERRUPCAO, 'DD/MM/YYYY HH24:MI:SS') 
		   ||'|'|| TO_CHAR( DTFIMINTERRUPCAO   , 'DD/MM/YYYY HH24:MI:SS') 
		   ||'|'|| SGUF 
		   ||'|'|| NMMUNICIPIO 
		   ||'|'|| DSTIPORESSARCIMENTO 
		   ||'|'|| DSTIPOREDE 
		   ||'|'|| TO_CHAR(DTULTIMAALTERACAO, 'DD/MM/YYYY HH24:MI:SS') AS LINHA
	  FROM ATENDIMENTO.PEDIDORESSARCIMENTO
	 WHERE UPPER(DSSTATUSRESSARCIMENTO) = 'EM ANÁLISE';

BEGIN
	DBMS_OUTPUT.ENABLE (buffer_size => NULL);
	OPEN CURSOR_APEDIDO;
	LOOP
		FETCH CURSOR_APEDIDO INTO V_LINHA;
		EXIT WHEN CURSOR_APEDIDO%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(V_LINHA);		
	END LOOP;
	CLOSE CURSOR_APEDIDO;
END;
/

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
