//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.02 at 04:06:14 PM BRT 
//


package br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.entrada;


/**
 * Java content class for ValidaSenhaVOType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/autenticacao/tuxgateway/entrada/validaSenhaIN.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="ValidaSenhaVOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idCanal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdSenha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdDDD" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdNumTelefone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="validarSenhaService" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ValidaSenhaVOType {


    /**
     * Gets the value of the validarSenhaService property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getValidarSenhaService();

    /**
     * Sets the value of the validarSenhaService property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setValidarSenhaService(java.lang.String value);

    /**
     * Gets the value of the telefone property.
     * 
     */
    int getTelefone();

    /**
     * Sets the value of the telefone property.
     * 
     */
    void setTelefone(int value);

    /**
     * Gets the value of the idCanal property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdCanal();

    /**
     * Sets the value of the idCanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdCanal(java.lang.String value);

    /**
     * Gets the value of the idTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdTerminal();

    /**
     * Sets the value of the idTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdTerminal(java.lang.String value);

    /**
     * Gets the value of the cdNumTelefone property.
     * 
     */
    int getCdNumTelefone();

    /**
     * Sets the value of the cdNumTelefone property.
     * 
     */
    void setCdNumTelefone(int value);

    /**
     * Gets the value of the cdSenha property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCdSenha();

    /**
     * Sets the value of the cdSenha property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCdSenha(java.lang.String value);

    /**
     * Gets the value of the cdDDD property.
     * 
     */
    int getCdDDD();

    /**
     * Sets the value of the cdDDD property.
     * 
     */
    void setCdDDD(int value);

}
