//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 03:54:49 PM BRST 
//


package br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl;

public class UsuarioVOTypeImpl implements br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.UsuarioVOType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _DsSiteConsultorAtdAtual;
    protected java.lang.String _DtRetorno;
    protected java.lang.String _IdUF;
    protected java.lang.String _DsPerfilConsultorAtdAtual;
    protected java.lang.String _DescricaoCargoAtual;
    protected java.lang.String _IdUsuario;
    protected java.lang.String _DsMotivo;
    protected java.lang.String _InConsultor;
    protected java.lang.String _IdCargoAtual;
    protected com.sun.xml.bind.util.ListImpl _DocumentoSimpVO;
    protected java.lang.String _Sobrenome;
    protected java.lang.String _LoginChefe;
    protected java.lang.String _NomeMeio;
    protected java.lang.String _LoginCti;
    protected java.lang.String _IdFornecedorConsultorAtdAtual;
    protected java.lang.String _IdStatusAtual;
    protected java.lang.String _NomeChefe;
    protected java.lang.String _DtInicio;
    protected java.lang.String _RegistrosPPagina;
    protected java.lang.String _NmUF;
    protected java.lang.String _DsFornecedorConsultorAtdAtual;
    protected java.lang.String _DescricaoStatusAtual;
    protected com.sun.xml.bind.util.ListImpl _UFOperadoraPessoaVO;
    protected java.lang.String _IdPerfilConsultorAtdAtual;
    protected java.lang.String _DtExclusao;
    protected java.lang.String _DsTelefone;
    protected java.lang.String _IdMotivo;
    protected java.lang.String _Login;
    protected java.lang.String _IdSiteConsultorAtdAtual;
    protected java.lang.String _Nome;
    protected java.lang.String _DtInclusao;
    protected java.lang.String _IdDDD;
    protected java.lang.String _Email;
    protected java.lang.String _DsLoginRoteamento;
    protected java.lang.String _PaginaAtual;
    protected java.lang.String _DsDDD;
    public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.UsuarioVOType.class);
    }

    public java.lang.String getDsSiteConsultorAtdAtual() {
        return _DsSiteConsultorAtdAtual;
    }

    public void setDsSiteConsultorAtdAtual(java.lang.String value) {
        _DsSiteConsultorAtdAtual = value;
    }

    public java.lang.String getDtRetorno() {
        return _DtRetorno;
    }

    public void setDtRetorno(java.lang.String value) {
        _DtRetorno = value;
    }

    public java.lang.String getIdUF() {
        return _IdUF;
    }

    public void setIdUF(java.lang.String value) {
        _IdUF = value;
    }

    public java.lang.String getDsPerfilConsultorAtdAtual() {
        return _DsPerfilConsultorAtdAtual;
    }

    public void setDsPerfilConsultorAtdAtual(java.lang.String value) {
        _DsPerfilConsultorAtdAtual = value;
    }

    public java.lang.String getDescricaoCargoAtual() {
        return _DescricaoCargoAtual;
    }

    public void setDescricaoCargoAtual(java.lang.String value) {
        _DescricaoCargoAtual = value;
    }

    public java.lang.String getIdUsuario() {
        return _IdUsuario;
    }

    public void setIdUsuario(java.lang.String value) {
        _IdUsuario = value;
    }

    public java.lang.String getDsMotivo() {
        return _DsMotivo;
    }

    public void setDsMotivo(java.lang.String value) {
        _DsMotivo = value;
    }

    public java.lang.String getInConsultor() {
        return _InConsultor;
    }

    public void setInConsultor(java.lang.String value) {
        _InConsultor = value;
    }

    public java.lang.String getIdCargoAtual() {
        return _IdCargoAtual;
    }

    public void setIdCargoAtual(java.lang.String value) {
        _IdCargoAtual = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getDocumentoSimpVO() {
        if (_DocumentoSimpVO == null) {
            _DocumentoSimpVO = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _DocumentoSimpVO;
    }

    public java.util.List getDocumentoSimpVO() {
        return _getDocumentoSimpVO();
    }

    public java.lang.String getSobrenome() {
        return _Sobrenome;
    }

    public void setSobrenome(java.lang.String value) {
        _Sobrenome = value;
    }

    public java.lang.String getLoginChefe() {
        return _LoginChefe;
    }

    public void setLoginChefe(java.lang.String value) {
        _LoginChefe = value;
    }

    public java.lang.String getNomeMeio() {
        return _NomeMeio;
    }

    public void setNomeMeio(java.lang.String value) {
        _NomeMeio = value;
    }

    public java.lang.String getLoginCti() {
        return _LoginCti;
    }

    public void setLoginCti(java.lang.String value) {
        _LoginCti = value;
    }

    public java.lang.String getIdFornecedorConsultorAtdAtual() {
        return _IdFornecedorConsultorAtdAtual;
    }

    public void setIdFornecedorConsultorAtdAtual(java.lang.String value) {
        _IdFornecedorConsultorAtdAtual = value;
    }

    public java.lang.String getIdStatusAtual() {
        return _IdStatusAtual;
    }

    public void setIdStatusAtual(java.lang.String value) {
        _IdStatusAtual = value;
    }

    public java.lang.String getNomeChefe() {
        return _NomeChefe;
    }

    public void setNomeChefe(java.lang.String value) {
        _NomeChefe = value;
    }

    public java.lang.String getDtInicio() {
        return _DtInicio;
    }

    public void setDtInicio(java.lang.String value) {
        _DtInicio = value;
    }

    public java.lang.String getRegistrosPPagina() {
        return _RegistrosPPagina;
    }

    public void setRegistrosPPagina(java.lang.String value) {
        _RegistrosPPagina = value;
    }

    public java.lang.String getNmUF() {
        return _NmUF;
    }

    public void setNmUF(java.lang.String value) {
        _NmUF = value;
    }

    public java.lang.String getDsFornecedorConsultorAtdAtual() {
        return _DsFornecedorConsultorAtdAtual;
    }

    public void setDsFornecedorConsultorAtdAtual(java.lang.String value) {
        _DsFornecedorConsultorAtdAtual = value;
    }

    public java.lang.String getDescricaoStatusAtual() {
        return _DescricaoStatusAtual;
    }

    public void setDescricaoStatusAtual(java.lang.String value) {
        _DescricaoStatusAtual = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getUFOperadoraPessoaVO() {
        if (_UFOperadoraPessoaVO == null) {
            _UFOperadoraPessoaVO = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _UFOperadoraPessoaVO;
    }

    public java.util.List getUFOperadoraPessoaVO() {
        return _getUFOperadoraPessoaVO();
    }

    public java.lang.String getIdPerfilConsultorAtdAtual() {
        return _IdPerfilConsultorAtdAtual;
    }

    public void setIdPerfilConsultorAtdAtual(java.lang.String value) {
        _IdPerfilConsultorAtdAtual = value;
    }

    public java.lang.String getDtExclusao() {
        return _DtExclusao;
    }

    public void setDtExclusao(java.lang.String value) {
        _DtExclusao = value;
    }

    public java.lang.String getDsTelefone() {
        return _DsTelefone;
    }

    public void setDsTelefone(java.lang.String value) {
        _DsTelefone = value;
    }

    public java.lang.String getIdMotivo() {
        return _IdMotivo;
    }

    public void setIdMotivo(java.lang.String value) {
        _IdMotivo = value;
    }

    public java.lang.String getLogin() {
        return _Login;
    }

    public void setLogin(java.lang.String value) {
        _Login = value;
    }

    public java.lang.String getIdSiteConsultorAtdAtual() {
        return _IdSiteConsultorAtdAtual;
    }

    public void setIdSiteConsultorAtdAtual(java.lang.String value) {
        _IdSiteConsultorAtdAtual = value;
    }

    public java.lang.String getNome() {
        return _Nome;
    }

    public void setNome(java.lang.String value) {
        _Nome = value;
    }

    public java.lang.String getDtInclusao() {
        return _DtInclusao;
    }

    public void setDtInclusao(java.lang.String value) {
        _DtInclusao = value;
    }

    public java.lang.String getIdDDD() {
        return _IdDDD;
    }

    public void setIdDDD(java.lang.String value) {
        _IdDDD = value;
    }

    public java.lang.String getEmail() {
        return _Email;
    }

    public void setEmail(java.lang.String value) {
        _Email = value;
    }

    public java.lang.String getDsLoginRoteamento() {
        return _DsLoginRoteamento;
    }

    public void setDsLoginRoteamento(java.lang.String value) {
        _DsLoginRoteamento = value;
    }

    public java.lang.String getPaginaAtual() {
        return _PaginaAtual;
    }

    public void setPaginaAtual(java.lang.String value) {
        _PaginaAtual = value;
    }

    public java.lang.String getDsDDD() {
        return _DsDDD;
    }

    public void setDsDDD(java.lang.String value) {
        _DsDDD = value;
    }

    public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
        return new br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.UsuarioVOTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx10 = 0;
        final int len10 = ((_DocumentoSimpVO == null)? 0 :_DocumentoSimpVO.size());
        int idx23 = 0;
        final int len23 = ((_UFOperadoraPessoaVO == null)? 0 :_UFOperadoraPessoaVO.size());
        while (idx10 != len10) {
            context.startElement("", "DocumentoSimpVO");
            int idx_0 = idx10;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _DocumentoSimpVO.get(idx_0 ++)), "DocumentoSimpVO");
            context.endNamespaceDecls();
            int idx_1 = idx10;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _DocumentoSimpVO.get(idx_1 ++)), "DocumentoSimpVO");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _DocumentoSimpVO.get(idx10 ++)), "DocumentoSimpVO");
            context.endElement();
        }
        while (idx23 != len23) {
            context.startElement("", "UFOperadoraPessoaVO");
            int idx_2 = idx23;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _UFOperadoraPessoaVO.get(idx_2 ++)), "UFOperadoraPessoaVO");
            context.endNamespaceDecls();
            int idx_3 = idx23;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _UFOperadoraPessoaVO.get(idx_3 ++)), "UFOperadoraPessoaVO");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _UFOperadoraPessoaVO.get(idx23 ++)), "UFOperadoraPessoaVO");
            context.endElement();
        }
        context.startElement("", "idUsuario");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdUsuario), "IdUsuario");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "nome");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Nome), "Nome");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_NomeMeio!= null) {
            context.startElement("", "nomeMeio");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NomeMeio), "NomeMeio");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "sobrenome");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Sobrenome), "Sobrenome");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "email");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Email), "Email");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idDDD");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdDDD), "IdDDD");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsDDD");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsDDD), "DsDDD");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsTelefone");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsTelefone), "DsTelefone");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "login");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Login), "Login");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "loginCti");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _LoginCti), "LoginCti");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idStatusAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdStatusAtual), "IdStatusAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idPerfilConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdPerfilConsultorAtdAtual), "IdPerfilConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsPerfilConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsPerfilConsultorAtdAtual), "DsPerfilConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idFornecedorConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdFornecedorConsultorAtdAtual), "IdFornecedorConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsFornecedorConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsFornecedorConsultorAtdAtual), "DsFornecedorConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idSiteConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdSiteConsultorAtdAtual), "IdSiteConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsSiteConsultorAtdAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsSiteConsultorAtdAtual), "DsSiteConsultorAtdAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsLoginRoteamento");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsLoginRoteamento), "DsLoginRoteamento");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "descricaoStatusAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DescricaoStatusAtual), "DescricaoStatusAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idMotivo");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdMotivo), "IdMotivo");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dsMotivo");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DsMotivo), "DsMotivo");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dtInicio");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DtInicio), "DtInicio");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dtRetorno");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DtRetorno), "DtRetorno");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idCargoAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdCargoAtual), "IdCargoAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "descricaoCargoAtual");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DescricaoCargoAtual), "DescricaoCargoAtual");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "loginChefe");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _LoginChefe), "LoginChefe");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "nomeChefe");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _NomeChefe), "NomeChefe");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dtInclusao");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DtInclusao), "DtInclusao");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "dtExclusao");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _DtExclusao), "DtExclusao");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "idUF");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _IdUF), "IdUF");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "nmUF");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _NmUF), "NmUF");
        } catch (java.lang.Exception e) {
            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_InConsultor!= null) {
            context.startElement("", "inConsultor");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _InConsultor), "InConsultor");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PaginaAtual!= null) {
            context.startElement("", "paginaAtual");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PaginaAtual), "PaginaAtual");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_RegistrosPPagina!= null) {
            context.startElement("", "registrosPPagina");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _RegistrosPPagina), "RegistrosPPagina");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx10 = 0;
        final int len10 = ((_DocumentoSimpVO == null)? 0 :_DocumentoSimpVO.size());
        int idx23 = 0;
        final int len23 = ((_UFOperadoraPessoaVO == null)? 0 :_UFOperadoraPessoaVO.size());
        while (idx10 != len10) {
            idx10 += 1;
        }
        while (idx23 != len23) {
            idx23 += 1;
        }
    }

    public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx10 = 0;
        final int len10 = ((_DocumentoSimpVO == null)? 0 :_DocumentoSimpVO.size());
        int idx23 = 0;
        final int len23 = ((_UFOperadoraPessoaVO == null)? 0 :_UFOperadoraPessoaVO.size());
        while (idx10 != len10) {
            idx10 += 1;
        }
        while (idx23 != len23) {
            idx23 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.UsuarioVOType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000 com."
+"sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.gramm"
+"ar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003ppsr\u0000\'com.sun.msv.gra"
+"mmar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/m"
+"sv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000"
+"\u0003pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000+pp\u0000sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsq\u0000~\u0000(sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuex"
+"p\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000"
+"\u0002L\u0000\tnameClassq\u0000~\u0000,xq\u0000~\u0000\u0003q\u0000~\u00005psr\u00002com.sun.msv.grammar.Expres"
+"sion$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u00004\u0001psr\u0000 com.sun"
+".msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar."
+"NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$Eps"
+"ilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000:psr\u0000#com.sun.msv.grammar"
+".SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;"
+"L\u0000\fnamespaceURIq\u0000~\u0000Axq\u0000~\u0000<t\u0000wbr.com.indrasistemas.vivoservic"
+"es.administracaosistema.usuario.manter.tuxgateway.entrada.us"
+"rinserir.DocumentoSimpVOTypet\u0000+http://java.sun.com/jaxb/xjc/"
+"dummy-elementssq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005psr\u0000\u001bcom.sun.msv.grammar.Da"
+"taExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006ex"
+"ceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\""
+"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv"
+".datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.da"
+"tatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.x"
+"sd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000AL\u0000\btypeNameq"
+"\u0000~\u0000AL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProc"
+"essor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.s"
+"un.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp"
+"sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tloca"
+"lNameq\u0000~\u0000AL\u0000\fnamespaceURIq\u0000~\u0000Axpq\u0000~\u0000Rq\u0000~\u0000Qsq\u0000~\u0000@t\u0000\u0004typet\u0000)ht"
+"tp://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u000fDocumen"
+"toSimpVOt\u0000\u0000sq\u0000~\u00001ppsq\u0000~\u0000(q\u0000~\u00005psq\u0000~\u0000+q\u0000~\u00005p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000+pp"
+"\u0000sq\u0000~\u00001ppsq\u0000~\u0000(q\u0000~\u00005psq\u0000~\u00006q\u0000~\u00005pq\u0000~\u00009q\u0000~\u0000=q\u0000~\u0000?sq\u0000~\u0000@t\u0000{br."
+"com.indrasistemas.vivoservices.administracaosistema.usuario."
+"manter.tuxgateway.entrada.usrinserir.UFOperadoraPessoaVOType"
+"q\u0000~\u0000Dsq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0013UFOperadora"
+"PessoaVOq\u0000~\u0000_q\u0000~\u0000?sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000Gppsr\u0000#com.sun.msv.d"
+"atatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000Lq\u0000~\u0000Q"
+"t\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Pr"
+"eserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000T\u0001q\u0000~\u0000Wsq\u0000~\u0000Xq\u0000~\u0000sq\u0000~\u0000Qsq\u0000~\u00001ppsq\u0000~\u00006q"
+"\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\tidUsuarioq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000pp"
+"q\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0004nomeq\u0000~\u0000_sq"
+"\u0000~\u00001ppsq\u0000~\u0000+q\u0000~\u00005p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~"
+"\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\bnomeMeioq\u0000~\u0000_q\u0000~\u0000?sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~"
+"\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\tsobrenomeq\u0000~\u0000_sq\u0000~\u0000+"
+"pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0005"
+"emailq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~"
+"\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0005idDDDq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~"
+"\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0005dsDDDq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq"
+"\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\ndsTelefoneq\u0000"
+"~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?"
+"sq\u0000~\u0000@t\u0000\u0005loginq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005"
+"pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\bloginCtiq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000p"
+"sq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\ridStatusAtualq\u0000~"
+"\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?s"
+"q\u0000~\u0000@t\u0000\u0019idPerfilConsultorAtdAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000p"
+"sq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0019dsPerfilConsulto"
+"rAtdAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000"
+"Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u001didFornecedorConsultorAtdAtualq\u0000~\u0000_sq\u0000~\u0000+"
+"pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u001d"
+"dsFornecedorConsultorAtdAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~"
+"\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0017idSiteConsultorAtdAt"
+"ualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Z"
+"q\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0017dsSiteConsultorAtdAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq"
+"\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0011dsLoginRotea"
+"mentoq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~"
+"\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0014descricaoStatusAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000"
+"~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\bidMotivoq\u0000~\u0000_"
+"sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000"
+"~\u0000@t\u0000\bdsMotivoq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005"
+"pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\bdtInicioq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000p"
+"sq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\tdtRetornoq\u0000~\u0000_sq"
+"\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000"
+"@t\u0000\fidCargoAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~"
+"\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0013descricaoCargoAtualq\u0000~\u0000_sq\u0000~\u0000+pp\u0000"
+"sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\nlog"
+"inChefeq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq"
+"\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\tnomeChefeq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001"
+"ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\ndtInclusaoq\u0000~\u0000_sq\u0000~\u0000+p"
+"p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\nd"
+"tExclusaoq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000"
+"Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0004idUFq\u0000~\u0000_sq\u0000~\u0000+pp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001pps"
+"q\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0004nmUFq\u0000~\u0000_sq\u0000~\u00001ppsq\u0000~\u0000+q\u0000"
+"~\u00005p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t"
+"\u0000\u000binConsultorq\u0000~\u0000_q\u0000~\u0000?sq\u0000~\u00001ppsq\u0000~\u0000+q\u0000~\u00005p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000"
+"~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u000bpaginaAtualq\u0000~\u0000_q\u0000~"
+"\u0000?sq\u0000~\u00001ppsq\u0000~\u0000+q\u0000~\u00005p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000psq\u0000~\u00001ppsq\u0000~\u00006q\u0000~\u00005pq\u0000~\u0000"
+"Jq\u0000~\u0000Zq\u0000~\u0000?sq\u0000~\u0000@t\u0000\u0010registrosPPaginaq\u0000~\u0000_q\u0000~\u0000?sr\u0000\"com.sun.ms"
+"v.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/ms"
+"v/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.gramma"
+"r.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersi"
+"onL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000v\u0001pq\u0000"
+"~\u0000\u0013q\u0000~\u0000%q\u0000~\u0000*q\u0000~\u0000aq\u0000~\u0000\'q\u0000~\u0000\u0015q\u0000~\u0000\u001dq\u0000~\u0001:q\u0000~\u00013q\u0000~\u0001,q\u0000~\u0001&q\u0000~\u0001 q\u0000"
+"~\u0001\u001aq\u0000~\u0001\u0014q\u0000~\u0001\u000eq\u0000~\u0001\bq\u0000~\u0001\u0002q\u0000~\u0000\u00fcq\u0000~\u0000\u00f6q\u0000~\u0000\u00f0q\u0000~\u0000\u00eaq\u0000~\u0000\u00e4q\u0000~\u0000\u00deq\u0000~\u0000\u00d8q\u0000"
+"~\u0000\u00d2q\u0000~\u0000Eq\u0000~\u0000jq\u0000~\u0000wq\u0000~\u0000}q\u0000~\u0000\u0084q\u0000~\u0000\u008aq\u0000~\u0000\u0090q\u0000~\u0000\u0096q\u0000~\u0000\u009cq\u0000~\u0000\u00a2q\u0000~\u0000\u00a8q\u0000"
+"~\u0000\u00aeq\u0000~\u0000\u00b4q\u0000~\u0000\u00baq\u0000~\u0000\u00c0q\u0000~\u0000\u00c6q\u0000~\u0000\u00ccq\u0000~\u0000\rq\u0000~\u0000\u0007q\u0000~\u0001Aq\u0000~\u0000&q\u0000~\u0000\fq\u0000~\u00003q\u0000"
+"~\u0000fq\u0000~\u0000\u001fq\u0000~\u0000\u001eq\u0000~\u00019q\u0000~\u00012q\u0000~\u0001+q\u0000~\u0001%q\u0000~\u0001\u001fq\u0000~\u0001\u0019q\u0000~\u0001\u0013q\u0000~\u0001\rq\u0000~\u0001\u0007q\u0000"
+"~\u0001\u0001q\u0000~\u0000\u00fbq\u0000~\u0000\u00f5q\u0000~\u0000\u00efq\u0000~\u0000\u00e9q\u0000~\u0000\u00e3q\u0000~\u0000\u00ddq\u0000~\u0000\u00d7q\u0000~\u0000\u00d1q\u0000~\u0000oq\u0000~\u0000|q\u0000~\u0000\u0083q\u0000"
+"~\u0000\u0089q\u0000~\u0000\u008fq\u0000~\u0000\u0095q\u0000~\u0000\u009bq\u0000~\u0000\u00a1q\u0000~\u0000\u00a7q\u0000~\u0000\u00adq\u0000~\u0000\u00b3q\u0000~\u0000\u00b9q\u0000~\u0000\u00bfq\u0000~\u0000\u00c5q\u0000~\u0000\u00cbq\u0000"
+"~\u0000\u0010q\u0000~\u0000!q\u0000~\u0000\tq\u0000~\u0001@q\u0000~\u0000\u0005q\u0000~\u0000\u0017q\u0000~\u0000\u001aq\u0000~\u0000\u0019q\u0000~\u0000\u000eq\u0000~\u0000\u000fq\u0000~\u0000\u0018q\u0000~\u00002q\u0000"
+"~\u0000eq\u0000~\u0000\u0014q\u0000~\u0000$q\u0000~\u0000\u0016q\u0000~\u00017q\u0000~\u00010q\u0000~\u0000\u0081q\u0000~\u0001>q\u0000~\u0000\nq\u0000~\u0000\u0006q\u0000~\u0000\u000bq\u0000~\u0000\u0012q\u0000"
+"~\u0000\u0011q\u0000~\u0000\u001bq\u0000~\u0000 q\u0000~\u0000`q\u0000~\u0000#q\u0000~\u0000/q\u0000~\u0000cq\u0000~\u0000\"q\u0000~\u0000\u001cq\u0000~\u0000\bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------------------------------------------------------------------------------------------------");
        }

        protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.UsuarioVOTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  78 :
                        if (("descricaoCargoAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 79;
                            return ;
                        }
                        break;
                    case  39 :
                        if (("idPerfilConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 40;
                            return ;
                        }
                        break;
                    case  93 :
                        if (("idUF" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 94;
                            return ;
                        }
                        break;
                    case  96 :
                        if (("nmUF" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 97;
                            return ;
                        }
                        break;
                    case  105 :
                        if (("registrosPPagina" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 106;
                            return ;
                        }
                        state = 108;
                        continue outer;
                    case  42 :
                        if (("dsPerfilConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 43;
                            return ;
                        }
                        break;
                    case  90 :
                        if (("dtExclusao" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 91;
                            return ;
                        }
                        break;
                    case  27 :
                        if (("dsTelefone" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 28;
                            return ;
                        }
                        break;
                    case  84 :
                        if (("nomeChefe" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 85;
                            return ;
                        }
                        break;
                    case  69 :
                        if (("dtInicio" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 70;
                            return ;
                        }
                        break;
                    case  51 :
                        if (("idSiteConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 52;
                            return ;
                        }
                        break;
                    case  33 :
                        if (("loginCti" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 34;
                            return ;
                        }
                        break;
                    case  1 :
                        if (("fromWS" == ___local)&&("" == ___uri)) {
                            _getDocumentoSimpVO().add(((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.DocumentoSimpVOTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.DocumentoSimpVOTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("idDocumento" == ___local)&&("" == ___uri)) {
                            _getDocumentoSimpVO().add(((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.DocumentoSimpVOTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.DocumentoSimpVOTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  66 :
                        if (("dsMotivo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 67;
                            return ;
                        }
                        break;
                    case  24 :
                        if (("dsDDD" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        break;
                    case  36 :
                        if (("idStatusAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 37;
                            return ;
                        }
                        break;
                    case  81 :
                        if (("loginChefe" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 82;
                            return ;
                        }
                        break;
                    case  87 :
                        if (("dtInclusao" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 88;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("DocumentoSimpVO" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  108 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  48 :
                        if (("dsFornecedorConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 49;
                            return ;
                        }
                        break;
                    case  21 :
                        if (("idDDD" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("sobrenome" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        break;
                    case  30 :
                        if (("login" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 31;
                            return ;
                        }
                        break;
                    case  54 :
                        if (("dsSiteConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 55;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("UFOperadoraPessoaVO" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        if (("idUsuario" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  102 :
                        if (("paginaAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 103;
                            return ;
                        }
                        state = 105;
                        continue outer;
                    case  57 :
                        if (("dsLoginRoteamento" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 58;
                            return ;
                        }
                        break;
                    case  63 :
                        if (("idMotivo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 64;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("email" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        break;
                    case  99 :
                        if (("inConsultor" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 100;
                            return ;
                        }
                        state = 102;
                        continue outer;
                    case  60 :
                        if (("descricaoStatusAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 61;
                            return ;
                        }
                        break;
                    case  75 :
                        if (("idCargoAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 76;
                            return ;
                        }
                        break;
                    case  72 :
                        if (("dtRetorno" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 73;
                            return ;
                        }
                        break;
                    case  4 :
                        if (("idUFOperadora" == ___local)&&("" == ___uri)) {
                            _getUFOperadoraPessoaVO().add(((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.UFOperadoraPessoaVOTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.entrada.usrinserir.impl.UFOperadoraPessoaVOTypeImpl.class), 5, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  9 :
                        if (("nome" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("DocumentoSimpVO" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("UFOperadoraPessoaVO" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  45 :
                        if (("idFornecedorConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 46;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("nomeMeio" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  80 :
                        if (("descricaoCargoAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 81;
                            return ;
                        }
                        break;
                    case  98 :
                        if (("nmUF" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 99;
                            return ;
                        }
                        break;
                    case  92 :
                        if (("dtExclusao" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 93;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("nome" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("idUsuario" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  105 :
                        state = 108;
                        continue outer;
                    case  17 :
                        if (("sobrenome" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  101 :
                        if (("inConsultor" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 102;
                            return ;
                        }
                        break;
                    case  71 :
                        if (("dtInicio" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 72;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("UFOperadoraPessoaVO" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("dsDDD" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  65 :
                        if (("idMotivo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 66;
                            return ;
                        }
                        break;
                    case  83 :
                        if (("loginChefe" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 84;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("email" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  32 :
                        if (("login" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 33;
                            return ;
                        }
                        break;
                    case  77 :
                        if (("idCargoAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 78;
                            return ;
                        }
                        break;
                    case  95 :
                        if (("idUF" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 96;
                            return ;
                        }
                        break;
                    case  29 :
                        if (("dsTelefone" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 30;
                            return ;
                        }
                        break;
                    case  108 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  89 :
                        if (("dtInclusao" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 90;
                            return ;
                        }
                        break;
                    case  56 :
                        if (("dsSiteConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 57;
                            return ;
                        }
                        break;
                    case  104 :
                        if (("paginaAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 105;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("idDDD" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  38 :
                        if (("idStatusAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 39;
                            return ;
                        }
                        break;
                    case  53 :
                        if (("idSiteConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 54;
                            return ;
                        }
                        break;
                    case  41 :
                        if (("idPerfilConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 42;
                            return ;
                        }
                        break;
                    case  50 :
                        if (("dsFornecedorConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 51;
                            return ;
                        }
                        break;
                    case  74 :
                        if (("dtRetorno" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 75;
                            return ;
                        }
                        break;
                    case  47 :
                        if (("idFornecedorConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 48;
                            return ;
                        }
                        break;
                    case  44 :
                        if (("dsPerfilConsultorAtdAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 45;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("DocumentoSimpVO" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  102 :
                        state = 105;
                        continue outer;
                    case  68 :
                        if (("dsMotivo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 69;
                            return ;
                        }
                        break;
                    case  107 :
                        if (("registrosPPagina" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 108;
                            return ;
                        }
                        break;
                    case  35 :
                        if (("loginCti" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 36;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("nomeMeio" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  99 :
                        state = 102;
                        continue outer;
                    case  59 :
                        if (("dsLoginRoteamento" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 60;
                            return ;
                        }
                        break;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  86 :
                        if (("nomeChefe" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 87;
                            return ;
                        }
                        break;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  62 :
                        if (("descricaoStatusAtual" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 63;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  105 :
                        state = 108;
                        continue outer;
                    case  108 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  102 :
                        state = 105;
                        continue outer;
                    case  99 :
                        state = 102;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  105 :
                        state = 108;
                        continue outer;
                    case  108 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  102 :
                        state = 105;
                        continue outer;
                    case  99 :
                        state = 102;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  76 :
                            state = 77;
                            eatText1(value);
                            return ;
                        case  34 :
                            state = 35;
                            eatText2(value);
                            return ;
                        case  58 :
                            state = 59;
                            eatText3(value);
                            return ;
                        case  82 :
                            state = 83;
                            eatText4(value);
                            return ;
                        case  67 :
                            state = 68;
                            eatText5(value);
                            return ;
                        case  105 :
                            state = 108;
                            continue outer;
                        case  31 :
                            state = 32;
                            eatText6(value);
                            return ;
                        case  28 :
                            state = 29;
                            eatText7(value);
                            return ;
                        case  91 :
                            state = 92;
                            eatText8(value);
                            return ;
                        case  88 :
                            state = 89;
                            eatText9(value);
                            return ;
                        case  40 :
                            state = 41;
                            eatText10(value);
                            return ;
                        case  55 :
                            state = 56;
                            eatText11(value);
                            return ;
                        case  100 :
                            state = 101;
                            eatText12(value);
                            return ;
                        case  7 :
                            state = 8;
                            eatText13(value);
                            return ;
                        case  43 :
                            state = 44;
                            eatText14(value);
                            return ;
                        case  64 :
                            state = 65;
                            eatText15(value);
                            return ;
                        case  108 :
                            revertToParentFromText(value);
                            return ;
                        case  19 :
                            state = 20;
                            eatText16(value);
                            return ;
                        case  46 :
                            state = 47;
                            eatText17(value);
                            return ;
                        case  73 :
                            state = 74;
                            eatText18(value);
                            return ;
                        case  49 :
                            state = 50;
                            eatText19(value);
                            return ;
                        case  97 :
                            state = 98;
                            eatText20(value);
                            return ;
                        case  79 :
                            state = 80;
                            eatText21(value);
                            return ;
                        case  13 :
                            state = 14;
                            eatText22(value);
                            return ;
                        case  70 :
                            state = 71;
                            eatText23(value);
                            return ;
                        case  52 :
                            state = 53;
                            eatText24(value);
                            return ;
                        case  22 :
                            state = 23;
                            eatText25(value);
                            return ;
                        case  102 :
                            state = 105;
                            continue outer;
                        case  16 :
                            state = 17;
                            eatText26(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText27(value);
                            return ;
                        case  106 :
                            state = 107;
                            eatText28(value);
                            return ;
                        case  37 :
                            state = 38;
                            eatText29(value);
                            return ;
                        case  25 :
                            state = 26;
                            eatText30(value);
                            return ;
                        case  99 :
                            state = 102;
                            continue outer;
                        case  94 :
                            state = 95;
                            eatText31(value);
                            return ;
                        case  85 :
                            state = 86;
                            eatText32(value);
                            return ;
                        case  61 :
                            state = 62;
                            eatText33(value);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  103 :
                            state = 104;
                            eatText34(value);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdCargoAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LoginCti = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsLoginRoteamento = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LoginChefe = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsMotivo = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Login = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsTelefone = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DtExclusao = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DtInclusao = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdPerfilConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText11(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsSiteConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText12(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _InConsultor = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText13(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdUsuario = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText14(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsPerfilConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText15(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdMotivo = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText16(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Email = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText17(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdFornecedorConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText18(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DtRetorno = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText19(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsFornecedorConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText20(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NmUF = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText21(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DescricaoCargoAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText22(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NomeMeio = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText23(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DtInicio = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText24(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdSiteConsultorAtdAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText25(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdDDD = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText26(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Sobrenome = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText27(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Nome = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText28(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _RegistrosPPagina = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText29(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdStatusAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText30(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DsDDD = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText31(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _IdUF = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText32(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NomeChefe = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText33(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DescricaoStatusAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText34(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PaginaAtual = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
