LOAD DATA 
APPEND
INTO TABLE Customer.LinhaParceiro
FIELDS TERMINATED BY ';'
 OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  IDCLASSIFICACAO     ,
  IDPARCEIRO          ,
  CDAREAREGISTRO      ,
  NRLINHA             "rtrim(:NRLINHA,chr(13))",
  IDLINHAPARCEIRO     "Customer.LinhaParceiroSQ.nextval" ,
  STATUS              CONSTANT 1 ,
  IDUSUARIOALTERACAO  CONSTANT 11 ,
  DTULTIMAALTERACAO   SYSDATE
)
