LOAD DATA
APPEND
INTO TABLE CUSTOMER.PESSOASUBSEGMENTO
APPEND
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
    IDPESSOA,
    IDSISTEMAORIGEMSUBSEGMENTO,
    IDSUBSEGMENTO,
    IDUSUARIOALTERACAO "666",
    DTULTIMAALTERACAO "SYSDATE"
)
