set echo on
set serveroutput on
set trimspool on
set pages 0
set serveroutput on size 1000000

spool cargaCarteiraProspeccaoVenda.txt

SELECT 'COD_FTTX|CDENDERECO|NOME_CONDOMINIO|CLASSE SOCIAL|TIPO DE CONDOMINIO|SEGMENTO|LAYOUT DO CONDOMINIO|PRIORIDADE|SEGMENTACAO_MKT|COD_LOG|CHAVE_CEP|QTDE_BLOCOS|QTDE_APTOS|CNL|AREA_TELEFONICA|ENDERECO|NUMERO|NUMERO 2|CEP|BAIRRO|CIDADE|REGIAO|UF|STATUS_INFRA|DATA_CONCL_INFRA|CAPACIDADE_EQUIPAMENTO|OCUPACAO_EQUIPAMENTO|FIBRA_LIVRE|PERCENTUAL_OCUPACAO|OPERACAO COMERCIAL|NOME_VENDEDOR|NOME_EPS_VENDEDOR|USUARIO_VENDEDOR|NOME_ PROSPECTOR|NOME_EPS_PROSPECTOR|USUARIO_PROSPECTOR|NUM_CART|QTDE_ANDARES_BLOCO|QTDE_APTO_ANDAR|QTDE_DORM_APTO|METRAGEM_APTOS|IDADE_EDIFICIO|SINDICO_NOME|SINDICO_APTO|SINDICO_TEL_RES|SINDICO_TEL_COML|SINDICO_TEL_CEL|ZELADOR_NOME|ZELADOR_APTO|ZELADOR_TEL_RES|ZELADOR_TEL_CEL|ZELADOR_TEL_COML|ZELADOR_TEL_PORTARIA|LONGITUDE|LATITUDE|OBS|ERRO' FROM DUAL;
SELECT CDFTTX || '|' ||
CDENDERECO || '|' || 
NMCONDOMINIO || '|' || 
SGCLASSESOCIAL || '|' || 
DSTIPOCONDOMINIO || '|' || 
SGSEGMENTOAREA || '|' || 
DSLAYOUTCONDOMINIO || '|' || 
NRPRIORIDADEATENDIMENTO || '|' || 
SGSEGMENTOSERASA || '|' || 
CDLOGRADOUROCSO || '|' || 
CDCHAVECEP || '|' || 
QTBLOCO || '|' || 
QTAPARTAMENTO || '|' || 
CDCNL || '|' || 
SGAREATELEFONICA || '|' || 
DSLOGRADOURO || '|' || 
NRLOGRADOURO || '|' || 
NRLOGRADOUROSECUNDARIO || '|' || 
CDCEP || '|' || 
DSBAIRROLOGRADOURO || '|' || 
DSCIDADELOGRADOURO || '|' || 
DSREGIAOLOGRADOURO || '|' || 
SGUF || '|' || 
INSTATUSINFRAESTRUTURA || '|' || 
DTCONCLUSAOINFRAESTRUTURA || '|' || 
QTFIBRALIMITE || '|' || 
QTFIBRAOCUPADO || '|' || 
QTFIBRALIVRE || '|' || 
PCOCUPACAO || '|' || 
DSOPERACAOCOMERCIAL || '|' || 
NMVENDEDOR || '|' || 
DSFORNECEDORVENDEDOR || '|' || 
CDUSUARIOVENDEDOR || '|' || 
NMPROSPECTOR || '|' || 
NMFORNECEDORPROSPECTOR || '|' || 
CDUSUARIOPROSPECTOR || '|' || 
NRCARTEIRA || '|' || 
QTANDARBLOCO || '|' || 
QTAPARTAMENTOANDAR || '|' || 
QTDORMITORIOAPARTAMENTO || '|' || 
QTMETRAGEMAPARTAMENTO || '|' || 
QTIDADECONDOMINIO || '|' || 
NMSINDICO || '|' || 
NRAPARTAMENTOSINDICO || '|' || 
NRTELRESSINDICO || '|' || 
NRTELCOMSINDICO || '|' || 
NRTELCELSINDICO || '|' || 
NMZELADOR || '|' || 
NRAPARTAMENTOZELADOR || '|' || 
NRTELRESZELADOR || '|' || 
NRTELCELZELADOR || '|' || 
NRTELCOMZELADOR || '|' || 
NRTELPORTCONDOMINIO || '|' || 
NRLONGITUDE || '|' || 
NRLATITUDE || '|' || 
DSOBSERVACAO || '|' || 
DSMSG
FROM SFA.CARTPROSPECCAOVENDA_LDR
WHERE SGTIPOMSG = 'E';
	
spool off

set echo off
set serveroutput off
