/***********************************************************
  BATCH......: extracaoUsuario
  Criado por.: Williams Santos

***********************************************************/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
spool &1;

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

SELECT NMLOGINUSUARIO
   ||'|'|| NRDOCUMENTO
   ||'|'|| IDGRUPO
   ||'|'|| INSUPERVISOR
    FROM (SELECT AU.NMLOGINUSUARIO
               , D.NRDOCUMENTO
               , AUG.IDGRUPO
               , AUG.INSUPERVISOR
            FROM ACESSO.USUARIO AU
               , ACESSO.USUARIOGRUPO AUG
               , CUSTOMER.PESSOADOCUMENTO PD
               , CUSTOMER.DOCUMENTO D
               , ACESSO.GRUPO AG
           WHERE AU.IDSTATUSUSUARIO = 1
             AND AUG.IDPESSOAUSUARIO = AU.IDPESSOAUSUARIO
             AND PD.IDPESSOA = AU.IDPESSOAUSUARIO
             AND D.IDDOCUMENTO = PD.IDDOCUMENTO
             AND AG.IDGRUPO = AUG.IDGRUPO
             AND AG.DTEXCLUSAO IS NULL
          ORDER BY NMLOGINUSUARIO, NRDOCUMENTO, IDGRUPO
         );

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
