OPTIONS (ROWS=100, ERRORS=9999)
LOAD DATA
	CHARACTERSET WE8ISO8859P1
	REPLACE
	INTO TABLE LOAD.CARGA_CATALOGO_CRM
	FIELDS TERMINATED BY "|"
	(CDINTEGRACAO, CDSISTEMAORIGEM, NMSISTEMAORIGEM, NMCOMERCIALSERVICO, CDTIPOSERVICO, DSTIPOSERVICO, CDFAMILIASERVICO, DSFAMILIASERVICO)
