INSERT INTO APOIO.PARAMETRO (IDPARAMETRO,CDPARAMETRO,DSPARAMETRO,DSVALORPARAMETRO,IDUSUARIOALTERACAO,DTULTIMAALTERACAO)
VALUES
(APOIO.PARAMETROSQ.NEXTVAL,'QTDE_RESERVA_APARELHO','quantidade de reserva de aparelho a ser enviada por xml','500',1,sysdate);
commit;