/**
 * FrequenciaPT.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn;

public interface FrequenciaPT extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorValorFrequenciaResponse buscarListaModeloPorValorFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorValorFrequenciaRequest buscarListaModeloPorValorFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.CriarTipoFrequenciaResponse criarTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.CriarTipoFrequenciaRequest criarTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.CriarValorFrequenciaResponse criarValorFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.CriarValorFrequenciaRequest criarValorFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.ExcluirValorFrequenciaResponse excluirValorFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.ExcluirValorFrequenciaRequest excluirValorFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorTipoFrequenciaResponse buscarListaModeloPorTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorTipoFrequenciaRequest buscarListaModeloPorTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.ExcluirTipoFrequenciaResponse excluirTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.ExcluirTipoFrequenciaRequest excluirTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorTecnologiaTipoFrequenciaResponse buscarListaModeloPorTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaModeloPorTecnologiaTipoFrequenciaRequest buscarListaModeloPorTecnologiaTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaValorFrequenciaPorTecnologiaTipoFrequenciaResponse buscarListaValorFrequenciaPorTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaValorFrequenciaPorTecnologiaTipoFrequenciaRequest buscarListaValorFrequenciaPorTecnologiaTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaTipoFrequenciaComValorPorTecnologiaResponse buscarListaTipoFrequenciaComValorPorTecnologia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaTipoFrequenciaComValorPorTecnologiaRequest buscarListaTipoFrequenciaComValorPorTecnologiaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaTipoFrequenciaResponse buscarListaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaTipoFrequenciaRequest buscarListaTipoFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaValorFrequenciaResponse buscarListaValorFrequencia(br.com.vivo.catalogoPRS.ws.catalogoFrequencia.sn.BuscarListaValorFrequenciaRequest buscarListaValorFrequenciaRequest , String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoFrequencia.mc.geral.ErroInfo;
}
