SET SQLPROMPT ''
SET FEEDBACK OFF
SET ECHO OFF
SET AUTOTRACE OFF
SET FLUSH ON
SET HEADING OFF
SET SERVEROUTPUT ON
SET TIME OFF
SET TIMING OFF
SET TRIMOUT ON
SET TERMOUT OFF
SET TRIMSPOOL ON
SET PAUSE OFF
SET SHOWMODE OFF
SET SQLBLANKLINES OFF
SET SQLNUMBER OFF
SET TAB OFF
SET VERIFY OFF
SET WRAP OFF
SET FEED OFF
SET NEWPAGE NONE
SET LINESIZE 1024
SPOOL '&1' APPEND

VARIABLE VO_CDERRO NUMBER
VARIABLE VO_DSERRO VARCHAR2(512)

DECLARE
    V_IDCONTA NUMBER;
    V_DTULTIMAALTERACAO DATE;
	V_IDUSUARIOALTERACAO NUMBER := 235160;
	V_LOGINSISTEMAORIGEM VARCHAR2(32) := 'CARGAGESTOR';
	
	V_IDPESSOAGESTOR CUSTOMER.PESSOAGESTOR.IDPESSOAGESTOR%TYPE;
	V_GM_DTULTIMAALTERACAO DATE;
	V_GC_DTULTIMAALTERACAO DATE;

	V_PARAM_COMMIT NUMBER := &2;
	V_COUNT NUMBER := 0;
	V_COUNT_TOTAL NUMBER := 0;

	V_LOGMSG VARCHAR2(512);
BEGIN
	DBMS_OUTPUT.ENABLE (buffer_size => NULL);
	
	V_LOGMSG := 'atualizacaoDadosGestor: INICIO DO PROCESSAMENTO';
	INSERT INTO LOAD.logsegmentacaocarga(dtprocessamento, msg) VALUES (SYSTIMESTAMP, V_LOGMSG);
	COMMIT;
	
	SELECT /*+ parallel(C, 8) */ COUNT(1)
	INTO V_COUNT_TOTAL
	FROM LOAD.CARGAGESTORES C;
	
	V_LOGMSG := 'REGISTROS PROCESSADOS '||V_COUNT||' DE '||V_COUNT_TOTAL;
	INSERT INTO LOAD.logsegmentacaocarga(dtprocessamento, msg) VALUES (SYSTIMESTAMP, V_LOGMSG);
	COMMIT;			
	dbms_output.put_line(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS')||' -- '||V_LOGMSG);
	
	FOR R_GESTORES 
	IN (
		SELECT /*+ parallel(C, 12) */
			C.NOME
			,C.SOBRENOME
			,C.NMCOMPLETO
			,C.SIGLA
			,C.CPFGESTOR
			,C.CELVIVOGESTOR
			,C.TELCOMERCIALGESTOR
			,C.CPFCNPJCLIENTE
			,C.EMAILGESTOR
			,C.CDCONTASISTEMAORIGEM
			,C.IDPESSOASISTEMAORIGEM
			,C.DTATUALIZACAOCONTATO
			,C.DTATUALIZACAOASSOCIACAO
		FROM
			LOAD.CARGAGESTORES C
	)
	LOOP
		V_COUNT := V_COUNT + 1;

		CASE 
			-- Se a sigla "GM" – Gestor Master
			WHEN R_GESTORES.SIGLA = 'GM'
			THEN
				BEGIN
					-- 1.	Se a linha do arquivo estiver presente pelo NRDOCUMENTO na tabela CUSTOMER.PESSOAGESTOR e NRDOCUMENTOGESTOR + NRDOCUMENTOEMPRESA na tabela PESSOAGESTORMASTER.
					begin
						SELECT /*+ PARALLEL(PG, 8) */
							PG.DTULTIMAALTERACAO
		                INTO
		                    V_DTULTIMAALTERACAO
						FROM 
							CUSTOMER.PESSOAGESTOR PG
						WHERE
							PG.NRDOCUMENTO = R_GESTORES.CPFGESTOR
						;
		            exception
		            	when no_data_found then
		            		V_DTULTIMAALTERACAO := NULL;
		            end;
	
					IF V_DTULTIMAALTERACAO is NULL
					THEN
						SOA_OW.PRC_MANTERGERENTEPJ (
							VI_NMNOME => R_GESTORES.NOME
							,VI_NMNOMEMEIO => NULL
							,VI_NMSOBRENOME => R_GESTORES.SOBRENOME
							,VI_NRDOCUMENTO => R_GESTORES.CPFGESTOR
							,VI_DSCELULAR => R_GESTORES.CELVIVOGESTOR
							,VI_DSTELEFONE => R_GESTORES.TELCOMERCIALGESTOR
							,VI_DSEMAIL => R_GESTORES.EMAILGESTOR
							,VI_CDCONTA => R_GESTORES.CDCONTASISTEMAORIGEM
							,VI_CNPJ => R_GESTORES.CPFCNPJCLIENTE
							,VI_SGRELACIONAMENTO => R_GESTORES.SIGLA
							,VI_IDPESSOAGESTOR => NULL
							,VI_IDPESSOASISTEMAORIGEM => R_GESTORES.IDPESSOASISTEMAORIGEM
							,VI_IDUSUARIOALTERACAO => V_IDUSUARIOALTERACAO
							,VI_DTNASCIMENTO => NULL
							,VI_TIPOOPERACAO => 1
							,VI_LOGINSISTEMAORIGEM => V_LOGINSISTEMAORIGEM
							,VO_IDPESSOAGESTOR => V_IDPESSOAGESTOR
							,VO_CDERRO => :VO_CDERRO
							,VO_DSERRO => :VO_DSERRO
						);
						
						IF :VO_CDERRO <> 0
						THEN
							DBMS_OUTPUT.Put_Line('SOA_OW.PRC_MANTERGERENTEPJ: VO_CDERRO['||:VO_CDERRO||'], VO_DSERRO['||:VO_DSERRO||'], VI_SGRELACIONAMENTO['||R_GESTORES.SIGLA||'], VI_NRDOCUMENTO['||R_GESTORES.CPFGESTOR||'], VI_CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
						END IF;
	
					-- 1.1	Se o campo "DATA DE ULTIMA ATUALIZAÇÃO CONTATO" do arquivo é maior do que a data de ultima atualização da tabela CUSTOMER.PESSOAGESTOR
					ELSIF R_GESTORES.DTATUALIZACAOCONTATO > V_DTULTIMAALTERACAO
					THEN
						-- Deverá ser atualizado o registro do gestor máster dentro do processo atual.
					    UPDATE CUSTOMER.PESSOAGESTOR
					        SET NMPESSOAGESTOR =
					                R_GESTORES.NOME || ' ' || R_GESTORES.SOBRENOME,
					            NMGESTOR = R_GESTORES.NOME,
					            NMSOBRENOMEGESTOR = R_GESTORES.SOBRENOME,
					            NRTELEFONECELULARVIVO = R_GESTORES.CELVIVOGESTOR,
					            NRTELEFONEFIXO = R_GESTORES.TELCOMERCIALGESTOR,
					            EMAIL = R_GESTORES.EMAILGESTOR,
					            IDTIPODOCUMENTO =
					                    DECODE (R_GESTORES.CPFGESTOR, NULL, 
					                            NULL,
					                            1
					                           ),
					            IDUSUARIOALTERACAO = V_IDUSUARIOALTERACAO,
					            DTULTIMAALTERACAO = SYSDATE,
					            DTNASCIMENTO = NULL,
					            IDPESSOASISTEMAORIGEM = R_GESTORES.IDPESSOASISTEMAORIGEM,
								LOGINSISTEMAORIGEM = V_LOGINSISTEMAORIGEM
					    WHERE NRDOCUMENTO = R_GESTORES.CPFGESTOR;
	
						BEGIN
							select /*+ PARALLEL(8) */ DTULTIMAALTERACAO
							INTO V_GM_DTULTIMAALTERACAO
							from customer.PESSOAGESTORMASTER
							where nrdocumentoempresa = R_GESTORES.CPFCNPJCLIENTE;
						EXCEPTION
							WHEN NO_DATA_FOUND THEN
								V_GM_DTULTIMAALTERACAO := NULL;
						END;
	
						IF V_GM_DTULTIMAALTERACAO is null 
						THEN
							INSERT INTO CUSTOMER.PESSOAGESTORMASTER
							(
								NRDOCUMENTOGESTOR,
								NRDOCUMENTOEMPRESA,
								LOGINSISTEMAORIGEM,
								IDUSUARIOALTERACAO,
								DTULTIMAALTERACAO
							) VALUES (
								R_GESTORES.CPFGESTOR,
								R_GESTORES.CPFCNPJCLIENTE,
								V_LOGINSISTEMAORIGEM,
								V_IDUSUARIOALTERACAO,
								SYSDATE
							);
	
						ELSIF R_GESTORES.DTATUALIZACAOASSOCIACAO > V_GM_DTULTIMAALTERACAO
						THEN
							UPDATE CUSTOMER.PESSOAGESTORMASTER
							   SET NRDOCUMENTOGESTOR = R_GESTORES.CPFGESTOR,
							       LOGINSISTEMAORIGEM = V_LOGINSISTEMAORIGEM,
								   IDUSUARIOALTERACAO = V_IDUSUARIOALTERACAO,
								   DTULTIMAALTERACAO = SYSDATE
							 WHERE NRDOCUMENTOEMPRESA = R_GESTORES.CPFCNPJCLIENTE;

						ELSE
							DBMS_OUTPUT.Put_Line('GM ASSOCIACAO NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
						END IF;
					ELSE
	                 	DBMS_OUTPUT.Put_Line('GM NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');			
						BEGIN
							select /*+ PARALLEL(8) */ DTULTIMAALTERACAO
							INTO V_GM_DTULTIMAALTERACAO
							from customer.PESSOAGESTORMASTER
							where nrdocumentoempresa = R_GESTORES.CPFCNPJCLIENTE;
						EXCEPTION
							WHEN NO_DATA_FOUND THEN
								V_GM_DTULTIMAALTERACAO := NULL;
						END;
						
						IF V_GM_DTULTIMAALTERACAO IS NOT NULL
						THEN
							IF R_GESTORES.DTATUALIZACAOASSOCIACAO > V_GM_DTULTIMAALTERACAO
							THEN
								UPDATE CUSTOMER.PESSOAGESTORMASTER
								   SET NRDOCUMENTOGESTOR = R_GESTORES.CPFGESTOR,
								       LOGINSISTEMAORIGEM = V_LOGINSISTEMAORIGEM,
									   IDUSUARIOALTERACAO = V_IDUSUARIOALTERACAO,
									   DTULTIMAALTERACAO = SYSDATE
								 WHERE NRDOCUMENTOEMPRESA = R_GESTORES.CPFCNPJCLIENTE;

							ELSE
								DBMS_OUTPUT.Put_Line('GM ASSOCIACAO NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
							END IF;
						ELSE
							INSERT INTO CUSTOMER.PESSOAGESTORMASTER
							(
								NRDOCUMENTOGESTOR,
								NRDOCUMENTOEMPRESA,
								LOGINSISTEMAORIGEM,
								IDUSUARIOALTERACAO,
								DTULTIMAALTERACAO
							) VALUES (
								R_GESTORES.CPFGESTOR,
								R_GESTORES.CPFCNPJCLIENTE,
								V_LOGINSISTEMAORIGEM,
								V_IDUSUARIOALTERACAO,
								SYSDATE
							);

						END IF;
					END IF; 
	    		EXCEPTION
	        		WHEN OTHERS THEN
	        			dbms_output.put_line('ERRO ORACLE: SQLCODE['||SQLCODE||'], SQLERRM['||SQLERRM||']');
						DBMS_OUTPUT.Put_Line('ERRO ORACLE: GM NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
				END;

			-- Se a sigla "GC" – Gestor Conta
			WHEN R_GESTORES.SIGLA = 'GC'
			THEN
				BEGIN
					-- 1.	Se a linha do arquivo estiver presente pelo NRDOCUMENTO na tabela CUSTOMER.PESSOAGESTOR e NRDOCUMENTO na tabela PESSOAGESTORCONTA
					begin
		                SELECT /*+ PARALLEL(PG, 8) */
		                    PG.DTULTIMAALTERACAO
		                    ,IDPESSOAGESTOR
		                INTO
		                    V_DTULTIMAALTERACAO
		                    ,V_IDPESSOAGESTOR
		                FROM 
		                    CUSTOMER.PESSOAGESTOR PG
		                WHERE
		                    PG.NRDOCUMENTO = R_GESTORES.CPFGESTOR ;
		            exception
		            	when no_data_found then
		            		V_DTULTIMAALTERACAO := NULL;
		            		V_IDPESSOAGESTOR := NULL;
		            end;

					-- 1.1	Se o campo "DATA DE ULTIMA ATUALIZAÇÃO CONTATO" do arquivo é maior do que a data de ultima atualização da tabela CUSTOMER.PESSOAGESTOR
	            	IF V_DTULTIMAALTERACAO IS NULL OR (R_GESTORES.DTATUALIZACAOCONTATO > V_DTULTIMAALTERACAO )
					THEN
						-- Deverá ser atualizado o registro do gestor conta dentro do processo atual.
						SOA_OW.PRC_MANTERGERENTEPJ (
							VI_NMNOME => R_GESTORES.NOME
							,VI_NMNOMEMEIO => NULL
							,VI_NMSOBRENOME => R_GESTORES.SOBRENOME
							,VI_NRDOCUMENTO => R_GESTORES.CPFGESTOR
							,VI_DSCELULAR => R_GESTORES.CELVIVOGESTOR
							,VI_DSTELEFONE => R_GESTORES.TELCOMERCIALGESTOR
							,VI_DSEMAIL => R_GESTORES.EMAILGESTOR
							,VI_CDCONTA => R_GESTORES.CDCONTASISTEMAORIGEM
							,VI_CNPJ => R_GESTORES.CPFCNPJCLIENTE
							,VI_SGRELACIONAMENTO => R_GESTORES.SIGLA
							,VI_IDPESSOAGESTOR => NULL
							,VI_IDPESSOASISTEMAORIGEM => R_GESTORES.IDPESSOASISTEMAORIGEM
							,VI_IDUSUARIOALTERACAO => V_IDUSUARIOALTERACAO
							,VI_DTNASCIMENTO => NULL
							,VI_TIPOOPERACAO => 1
							,VI_LOGINSISTEMAORIGEM => V_LOGINSISTEMAORIGEM
							,VO_IDPESSOAGESTOR => V_IDPESSOAGESTOR
							,VO_CDERRO => :VO_CDERRO
							,VO_DSERRO => :VO_DSERRO
						);
						
						IF :VO_CDERRO <> 0
						THEN
							DBMS_OUTPUT.Put_Line('SOA_OW.PRC_MANTERGERENTEPJ: VO_CDERRO['||:VO_CDERRO||'], VO_DSERRO['||:VO_DSERRO||'], VI_SGRELACIONAMENTO['||R_GESTORES.SIGLA||'], VI_NRDOCUMENTO['||R_GESTORES.CPFGESTOR||'], VI_CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
						END IF;
							
					-- 1.2	Se o campo "DATA DE ULTIMA ATUALIZAÇÃO CONTATO" do arquivo é menor do que a data de ultima atualização da tabela CUSTOMER.PESSOAGESTOR e o campo CÓDIGO CONTA SISTEMA ORIGEM for diferente do CDCONTA da tabela do contato.
					ELSE
						IF V_DTULTIMAALTERACAO IS NOT NULL 
						THEN
							DBMS_OUTPUT.Put_Line('GC NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CNPJ['||R_GESTORES.CPFCNPJCLIENTE||']');
						END IF;
					
		                BEGIN
		                    SELECT /*+ PARALLEL(8) */
		                        CONTA.IDCONTA
		                    INTO 
		                        V_IDCONTA
		                    FROM 
		                        CUSTOMER.CONTA CONTA
		                    WHERE 
		                        CONTA.IDSISTEMAORIGEM = 1
		                    AND CONTA.IDCONTASISTEMAORIGEM = R_GESTORES.CDCONTASISTEMAORIGEM --(enviado no arquivo) 
		                    AND CONTA.IDTIPOCONTASISTEMAORIGEM = 1;
		               	EXCEPTION
		                    WHEN NO_DATA_FOUND THEN
		                    	V_IDCONTA := NULL;
		                END;
	
		               	IF V_IDCONTA IS NULL
		               	THEN
	                        CONSUMO.GETIDCONTA(1,R_GESTORES.CDCONTASISTEMAORIGEM,V_IDCONTA);
	                    
	                    	-- Insere a conta associada ao gestor:
	                        INSERT INTO CUSTOMER.PESSOAGESTORCONTA
	                        (
	                            NRDOCUMENTO,
	                            IDCONTA,
	                            IDTIPORELACIONAMENTO,
	                            LOGINSISTEMAORIGEM,
	                            IDUSUARIOALTERACAO,
	                            DTULTIMAALTERACAO,
	                            IDPESSOAGESTOR
	                        )
	                        VALUES (
	                            R_GESTORES.CPFGESTOR,
	                            V_IDCONTA,
	                            (SELECT IDTIPORELACIONAMENTO FROM CUSTOMER.TIPORELACIONAMENTO WHERE SGTIPORELACIONAMENTO = R_GESTORES.SIGLA),
	                            V_LOGINSISTEMAORIGEM,
	                            V_IDUSUARIOALTERACAO,
	                            SYSDATE,
	                            V_IDPESSOAGESTOR
	                        );

						ELSE
	        				begin
	            				SELECT /*+ PARALLEL(8) */ DTULTIMAALTERACAO
	            				INTO V_GC_DTULTIMAALTERACAO
	            				FROM CUSTOMER.PESSOAGESTORCONTA
	            				WHERE IDCONTA = V_IDCONTA;
	        				exception
	        					when others then
	        						V_GC_DTULTIMAALTERACAO := NULL;
	        				end;
	        				
	        				IF V_GC_DTULTIMAALTERACAO IS NULL OR (R_GESTORES.DTATUALIZACAOASSOCIACAO > V_GC_DTULTIMAALTERACAO)
	        				THEN
								DELETE FROM CUSTOMER.PESSOAGESTORCONTA PGC
								WHERE
									PGC.IDTIPORELACIONAMENTO = 5 
								AND
									IDCONTA = V_IDCONTA
								;

	
								INSERT INTO CUSTOMER.PESSOAGESTORCONTA 
								(
									NRDOCUMENTO,
									IDCONTA,
									IDTIPORELACIONAMENTO,
									LOGINSISTEMAORIGEM,
									IDUSUARIOALTERACAO,
									DTULTIMAALTERACAO,
									IDPESSOAGESTOR
								) VALUES (
									R_GESTORES.CPFGESTOR,
									V_IDCONTA,
									(SELECT IDTIPORELACIONAMENTO FROM CUSTOMER.TIPORELACIONAMENTO WHERE SGTIPORELACIONAMENTO = R_GESTORES.SIGLA),
									V_LOGINSISTEMAORIGEM,
									V_IDUSUARIOALTERACAO,
									SYSDATE,
									V_IDPESSOAGESTOR
								);

							ELSE
								DBMS_OUTPUT.Put_Line('GC ASSOCIACAO NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CONTA['||R_GESTORES.CDCONTASISTEMAORIGEM||']');
							END IF;
	            		END IF;
					END IF;
        		EXCEPTION
            		WHEN OTHERS THEN
            			dbms_output.put_line('ERRO ORACLE: SQLCODE['||SQLCODE||'], SQLERRM['||SQLERRM||']');
						DBMS_OUTPUT.Put_Line('ERRO ORACLE: GC NAO ATUALIZADO: CPF['||R_GESTORES.CPFGESTOR||'], CONTA['||R_GESTORES.CDCONTASISTEMAORIGEM||']');
				END;
		END CASE;
		
		IF MOD(V_COUNT, V_PARAM_COMMIT) = 0
		THEN
			V_LOGMSG := 'REGISTROS PROCESSADOS: '||V_COUNT||' DE '||V_COUNT_TOTAL;
			INSERT INTO LOAD.logsegmentacaocarga(dtprocessamento, msg)VALUES (SYSTIMESTAMP, V_LOGMSG);
			COMMIT;
			dbms_output.put_line(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS')||' -- '||V_LOGMSG);
		END IF;
	END LOOP;

	V_LOGMSG := 'REGISTROS PROCESSADOS: '||V_COUNT||' DE '||V_COUNT_TOTAL;
	INSERT INTO LOAD.logsegmentacaocarga(dtprocessamento, msg)VALUES (SYSTIMESTAMP, V_LOGMSG);
	dbms_output.put_line(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS')||' -- '||V_LOGMSG);
	
	V_LOGMSG := 'atualizacaoDadosGestor: FIM DO PROCESSAMENTO';
	INSERT INTO LOAD.logsegmentacaocarga(dtprocessamento, msg)VALUES (SYSTIMESTAMP, V_LOGMSG);	
	COMMIT;
	
	:VO_CDERRO := 0;
	:VO_DSERRO := 'Sucesso';
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		:VO_CDERRO := 99;
		:VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRIÇÃO DO ERRO: ' || SQLERRM;
END;
/

select CHR(10) from dual;
select 'VO_CDERRO', :VO_CDERRO from dual;
select 'VO_DSERRO', :VO_DSERRO from dual;

SPOOL OFF

exit
