
LOAD DATA 
CHARACTERSET WE8ISO8859P1
INTO TABLE LOAD.CARGAGESTORES
APPEND
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
	NOME CHAR,
	SOBRENOME CHAR,
	NMCOMPLETO CHAR,
	SIGLA CHAR,
	CPFGESTOR CHAR,
	CELVIVOGESTOR INTEGER EXTERNAL,
	TELCOMERCIALGESTOR INTEGER EXTERNAL,
	CPFCNPJCLIENTE CHAR,
	EMAILGESTOR CHAR,
	CDCONTASISTEMAORIGEM CHAR,
	IDPESSOASISTEMAORIGEM CHAR,
	DTATUALIZACAOCONTATO TIMESTAMP "DD/MM/YYYY HH24:MI:SS",
	DTATUALIZACAOASSOCIACAO TIMESTAMP "DD/MM/YYYY HH24:MI:SS"
)
