//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.28 at 11:52:53 AM BRST 
//


package br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada;


/**
 * Java content class for AtendimentoVOType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 23)
 * <p>
 * <pre>
 * &lt;complexType name="AtendimentoVOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idAtendimento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="msgError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idLinhaAtendimento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idUfOperadora" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idTipoLinha" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idChamadaTelefonica" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="inResponsavelAbertura" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idGrupoAbertura" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="observacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inTipoPessoa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrTelefone" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="tpOperacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ProcedenciaVO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idProcedencia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CanalVO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idCanal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Contas" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContaVO" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LinhaVO" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="idPessoaLinhaHistorico" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="idConta" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PessoaVO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idPessoa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UsuarioLinhaVO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idPessoa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ArvoreAtendimento" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nmPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CarterizacaoVO" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="idTipoCarteira" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="SegmentacaoVO" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="idSegmentacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LinhasAssociadasVO" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cdConta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="nrTelefone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AtendimentoVOType {


    /**
     * Gets the value of the nrTelefone property.
     * 
     */
    long getNrTelefone();

    /**
     * Sets the value of the nrTelefone property.
     * 
     */
    void setNrTelefone(long value);

    /**
     * Gets the value of the inTipoPessoa property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInTipoPessoa();

    /**
     * Sets the value of the inTipoPessoa property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInTipoPessoa(java.lang.String value);

    /**
     * Gets the value of the idAtendimento property.
     * 
     */
    int getIdAtendimento();

    /**
     * Sets the value of the idAtendimento property.
     * 
     */
    void setIdAtendimento(int value);

    /**
     * Gets the value of the idChamadaTelefonica property.
     * 
     */
    int getIdChamadaTelefonica();

    /**
     * Sets the value of the idChamadaTelefonica property.
     * 
     */
    void setIdChamadaTelefonica(int value);

    /**
     * Gets the value of the canalVO property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.CanalVOType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.CanalVOType getCanalVO();

    /**
     * Sets the value of the canalVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.CanalVOType}
     */
    void setCanalVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.CanalVOType value);

    /**
     * Gets the value of the LinhasAssociadasVO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the LinhasAssociadasVO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinhasAssociadasVO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.LinhasAssociadasVOType}
     * 
     */
    java.util.List getLinhasAssociadasVO();

    /**
     * Gets the value of the pessoaVO property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.PessoaVOType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.PessoaVOType getPessoaVO();

    /**
     * Sets the value of the pessoaVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.PessoaVOType}
     */
    void setPessoaVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.PessoaVOType value);

    /**
     * Gets the value of the procedenciaVO property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ProcedenciaVOType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ProcedenciaVOType getProcedenciaVO();

    /**
     * Sets the value of the procedenciaVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ProcedenciaVOType}
     */
    void setProcedenciaVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ProcedenciaVOType value);

    /**
     * Gets the value of the contas property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType getContas();

    /**
     * Sets the value of the contas property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType}
     */
    void setContas(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType value);

    /**
     * Gets the value of the idUfOperadora property.
     * 
     */
    int getIdUfOperadora();

    /**
     * Sets the value of the idUfOperadora property.
     * 
     */
    void setIdUfOperadora(int value);

    /**
     * Gets the value of the idGrupoAbertura property.
     * 
     */
    int getIdGrupoAbertura();

    /**
     * Sets the value of the idGrupoAbertura property.
     * 
     */
    void setIdGrupoAbertura(int value);

    /**
     * Gets the value of the msgError property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMsgError();

    /**
     * Sets the value of the msgError property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMsgError(java.lang.String value);

    /**
     * Gets the value of the idLinhaAtendimento property.
     * 
     */
    int getIdLinhaAtendimento();

    /**
     * Sets the value of the idLinhaAtendimento property.
     * 
     */
    void setIdLinhaAtendimento(int value);

    /**
     * Gets the value of the inResponsavelAbertura property.
     * 
     */
    int getInResponsavelAbertura();

    /**
     * Sets the value of the inResponsavelAbertura property.
     * 
     */
    void setInResponsavelAbertura(int value);

    /**
     * Gets the value of the tpOperacao property.
     * 
     */
    int getTpOperacao();

    /**
     * Sets the value of the tpOperacao property.
     * 
     */
    void setTpOperacao(int value);

    /**
     * Gets the value of the arvoreAtendimento property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType getArvoreAtendimento();

    /**
     * Sets the value of the arvoreAtendimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType}
     */
    void setArvoreAtendimento(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType value);

    /**
     * Gets the value of the idTipoLinha property.
     * 
     */
    int getIdTipoLinha();

    /**
     * Sets the value of the idTipoLinha property.
     * 
     */
    void setIdTipoLinha(int value);

    /**
     * Gets the value of the usuarioLinhaVO property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.UsuarioLinhaVOType}
     */
    br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.UsuarioLinhaVOType getUsuarioLinhaVO();

    /**
     * Sets the value of the usuarioLinhaVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.UsuarioLinhaVOType}
     */
    void setUsuarioLinhaVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.UsuarioLinhaVOType value);

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getObservacao();

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setObservacao(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 86)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nmPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CarterizacaoVO" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="idTipoCarteira" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SegmentacaoVO" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="idSegmentacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ArvoreAtendimentoType {


        /**
         * Gets the value of the carterizacaoVO property.
         * 
         * @return
         *     possible object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.CarterizacaoVOType}
         */
        br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.CarterizacaoVOType getCarterizacaoVO();

        /**
         * Sets the value of the carterizacaoVO property.
         * 
         * @param value
         *     allowed object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.CarterizacaoVOType}
         */
        void setCarterizacaoVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.CarterizacaoVOType value);

        /**
         * Gets the value of the nmPath property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getNmPath();

        /**
         * Sets the value of the nmPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setNmPath(java.lang.String value);

        /**
         * Gets the value of the segmentacaoVO property.
         * 
         * @return
         *     possible object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.SegmentacaoVOType}
         */
        br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.SegmentacaoVOType getSegmentacaoVO();

        /**
         * Sets the value of the segmentacaoVO property.
         * 
         * @param value
         *     allowed object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.SegmentacaoVOType}
         */
        void setSegmentacaoVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ArvoreAtendimentoType.SegmentacaoVOType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 90)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="idTipoCarteira" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface CarterizacaoVOType {


            /**
             * Gets the value of the idTipoCarteira property.
             * 
             */
            int getIdTipoCarteira();

            /**
             * Sets the value of the idTipoCarteira property.
             * 
             */
            void setIdTipoCarteira(int value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 97)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="idSegmentacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface SegmentacaoVOType {


            /**
             * Gets the value of the idSegmentacao property.
             * 
             */
            int getIdSegmentacao();

            /**
             * Sets the value of the idSegmentacao property.
             * 
             */
            void setIdSegmentacao(int value);

        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 45)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idCanal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface CanalVOType {


        /**
         * Gets the value of the idCanal property.
         * 
         */
        int getIdCanal();

        /**
         * Sets the value of the idCanal property.
         * 
         */
        void setIdCanal(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 52)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContaVO" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LinhaVO" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="idPessoaLinhaHistorico" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="idConta" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ContasType {


        /**
         * Gets the value of the contaVO property.
         * 
         * @return
         *     possible object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType}
         */
        br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType getContaVO();

        /**
         * Sets the value of the contaVO property.
         * 
         * @param value
         *     allowed object is
         *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType}
         */
        void setContaVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 55)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LinhaVO" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="idPessoaLinhaHistorico" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="idConta" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface ContaVOType {


            /**
             * Gets the value of the idConta property.
             * 
             */
            long getIdConta();

            /**
             * Sets the value of the idConta property.
             * 
             */
            void setIdConta(long value);

            /**
             * Gets the value of the linhaVO property.
             * 
             * @return
             *     possible object is
             *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType.LinhaVOType}
             */
            br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType.LinhaVOType getLinhaVO();

            /**
             * Sets the value of the linhaVO property.
             * 
             * @param value
             *     allowed object is
             *     {@link br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType.LinhaVOType}
             */
            void setLinhaVO(br.com.indrasistemas.vivoservices.listapup.tuxgateway.entrada.AtendimentoVOType.ContasType.ContaVOType.LinhaVOType value);


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 58)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="idPessoaLinhaHistorico" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface LinhaVOType {


                /**
                 * Gets the value of the idPessoaLinhaHistorico property.
                 * 
                 */
                int getIdPessoaLinhaHistorico();

                /**
                 * Sets the value of the idPessoaLinhaHistorico property.
                 * 
                 */
                void setIdPessoaLinhaHistorico(int value);

            }

        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 107)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cdConta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="nrTelefone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface LinhasAssociadasVOType {


        /**
         * Gets the value of the nrTelefone property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getNrTelefone();

        /**
         * Sets the value of the nrTelefone property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setNrTelefone(java.lang.String value);

        /**
         * Gets the value of the cdConta property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getCdConta();

        /**
         * Sets the value of the cdConta property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setCdConta(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 72)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idPessoa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface PessoaVOType {


        /**
         * Gets the value of the idPessoa property.
         * 
         */
        int getIdPessoa();

        /**
         * Sets the value of the idPessoa property.
         * 
         */
        void setIdPessoa(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 38)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idProcedencia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ProcedenciaVOType {


        /**
         * Gets the value of the idProcedencia property.
         * 
         */
        int getIdProcedencia();

        /**
         * Sets the value of the idProcedencia property.
         * 
         */
        void setIdProcedencia(int value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/indra_work/VivoServices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/listapup/tuxgateway/entrada/regContatoIN.xsd line 79)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idPessoa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface UsuarioLinhaVOType {


        /**
         * Gets the value of the idPessoa property.
         * 
         */
        int getIdPessoa();

        /**
         * Sets the value of the idPessoa property.
         * 
         */
        void setIdPessoa(int value);

    }

}
