LOAD DATA 
REPLACE
INTO TABLE LOAD.RESSARCIMENTOBILLING
WHEN DSTIPORESSARCIMENTO = 'PED'
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	DSTIPORESSARCIMENTO,
	CDLINHADW,
	NRASSINATURA,
	NRLINHA,
	DSPLANO,
	NREVENTOANATEL,
	DTINICIOINTERRUPCAO,
	DTFIMINTERRUPCAO,
	HRINICIOINTERRUPCAO,
	HRFIMINTERRUPCAO,
	NRTEMPOINTERRUPCAO,
	VLRESSARCIMENTO,
	DTCONCESSAORESSARCIMENTO,
	DSSTATUS,
	NRCICLO,
	DTFATURA,
	DTPROCESSAMENTO,
	SGUF,
	NMMUNICIPIO,
	VLARPU
)