declare
    N_START             NUMBER;
    N_STOP              NUMBER;
    V_IDPARCEIRO        NUMBER;
    V_PARCEIROSQ        NUMBER;
    V_IDCLASSIFICACAO   NUMBER;
    V_CLASSIFICACAOSQ   NUMBER;
begin
    -- SAPOIO_OW.PARCEIRO
    SELECT MAX(IDPARCEIRO) INTO V_IDPARCEIRO FROM SAPOIO_OW.PARCEIRO;
    SELECT SAPOIO_OW.PARCEIROSQ.NEXTVAL INTO V_PARCEIROSQ FROM DUAL;
    N_STOP := V_IDPARCEIRO - V_PARCEIROSQ;
    IF N_STOP > 0 THEN
        FOR Y IN 1 .. N_STOP LOOP
            SELECT SAPOIO_OW.PARCEIROSQ.NEXTVAL INTO N_START FROM DUAL;
        END LOOP;
    END IF;

    -- SAPOIO_OW.CLASSIFICACAO
    SELECT MAX(IDCLASSIFICACAO) INTO V_IDCLASSIFICACAO FROM SAPOIO_OW.CLASSIFICACAO;
    SELECT SAPOIO_OW.CLASSIFICACAOSQ.NEXTVAL INTO V_CLASSIFICACAOSQ FROM DUAL;
    N_STOP := V_IDCLASSIFICACAO - V_CLASSIFICACAOSQ;
    IF N_STOP > 0 THEN
        FOR Y IN 1 .. N_STOP LOOP
            SELECT SAPOIO_OW.CLASSIFICACAOSQ.NEXTVAL INTO N_START FROM DUAL;
        END LOOP;
    END IF;

end;