LOAD DATA
APPEND INTO TABLE CUSTOMER.CARGAPROGRAMARELACIONAMENTO
Fields terminated by ";"
(
  NRDOCUMENTO,
  NRTELEFONE,
  INPR,
  DTCADASTROPR DATE "YYYY-MM-DD HH24:MI:SS",
  DTATUALIZACAOPR DATE "YYYY-MM-DD HH24:MI:SS",
  INCADASTROMANUAL,
  NMLOGINATUALIZACAOPR,
  IDSISTEMAORIGEMPR,
  NRLINHACONTATO,
  NMLOGINATUALIZACAOLC,
  IDSISTEMAATUALIZACAOLC
)