//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 05:26:36 PM BRST 
//


package br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.saida.usrinserir;


/**
 * Java content class for msgBodyType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/administracaosistema/usuario/manter/tuxgateway/saida/usrinserir/UsuarioLDAPVO.xsd line 20)
 * <p>
 * <pre>
 * &lt;complexType name="msgBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="UsuarioLDAPVO">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="idUsuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="idUF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="primeiroAcesso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sobrenome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MsgBodyType {


    /**
     * Gets the value of the usuarioLDAPVO property.
     * 
     * @return
     *     possible object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.saida.usrinserir.MsgBodyType.UsuarioLDAPVOType}
     */
    br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.saida.usrinserir.MsgBodyType.UsuarioLDAPVOType getUsuarioLDAPVO();

    /**
     * Sets the value of the usuarioLDAPVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.saida.usrinserir.MsgBodyType.UsuarioLDAPVOType}
     */
    void setUsuarioLDAPVO(br.com.indrasistemas.vivoservices.administracaosistema.usuario.manter.tuxgateway.saida.usrinserir.MsgBodyType.UsuarioLDAPVOType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/administracaosistema/usuario/manter/tuxgateway/saida/usrinserir/UsuarioLDAPVO.xsd line 23)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="idUsuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="idUF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="primeiroAcesso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sobrenome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface UsuarioLDAPVOType {


        /**
         * Gets the value of the primeiroAcesso property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPrimeiroAcesso();

        /**
         * Sets the value of the primeiroAcesso property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPrimeiroAcesso(java.lang.String value);

        /**
         * Gets the value of the idUF property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getIdUF();

        /**
         * Sets the value of the idUF property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setIdUF(java.lang.String value);

        /**
         * Gets the value of the idUsuario property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getIdUsuario();

        /**
         * Sets the value of the idUsuario property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setIdUsuario(java.lang.String value);

        /**
         * Gets the value of the sobrenome property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getSobrenome();

        /**
         * Sets the value of the sobrenome property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setSobrenome(java.lang.String value);

        /**
         * Gets the value of the login property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getLogin();

        /**
         * Sets the value of the login property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setLogin(java.lang.String value);

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getNome();

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setNome(java.lang.String value);

    }

}
