/**
 * ModeloPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoModelo.sn;

public interface ModeloPortType extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.UpdateGrupoProdutoResponse updateGrupoProduto(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.UpdateGrupoProdutoRequest updateGrupoProdutoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaCaracteristicaDispProdutoModeloResponse buscarListaCaracteristicaDispProdutoModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaCaracteristicaDispProdutoModeloRequest buscarListaCaracteristicaDispProdutoModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExportarModeloResponse exportarModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExportarModeloRequest exportarModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExportarRestricoesModeloResponse exportarRestricoesModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExportarRestricoesModeloRequest exportarRestricoesModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloPorTipoProdutoFabricanteResponse buscarListaModeloPorTipoProdutoFabricante(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloPorTipoProdutoFabricanteRequest buscarListaModeloPorTipoProdutoFabricanteRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarGrupoProdutoPorIdResponse buscarGrupoProdutoPorId(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarGrupoProdutoPorIdRequest buscarGrupoProdutoPorIdRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloPorTecnologiaTpFrequenciaVlResponse buscarListaModeloPorTecnologiaTpFrequenciaVl(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloPorTecnologiaTpFrequenciaVlRequest buscarListaModeloPorTecnologiaTpFrequenciaVlRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloListaTecnologiaTipoFrequenciaValorFrequenciaResponse buscarModeloListaTecnologiaTipoFrequenciaValorFrequencia(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloListaTecnologiaTipoFrequenciaValorFrequenciaRequest buscarModeloListaTecnologiaTipoFrequenciaValorFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.DisponibilizarModeloResponse disponibilizarModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.DisponibilizarModeloRequest disponibilizarModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarDetalhesModeloResponse buscarDetalhesModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarDetalhesModeloRequest buscarDetalhesModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloResponse buscarListaModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloRequest buscarListaModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloDispComFabricanteResponse buscarListaModeloDispComFabricante(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaModeloDispComFabricanteRequest buscarListaModeloDispComFabricanteRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaRestricoesModeloResponse buscarListaRestricoesModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaRestricoesModeloRequest buscarListaRestricoesModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaCaracteristicaProdutoModeloResponse buscarListaCaracteristicaProdutoModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarListaCaracteristicaProdutoModeloRequest buscarListaCaracteristicaProdutoModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloPorIdResponse buscarModeloPorId(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloPorIdRequest buscarModeloPorIdRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public java.lang.Object alterarModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.AlterarModeloRequest alterarModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.CriarModeloResponse criarModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.CriarModeloRequest criarModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloPorTecnologiaTpFrequenciaVlResponse buscarModeloPorTecnologiaTpFrequenciaVl(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.BuscarModeloPorTecnologiaTpFrequenciaVlRequest buscarModeloPorTecnologiaTpFrequenciaVlRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExcluirListaModeloResponse excluirListaModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.ExcluirListaModeloRequest excluirListaModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public java.lang.Object alterarModeloCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.AlterarModeloCaracteristicaRequest alterarModeloCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.AlterarFimVidaModeloResponse alterarFimVidaModelo(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.AlterarFimVidaModeloRequest alterarFimVidaModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
    public java.lang.Object associarModeloCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoModelo.sn.AssociarModeloCaracteristicaRequest associarModeloCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoModelo.mc.geral.ErroInfo;
}
