set timi on
set echo on
spool A_L1121.log


CREATE TABLE ATENDIMENTO.ATENDIMENTOANATEL
(
  IDATENDIMENTOANATEL         NUMBER                        NOT NULL,
  NRSOLICITACAO               NUMBER                        NOT NULL,
  IDATENDIMENTOANATELARQUIVO  NUMBER,
  IDATENDIMENTO               NUMBER,
  IDATENDIMENTOPROTOCOLO      NUMBER,  
  DSTIPOATENDIMENTOANATEL     VARCHAR2(255 BYTE),
  DSSERVICO					  VARCHAR2(255 BYTE),
  DSMODALIDADE				  VARCHAR2(255 BYTE),
  DSMOTIVO					  VARCHAR2(255 BYTE),
  DSSUBMOTIVO				  VARCHAR2(255 BYTE),
  DSCATEGORIA				  VARCHAR2(255 BYTE),
  DSSUBCATEGORIA			  VARCHAR2(255 BYTE),  
  NMACAO                      VARCHAR2(255 BYTE),
  NRTELEFONEPROBLEMA          VARCHAR2(255 BYTE)            NOT NULL,
  NRCPFCNPJASSINANTE          VARCHAR2(255 BYTE)            NOT NULL,
  NMASSINANTE                 VARCHAR2(255 BYTE),
  DTREGISTRO                  DATE,  
  CDSITUACAO                  NUMBER,
  DSSITUACAO                  VARCHAR2(255 BYTE),
  CDVIARESPOSTA               NUMBER,
  DSVIARESPOSTA               VARCHAR2(255 BYTE),
  DSDIAGNOSTICO               VARCHAR2(1000 BYTE),
  OBSUSUARIO                  VARCHAR2(4000 BYTE),
  QTREITERACAO                NUMBER,
  QTREABERTURA                NUMBER,
  QTARQUIVOSANEXO             NUMBER,
  NMUSUARIO                   VARCHAR2(255 BYTE),
  NRCPFCNPJUSUARIO            VARCHAR2(255 BYTE),
  NRTELEFONEUSUARIO           VARCHAR2(255 BYTE),
  DSENDERECOUSUARIO           VARCHAR2(800 BYTE),
  DSBAIRROUSUARIO             VARCHAR2(255 BYTE),
  DSCIDADEUSUARIO             VARCHAR2(255 BYTE),
  SGUFUSUARIO                 VARCHAR2(255 BYTE),
  NRCEPUSUARIO                VARCHAR2(255 BYTE),
  DSEMAIL                     VARCHAR2(255 BYTE),  
  NRPROTOCOLO				  VARCHAR2(255 BYTE),
  IDUSUARIOALTERACAO          NUMBER,
  DTULTIMAALTERACAO           DATE                      DEFAULT sysdate               NOT NULL
)
tablespace tbs_dados
;


COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.IDATENDIMENTOANATEL IS 'sequence da tabela';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRSOLICITACAO IS 'identificador interno da solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.IDATENDIMENTOANATELARQUIVO IS 'campo faz referencia à tabela atendimento.atendimentoanatelarquivo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSTIPOATENDIMENTOANATEL IS 'tipo de atendimento anatel';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSSERVICO IS 'descrição do serviço';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSMODALIDADE IS 'modalidade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSMOTIVO IS 'motivo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSSUBMOTIVO IS 'submotivo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSCATEGORIA IS 'categoria';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSSUBCATEGORIA IS 'subcategoria';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.IDATENDIMENTO IS 'campo faz referencia à tabela atendimento.atendimento';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.IDATENDIMENTOPROTOCOLO IS 'campo faz referencia à tabela atendimento.atendimentoprotocolo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRTELEFONEPROBLEMA IS 'número do telefone que está com problema do cliente. composto por ddd e número';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRCPFCNPJASSINANTE IS 'cpf/cnpj do assinante';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NMASSINANTE IS 'nome do assinante';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DTREGISTRO IS 'data/hora em que a solicitação foi registrada';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.CDSITUACAO IS 'identificador interno da situação da solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSSITUACAO IS 'descrição da situação da solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.CDVIARESPOSTA IS 'identificador interno do canal de resposta preferido pelo usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSVIARESPOSTA IS 'descrição do canal de resposta (da solicitação) preferido pelo usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSDIAGNOSTICO IS 'resumo da informação prestadora pelo usuário sobre sua solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.OBSUSUARIO IS 'observação realizada pelo usuário quanto à solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.QTREITERACAO IS 'quantidade de reiterações efetuadas para a solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.QTREABERTURA IS 'quantidade de reaberturas efetuadas para a solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.QTARQUIVOSANEXO IS 'quantidade de arquivos anexos à solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NMUSUARIO IS 'nome do usuário que realizou a solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRCPFCNPJUSUARIO IS 'número cpf ou cnpj do usuário cliente';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRTELEFONEUSUARIO IS 'telefone do usuário. composto por ddd e número';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSENDERECOUSUARIO IS 'endereço (logradouro) do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSBAIRROUSUARIO IS 'bairro do endereço do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSCIDADEUSUARIO IS 'cidade do endereço do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.SGUFUSUARIO IS 'sigla uf do endereço do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRCEPUSUARIO IS 'CEP do endereço do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DSEMAIL IS 'endereço de correio-eletrônico do usuário';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.NRPROTOCOLO IS 'número de protocolo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.IDUSUARIOALTERACAO IS 'usuário de alteração';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATEL.DTULTIMAALTERACAO IS 'data de última alteração';

CREATE UNIQUE INDEX ATENDIMENTO.ATENDIMENTOANATELPK ON ATENDIMENTO.ATENDIMENTOANATEL
(IDATENDIMENTOANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX ATENDIMENTO.ATENDIMENTOANATELAK1 ON ATENDIMENTO.ATENDIMENTOANATEL
(NRSOLICITACAO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX ATENDIMENTO.ATENDIMENTOANATELAK2 ON ATENDIMENTO.ATENDIMENTOANATEL
(IDATENDIMENTO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX ATENDIMENTO.ATENDIMENTOANATELAK3 ON ATENDIMENTO.ATENDIMENTOANATEL
(IDATENDIMENTOPROTOCOLO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



ALTER TABLE ATENDIMENTO.ATENDIMENTOANATEL ADD (
  CONSTRAINT ATENDIMENTOANATELPK
 PRIMARY KEY
 (IDATENDIMENTOANATEL)
    USING INDEX 
    TABLESPACE TBS_INDICES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
                  
 
ALTER TABLE ATENDIMENTO.ATENDIMENTOANATEL ADD (
CONSTRAINT ATENDIMENTOANATELFK1 FOREIGN KEY (IDATENDIMENTOANATELARQUIVO) 
REFERENCES ATENDIMENTO.ATENDIMENTOANATELARQUIVO (IDATENDIMENTOANATELARQUIVO));
 
 ALTER TABLE ATENDIMENTO.ATENDIMENTOANATEL ADD (
  CONSTRAINT ATENDIMENTOANATELFK2
 FOREIGN KEY (IDATENDIMENTO) 
 REFERENCES ATENDIMENTO.ATENDIMENTO (IDATENDIMENTO));
 
 ALTER TABLE ATENDIMENTO.ATENDIMENTOANATEL ADD (
  CONSTRAINT ATENDIMENTOANATELFK3
 FOREIGN KEY (IDATENDIMENTOPROTOCOLO) 
 REFERENCES ATENDIMENTO.ATENDIMENTOPROTOCOLO (IDATENDIMENTOPROTOCOLO)); 
 
 
 
spool off
set echo off
set timi off