set timi on
set echo on
spool A_L1123.log

CREATE TABLE ATENDIMENTO.ATENDIMENTOANATELDADOS
(
  IDATENDIMENTOANATEL                NUMBER                        NOT NULL,
  NRTIPODADOS                        NUMBER(10),
  DSDADOS                            VARCHAR2(100 BYTE),
  NMTIPODADOS                        VARCHAR2(150 BYTE),
  IDUSUARIOALTERACAO                 NUMBER,
  DTULTIMAALTERACAO                  DATE                      DEFAULT sysdate               NOT NULL
)
tablespace tbs_dados
;


COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELDADOS.IDATENDIMENTOANATEL IS 'fk que faz referencia a tabela atendimento.atendimentoanatel';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELDADOS.NRTIPODADOS IS 'identificador em uma lista de tipo de dados';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELDADOS.DSDADOS IS 'descrição em uma lista de tipo de dados';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELDADOS.NMTIPODADOS IS 'descrição conforme tabela de domínio abaixo tipo dado complementar';


ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELDADOS ADD (
  CONSTRAINT ATENDIMENTOANATELDADOSFK1 
 FOREIGN KEY (IDATENDIMENTOANATEL) 
 REFERENCES ATENDIMENTO.ATENDIMENTOANATEL (IDATENDIMENTOANATEL));

spool off
set echo off
set timi off