set timi on
set echo on
spool A_L1115.log

ALTER TABLE 
   ATENDIMENTO.ATENDIMENTOPRIORIZACAO
ADD 
   (
      INANATEL            NUMBER DEFAULT 0,
      IDATENDIMENTOANATEL NUMBER
   );

CREATE INDEX ATENDIMENTO.ATENDIMENTOPRIORIZACAOIE15 ON ATENDIMENTO.ATENDIMENTOPRIORIZACAO
(INANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX ATENDIMENTO.ATENDIMENTOPRIORIZACAOIE16 ON ATENDIMENTO.ATENDIMENTOPRIORIZACAO
(IDATENDIMENTOANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOPRIORIZACAO.INANATEL IS 'indica se o atendimento é da anatel com valor 1';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOPRIORIZACAO.IDATENDIMENTOANATEL IS 'chave para atendimento.atendimentoanatel';







spool off
set echo off
set timi off
