set timi on
set echo on
spool A_L1132.log

CREATE TABLE ATENDIMENTO.ATENDIMENTOANATELATIVIDADE
(
  IDATENDIMENTOANATELATV        NUMBER                        NOT NULL,
  IDATENDIMENTOANATEL           NUMBER                        NOT NULL,
  NRATIVIDADE					NUMBER, 
  SGSOLICITANTE					VARCHAR2(255 BYTE),
  ORGAOSOLICITANTE 				VARCHAR2(255 BYTE),
  USUARIOSOLICITANTE			VARCHAR2(255 BYTE),
  DESCRICAO						VARCHAR2(1000 BYTE),  
  DTESTIMADA					DATE,
  DTINICIAL						DATE,
  IDUSUARIOALTERACAO			NUMBER,
  DTULTIMAATUALIZACAO			DATE
)
tablespace tbs_dados
;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.IDATENDIMENTOANATELATV IS 'chave primaria da tabela';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.IDATENDIMENTOANATEL IS 'fk que faz referencia a tabela atendimento.atendimentoanatel';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.NRATIVIDADE IS 'Número da atividade criada para a solicitação';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.SGSOLICITANTE IS 'Sigla do órgão da Anatel que solicitou a atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.ORGAOSOLICITANTE IS 'Nome do órgão da Anatel que solicitou a atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.USUARIOSOLICITANTE IS 'Nome do solicitante do órgão da Anatel que solicitou a atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.DESCRICAO IS 'Descrição detalhada da atividade solicitada';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.DTESTIMADA IS 'Data estimada para a conclusão da atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.DTINICIAL IS 'Data de solicitação da atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.IDUSUARIOALTERACAO IS 'usuário do vivonet que atualizou o registro';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATIVIDADE.DTULTIMAATUALIZACAO IS 'data de ultima atualização no vivonet';

CREATE UNIQUE INDEX ATENDIMENTO.ATDANATELATIVIDADEPK ON ATENDIMENTO.ATENDIMENTOANATELATIVIDADE
(IDATENDIMENTOANATELATV)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX ATENDIMENTO.ATDANATELATIVIDADEAK1 ON ATENDIMENTO.ATENDIMENTOANATELATIVIDADE
(IDATENDIMENTOANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELATIVIDADE ADD (
  CONSTRAINT ATDANATELATIVIDADEPK
 PRIMARY KEY
 (IDATENDIMENTOANATELATV)
    USING INDEX 
    TABLESPACE TBS_INDICES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELATIVIDADE ADD (
  CONSTRAINT ATDANATELATIVIDADEFK1 
 FOREIGN KEY (IDATENDIMENTOANATEL) 
 REFERENCES ATENDIMENTO.ATENDIMENTOANATEL (IDATENDIMENTOANATEL));



spool off
set echo off
set timi off