set timi on
set echo on
spool A_L1136.log

ALTER TABLE 
   INFRA.ARQUIVOFUNCIONALIDADE
ADD 
   (
      IDATENDIMENTOANATELARQUIVO  NUMBER
   );

CREATE INDEX INFRA.ARQUIVOFUNCIONALIDADEIE1 ON INFRA.ARQUIVOFUNCIONALIDADE
(IDATENDIMENTOANATELARQUIVO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX INFRA.ARQUIVOFUNCIONALIDADEIE2 ON INFRA.ARQUIVOFUNCIONALIDADE
(NMARQUIVO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

COMMENT ON COLUMN INFRA.ARQUIVOFUNCIONALIDADE.IDATENDIMENTOANATELARQUIVO IS 'chave para tabela atendimento.atendimentoanatelarquivo';



spool off
set echo off
set timi off
