set timi on
set echo on
spool A_L1125.log

CREATE TABLE ATENDIMENTO.ATENDIMENTOANATELHISTORICO
(
  IDATENDIMENTOANATEL           NUMBER                        NOT NULL,
  DSDETALHAMENTO                VARCHAR2(4000 BYTE),
  DSEVENTO                      VARCHAR2(100 BYTE),
  DTHISTORICO                   DATE                          NOT NULL
)
tablespace tbs_dados
;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELHISTORICO.IDATENDIMENTOANATEL IS 'fk que faz referencia a tabela atendimento.atendimentoanatel';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELHISTORICO.DSDETALHAMENTO IS 'descrição do histórico';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELHISTORICO.DSEVENTO IS 'descrição do evento';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELHISTORICO.DTHISTORICO IS 'data de registro de histórico';


CREATE UNIQUE INDEX ATENDIMENTO.ATENDIMENTOANATELHISTORICOAK1 ON ATENDIMENTO.ATENDIMENTOANATELHISTORICO
(IDATENDIMENTOANATEL,DTHISTORICO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELHISTORICO ADD (
  CONSTRAINT ATENDIMENTOANATELHISTORICOFK1 
 FOREIGN KEY (IDATENDIMENTOANATEL) 
 REFERENCES ATENDIMENTO.ATENDIMENTOANATEL (IDATENDIMENTOANATEL));

spool off
set echo off
set timi off