set timi on
set echo on
spool A_L1119.log

ALTER TABLE 
   ATENDIMENTO.ATENDIMENTO
ADD 
   (
      INANATEL            NUMBER DEFAULT 0,
      IDATENDIMENTOANATEL NUMBER
   );

CREATE INDEX ATENDIMENTO.ATENDIMENTOIE14 ON ATENDIMENTO.ATENDIMENTO
(INANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX ATENDIMENTO.ATENDIMENTOIE15 ON ATENDIMENTO.ATENDIMENTO
(IDATENDIMENTOANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTO.INANATEL IS 'indica se o atendimento é da anatel com valor 1';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTO.IDATENDIMENTOANATEL IS 'chave para atendimento.atendimentoanatel';




spool off
set echo off
set timi off