set timi on
set echo on
spool A_L1133.log

CREATE TABLE ATENDIMENTO.ATENDIMENTOANATELATVANEXO
(
  IDATENDIMENTOANATELATV                 NUMBER                        NOT NULL,  
  DSANEXO                       		 VARCHAR2(500 BYTE),
  DTEXCLUSAO							 DATE,
  IDUSUARIOALTERACAO					 NUMBER,
  DTULTIMAATUALIZACAO					 DATE
)
tablespace tbs_dados
;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATVANEXO.IDATENDIMENTOANATELATV IS 'fk que faz referencia a tabela atendimento.atendimentoanatelatividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATVANEXO.DSANEXO IS 'nome do anexo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATVANEXO.DTEXCLUSAO IS 'data de exclusão do anexo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATVANEXO.IDUSUARIOALTERACAO IS 'usuário do vivonet que atualizou o registro';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELATVANEXO.DTULTIMAATUALIZACAO IS 'data de ultima atualização no vivonet';


CREATE UNIQUE INDEX ATENDIMENTO.ATDANATELATVANEXOAK1 ON ATENDIMENTO.ATENDIMENTOANATELATVANEXO
(IDATENDIMENTOANATELATV, DSANEXO)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELATVANEXO ADD (
  CONSTRAINT ATDANATELATVANEXOFK1 
 FOREIGN KEY (IDATENDIMENTOANATELATV) 
 REFERENCES ATENDIMENTO.ATENDIMENTOANATELATIVIDADE (IDATENDIMENTOANATELATV));



spool off
set echo off
set timi off