set timi on
set echo on
spool A_L1174.log


INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(1,839,'VIVO - PB',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(2,278,'VIVO - AC',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(3,836,'VIVO - AL',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(4,288,'VIVO - BA',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(5,835,'VIVO - CE',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(6,277,'VIVO - DF',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(7,269,'VIVO - ES',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(8,282,'VIVO - GO',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(9,281,'VIVO - MS',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(10,280,'VIVO - MT',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(11,841,'VIVO - PE',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(12,837,'VIVO - PI',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(13,270,'VIVO - RJ',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(14,838,'VIVO - RN',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(15,279,'VIVO - RO',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(16,276,'VIVO - RS',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(17,289,'VIVO - SE',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(18,266,'VIVO - SP',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(19,301,'VIVO - SC e PR',1,sysdate);

INSERT INTO APOIO.PRESTADORAANATEL 
(IDPRESTADORAANATEL, CDPRESTADORA, DSPRESTADORA, IDUSUARIOALTERACAO, DTULTIMAALTERACAO)
VALUES
(20,331,'VIVO - AM-RR-PA-AP-MA',1,sysdate);

commit;



spool off
set echo off
set timi off
