set timi on
set echo on
spool A_L1122.log

CREATE TABLE ATENDIMENTO.ATENDIMENTOANATELANEXO
(
  IDATENDIMENTOANATEL           NUMBER                        NOT NULL,
  DSANEXO                       VARCHAR2(500 BYTE),
  INANEXOANATEL					NUMBER,
  INATIVIDADE					NUMBER,
  DTEXCLUSAO					DATE,
  DTULTIMAATUALIZACAO			DATE
)
tablespace tbs_dados
;

COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.IDATENDIMENTOANATEL IS 'fk que faz referencia a tabela atendimento.atendimentoanatel';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.DSANEXO IS 'caminho do arquivo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.INANEXOANATEL IS 'indicador se é arquivo anatel ou anexado pela vivo 1 quando for anatel e 0 para vivo';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.INATIVIDADE IS 'indicador se é arquivo de anexo ou atividade';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.DTEXCLUSAO IS 'data de exclusão do arquivo pelo vivonet';
COMMENT ON COLUMN ATENDIMENTO.ATENDIMENTOANATELANEXO.DTULTIMAATUALIZACAO IS 'data de ultima atualização no vivonet';


CREATE UNIQUE INDEX ATENDIMENTO.ATENDIMENTOANATELANEXOAK1 ON ATENDIMENTO.ATENDIMENTOANATELANEXO
(IDATENDIMENTOANATEL,DSANEXO,INATIVIDADE)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE ATENDIMENTO.ATENDIMENTOANATELANEXO ADD (
  CONSTRAINT ATENDIMENTOANATELANEXOFK1 
 FOREIGN KEY (IDATENDIMENTOANATEL) 
 REFERENCES ATENDIMENTO.ATENDIMENTOANATEL (IDATENDIMENTOANATEL));



spool off
set echo off
set timi off