set timi on
set echo on
spool A_L1175.log

DROP TABLE APOIO.ATENDIMENTOEVENTOANATEL CASCADE CONSTRAINTS;

CREATE TABLE APOIO.ATENDIMENTOEVENTOANATEL
(
  IDEVENTOANATEL       NUMBER                   NOT NULL,
  SGEVENTOANATEL       VARCHAR2(2 BYTE)         NOT NULL,
  DSEVENTOANATEL       VARCHAR2(200 BYTE),
  TIPOEVENTO           VARCHAR2(1 BYTE)         NOT NULL,
  IDUSUARIOALTERACAO   NUMBER                   NOT NULL,
  DTULTIMAATUALIZACAO  DATE                     NOT NULL
)
TABLESPACE TBS_DADOS
;
           


COMMENT ON TABLE APOIO.ATENDIMENTOEVENTOANATEL IS 'Tabela de eventos utilizados no atendimento de um processo anatel .';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.IDEVENTOANATEL IS 'Chave de acesso primaria (nao se repete) para acessar as informacoes dos Eventos';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.SGEVENTOANATEL IS 'Sigla do evento';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.DSEVENTOANATEL IS 'Descricao detalhada do evento';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.TIPOEVENTO IS 'Indica o tipo de evento se e Atividade ou Solicitacao';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.IDUSUARIOALTERACAO IS 'ID do Usuario utilizado para Inclusao e Alteracao do Registro em cada tabela, conforme solicitacao VIVO';

COMMENT ON COLUMN APOIO.ATENDIMENTOEVENTOANATEL.DTULTIMAATUALIZACAO IS 'Data da ultima atualizacao do registro; sendo atualizada na Inclusao ou na alteracao; conforme solicitacao da VIVO';



CREATE UNIQUE INDEX APOIO.ATENDIMENTOEVENTOANATELPK ON APOIO.ATENDIMENTOEVENTOANATEL
(IDEVENTOANATEL)
LOGGING
TABLESPACE TBS_DADOS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE APOIO.ATENDIMENTOEVENTOANATEL ADD (
  CONSTRAINT ATENDIMENTOEVENTOANATELCK
 CHECK (TIPOEVENTO IN('A','S')),
  CONSTRAINT ATENDIMENTOEVENTOANATELPK
 UNIQUE (IDEVENTOANATEL)
    USING INDEX 
    TABLESPACE TBS_DADOS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




spool off
set echo off
set timi off
