set timi on
set echo on
spool A_L1173.log


CREATE TABLE APOIO.PRESTADORAANATEL
(
  IDPRESTADORAANATEL          NUMBER                        NOT NULL,
  CDPRESTADORA                NUMBER,
  DSPRESTADORA                VARCHAR2(255 BYTE),
  IDUSUARIOALTERACAO          NUMBER,
  DTULTIMAALTERACAO           DATE                      DEFAULT sysdate               NOT NULL
)
tablespace tbs_dados
;


COMMENT ON COLUMN APOIO.PRESTADORAANATEL.IDPRESTADORAANATEL IS 'sequence da tabela';
COMMENT ON COLUMN APOIO.PRESTADORAANATEL.CDPRESTADORA IS 'CÓDIGO DA PRESTADORA ANATEL';
COMMENT ON COLUMN APOIO.PRESTADORAANATEL.DSPRESTADORA IS 'DESCRIÇÃO DA PRESTADORA ANATEL';
COMMENT ON COLUMN APOIO.PRESTADORAANATEL.IDUSUARIOALTERACAO IS 'USUÁRIO QUE FEZ A ALTERAÇÃO';
COMMENT ON COLUMN APOIO.PRESTADORAANATEL.DTULTIMAALTERACAO IS 'DATA DE ULTIMA ATUALIZACAO DO REGISTRO';


CREATE UNIQUE INDEX APOIO.PRESTADORAANATELPK ON APOIO.PRESTADORAANATEL
(IDPRESTADORAANATEL)
LOGGING
TABLESPACE TBS_INDICES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE APOIO.PRESTADORAANATEL ADD (
  CONSTRAINT PRESTADORAANATELPK
 PRIMARY KEY
 (IDPRESTADORAANATEL)
    USING INDEX 
    TABLESPACE TBS_INDICES
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
   
 
spool off
set echo off
set timi off