#include "../include/classdef.h"

int usrID=-1;

void CheckUsr()
{
	if(usrID<0)
		throw new TuxBasicSvcException("00E9999","Invalid UserID");
}
GrupoRetornoWFCTI::GrupoRetornoWFCTI(DOMNode*dom,XMLGen*xml):pdom(dom),pxml(xml)
{
   ULOG_START("GrupoRetornoWFCTI::GrupoRetornoWFCTI()");
   
	CheckUsr();
	memset(&grwfcti,0,sizeof(grwfcti));
	grwfcti.idusuarioalteracao=usrID;
	POPULATE_INT(pdom,IDGRUPORETORNOWFCTI,grwfcti.idgruporetornowfcti);
	POPULATE_INT(pdom,IDRETORNOWFCTI,grwfcti.idretornowfcti);
	POPULATE_INT(pdom,IDUSUARIOGRUPO,grwfcti.idusuariogrupo);
	POPULATE_INT(pdom,INPADRAO,grwfcti.inpadrao);
	
	ULOG_END("GrupoRetornoWFCTI::GrupoRetornoWFCTI()");
}

BEGIN_DECLARE_ROUTER_PARM(SetUser)
	ADD_ROUTER_FUNCTION_ITEM(AC_INTEGER)
END_DECLARE_ROUTER_PARM
BEGIN_DECLARE_ROUTER_PARM(InsertWFGRetWFCTI)
	ADD_ROUTER_FUNCTION_ITEM(AC_DOMNODE)
END_DECLARE_ROUTER_PARM
BEGIN_DECLARE_ROUTER_PARM(DeleteWFGRetWFCTI)
	ADD_ROUTER_FUNCTION_ITEM(AC_DOMNODE)
END_DECLARE_ROUTER_PARM
BEGIN_DECLARE_ROUTER_PARM(DeleteWFGRetWFCTIByID)
	ADD_ROUTER_FUNCTION_ITEM(AC_DOMNODE)
END_DECLARE_ROUTER_PARM
BEGIN_DECLARE_ROUTER_PARM(UpdateWFGRetWFCTI)
	ADD_ROUTER_FUNCTION_ITEM(AC_DOMNODE)
END_DECLARE_ROUTER_PARM
BEGIN_DECLARE_ROUTER_PARM(SelectByRetWFCTI)
	ADD_ROUTER_FUNCTION_ITEM(AC_DOMNODE)
END_DECLARE_ROUTER_PARM

DECLARE_RETURN_TYPE(InsertWFGRetWFCTI,AC_XMLGEN)
DECLARE_RETURN_TYPE(DeleteWFGRetWFCTI,AC_XMLGEN)
DECLARE_RETURN_TYPE(DeleteWFGRetWFCTIByID,AC_XMLGEN)
DECLARE_RETURN_TYPE(UpdateWFGRetWFCTI,AC_XMLGEN)
DECLARE_RETURN_TYPE(SelectByRetWFCTI,AC_XMLGEN)
DECLARE_NO_RETURN(SetUser)

BEGIN_DECLARE_ROUTER_INTERF(SetUser,1)
	usrID=pSetUser[0].accum->var.i32;
END_DECLARE_ROUTER_INTERF
BEGIN_DECLARE_ROUTER_INTERF(InsertWFGRetWFCTI,1)
	GrupoRetornoWFCTI grwfcti(pInsertWFGRetWFCTI[0].accum->var.dom->RetrieveDOM(),ac->var.xml);
	grwfcti.Insert();
END_DECLARE_ROUTER_INTERF
BEGIN_DECLARE_ROUTER_INTERF(DeleteWFGRetWFCTI,1)
	GrupoRetornoWFCTI grwfcti(pDeleteWFGRetWFCTI[0].accum->var.dom->RetrieveDOM(),ac->var.xml);
	grwfcti.Delete();
END_DECLARE_ROUTER_INTERF
BEGIN_DECLARE_ROUTER_INTERF(DeleteWFGRetWFCTIByID,1)
	GrupoRetornoWFCTI grwfcti(pDeleteWFGRetWFCTIByID[0].accum->var.dom->RetrieveDOM(),ac->var.xml);
	grwfcti.DeleteByID();
END_DECLARE_ROUTER_INTERF
BEGIN_DECLARE_ROUTER_INTERF(UpdateWFGRetWFCTI,1)
	GrupoRetornoWFCTI grwfcti(pUpdateWFGRetWFCTI[0].accum->var.dom->RetrieveDOM(),ac->var.xml);
	grwfcti.Update();
END_DECLARE_ROUTER_INTERF
BEGIN_DECLARE_ROUTER_INTERF(SelectByRetWFCTI,1)
	GrupoRetornoWFCTI grwfcti(pSelectByRetWFCTI[0].accum->var.dom->RetrieveDOM(),ac->var.xml);
	grwfcti.SelectGroupsByRetWFCTI();
END_DECLARE_ROUTER_INTERF

