SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
    V_DATA_CRITERIO VARCHAR2(255);
	V_ROWCOUNT NUMBER;
BEGIN

	V_DATA_CRITERIO := '&1';
	
	/*
		Verifica todas as linhas PRE que estao na tabela CUSTOMER.PROGRAMARELACIONAMENTOPRECTRL com a data
		DTEXCLUSAO = V_DATA_CRITERIO (parametro de entrada) e exclui da tabela do DW CUSTOMER.CARGAPROGRAMARELACIONAMENTO
	*/


	DELETE FROM CUSTOMER.CARGAPROGRAMARELACIONAMENTO CPR
	WHERE EXISTS
	(
		SELECT /*+ PARALLEL (64) */ 1
		  FROM CUSTOMER.PROGRAMARELACIONAMENTOPRECTRL PRPRE
		 WHERE TRUNC(PRPRE.DTEXCLUSAO) = TO_DATE(V_DATA_CRITERIO, 'DD/MM/YYYY')
		   AND PRPRE.NRLINHA = CPR.NRTELEFONE
		   AND PRPRE.IDPESSOAENDERECO = CPR.NRDOCUMENTO
	);
	V_ROWCOUNT:=SQL%ROWCOUNT;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas excluidas EXCLUSAO PRE: '||V_ROWCOUNT);
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
