SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
    V_DATA_CRITERIO VARCHAR2(255);
	V_ROWCOUNT NUMBER;
BEGIN
	
	V_DATA_CRITERIO := '&1';

	/*
		Verifica todas as linhas POS que estao na tabela CUSTOMER.PROGRAMARELACIONAMENTOPOS com a data
		DTEXCLUSAO = V_DATA_CRITERIO (parametro de entrada) e inclui na tabela do DW CUSTOMER.CARGAPROGRAMARELACIONAMENTO
		Pode ser que haja alguma alteracao nas datas e a linha ja esteja no DW (CUSTOMER.CARGAPROGRAMARELACIONAMENTO), neste
		caso ela nao sera inserida
	*/
	
	INSERT /*+ APPEND */ INTO CUSTOMER.CARGAPROGRAMARELACIONAMENTO
		(
			NRDOCUMENTO,
			NRTELEFONE,
			INPR,
			DTCADASTROPR,
			DTATUALIZACAOPR,
			INCADASTROMANUAL,
			NMLOGINATUALIZACAOPR,
			IDSISTEMAORIGEMPR,
			NRLINHACONTATO,
			NMLOGINATUALIZACAOLC,
			IDSISTEMAATUALIZACAOLC
		)
	SELECT /*+ PARALLEL (64) */
		   D.NRDOCUMENTO,
		   PLH.CDAREAREGISTRO || PLH.NRLINHA AS NRTELEFONE,
		   1,
		   SAD.DTCADASTRO,
		   SAD.DTULTIMAATUALIZACAO,
		   0,
		   'vnet',
		   7,
		   NULL,
		   NULL,
		   NULL
	  FROM (
			SELECT
				   PRPOS.NRDOCUMENTO, 
				   PRPOS.DTCADASTRO,
				   PRPOS.DTULTIMAATUALIZACAO       
			  FROM CUSTOMER.PROGRAMARELACIONAMENTOPOS PRPOS
			 WHERE TRUNC(PRPOS.DTULTIMAATUALIZACAO) = TO_DATE(V_DATA_CRITERIO, 'DD/MM/YYYY')
			   AND PRPOS.DTEXCLUSAO IS NULL
			   AND ( PRPOS.NRDOCUMENTO != PRPOS.NRLINHASOLICITANTE OR PRPOS.NRLINHASOLICITANTE IS NULL )
		   ) SAD,
		   CUSTOMER.DOCUMENTO D,
		   CUSTOMER.PESSOADOCUMENTO PD,
		   CUSTOMER.PESSOA P,
		   CUSTOMER.PESSOADEPARA PDP,
		   CUSTOMER.PESSOALINHAHISTORICO PLH,
		   LINHA.LINHATELEFONICA LT
	 WHERE SAD.NRDOCUMENTO = D.NRDOCUMENTO
	   AND D.IDDOCUMENTO = PD.IDDOCUMENTO
	   AND PD.IDPESSOA = P.IDPESSOA
	   AND P.IDPESSOA = PDP.IDPESSOA
	   AND PDP.IDPESSOADEPARA = PLH.IDPESSOADEPARA
	   AND PLH.IDLINHATELEFONICA = LT.IDLINHATELEFONICA
	   AND D.IDTIPODOCUMENTO IN ( SELECT IDTIPODOCUMENTO FROM APOIO.TIPODOCUMENTO WHERE SGCLASSIFICACAO = 'CPF' ) -- Apenas os varios tipos de CPF
	   AND PLH.IDTIPORELACIONAMENTO = 2 -- Clients
	   AND LT.IDSISTEMAORIGEM = 1 -- Atlys
	   AND NOT EXISTS (SELECT 1 FROM CUSTOMER.CARGAPROGRAMARELACIONAMENTO C WHERE D.NRDOCUMENTO = C.NRDOCUMENTO  AND PLH.CDAREAREGISTRO || PLH.NRLINHA = C.NRTELEFONE )
	   AND PLH.NRLINHA IS NOT NULL;

	V_ROWCOUNT:=SQL%ROWCOUNT;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inluidas INCLUSAO POS: '||V_ROWCOUNT);
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
