SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
    V_DATA_CRITERIO VARCHAR2(255);
	V_ROWCOUNT NUMBER;
BEGIN
	
	V_DATA_CRITERIO := '&1';
	
	/*
		Verifica todas as linhas POS que estao na tabela CUSTOMER.PROGRAMARELACIONAMENTOPOS com a data
		DTEXCLUSAO = V_DATA_CRITERIO (parametro de entrada) e exclui da tabela do DW CUSTOMER.CARGAPROGRAMARELACIONAMENTO
	*/

	DELETE FROM CUSTOMER.CARGAPROGRAMARELACIONAMENTO CPREL
    WHERE EXISTS 
    (
        SELECT /*+ PARALLEL (64) */
               1
          FROM (
                SELECT
                       PRPOS.NRDOCUMENTO, 
                       PRPOS.DTCADASTRO,
                       PRPOS.DTULTIMAATUALIZACAO       
                  FROM CUSTOMER.PROGRAMARELACIONAMENTOPOS PRPOS
                 WHERE TRUNC(PRPOS.DTEXCLUSAO) = TO_DATE(V_DATA_CRITERIO, 'DD/MM/YYYY')
                   AND ( PRPOS.NRDOCUMENTO != PRPOS.NRLINHASOLICITANTE OR PRPOS.NRLINHASOLICITANTE IS NULL )
               ) SAD,
               CUSTOMER.DOCUMENTO D,
               CUSTOMER.PESSOADOCUMENTO PD,
               CUSTOMER.PESSOA P,
               CUSTOMER.PESSOADEPARA PDP,
               CUSTOMER.PESSOALINHAHISTORICO PLH,
               LINHA.LINHATELEFONICA LT
         WHERE SAD.NRDOCUMENTO = D.NRDOCUMENTO
           AND D.IDDOCUMENTO = PD.IDDOCUMENTO
           AND PD.IDPESSOA = P.IDPESSOA
           AND P.IDPESSOA = PDP.IDPESSOA
           AND PDP.IDPESSOADEPARA = PLH.IDPESSOADEPARA
           AND PLH.IDLINHATELEFONICA = LT.IDLINHATELEFONICA
           AND D.IDTIPODOCUMENTO IN ( SELECT IDTIPODOCUMENTO FROM APOIO.TIPODOCUMENTO WHERE SGCLASSIFICACAO = 'CPF' ) -- Apenas os varios tipos de CPF
           AND PLH.IDTIPORELACIONAMENTO = 2 -- Apenas clientes
           AND LT.IDSISTEMAORIGEM = 1 -- Atlys
           AND CPREL.NRDOCUMENTO = SAD.NRDOCUMENTO
           AND CPREL.NRTELEFONE = (PLH.CDAREAREGISTRO || PLH.NRLINHA)
       );
	V_ROWCOUNT:=SQL%ROWCOUNT;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas excluidas EXCLUSAO POS: '||V_ROWCOUNT);
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
