//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 02:38:35 PM BRST 
//


package br.com.indrasistemas.vivoservices.atendimento.palitagem.tuxgateway.saida;


/**
 * Java content class for AtendimentoVOType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/vivoservices/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/atendimento/palitagem/tuxgateway/saida/regPalitageFoOUT.xsd line 33)
 * <p>
 * <pre>
 * &lt;complexType name="AtendimentoVOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nrProtocolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idAtendimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AtendimentoVOType {


    /**
     * Gets the value of the nrProtocolo property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrProtocolo();

    /**
     * Sets the value of the nrProtocolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrProtocolo(java.lang.String value);

    /**
     * Gets the value of the idAtendimento property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdAtendimento();

    /**
     * Sets the value of the idAtendimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdAtendimento(java.lang.String value);

}
