//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.16 at 11:31:39 AM BRST 
//


package br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl;

public class ListaBonusVOTypeImpl implements br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _MsgRetorno;
    protected com.sun.xml.bind.util.ListImpl _Ofertas;
    protected java.lang.String _CdRetorno;
    public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.class);
    }

    public java.lang.String getMsgRetorno() {
        return _MsgRetorno;
    }

    public void setMsgRetorno(java.lang.String value) {
        _MsgRetorno = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getOfertas() {
        if (_Ofertas == null) {
            _Ofertas = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Ofertas;
    }

    public java.util.List getOfertas() {
        return _getOfertas();
    }

    public java.lang.String getCdRetorno() {
        return _CdRetorno;
    }

    public void setCdRetorno(java.lang.String value) {
        _CdRetorno = value;
    }

    public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
        return new br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Ofertas == null)? 0 :_Ofertas.size());
        while (idx2 != len2) {
            context.startElement("", "Ofertas");
            int idx_0 = idx2;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Ofertas.get(idx_0 ++)), "Ofertas");
            context.endNamespaceDecls();
            int idx_1 = idx2;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Ofertas.get(idx_1 ++)), "Ofertas");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Ofertas.get(idx2 ++)), "Ofertas");
            context.endElement();
        }
        if (_CdRetorno!= null) {
            context.startElement("", "cdRetorno");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CdRetorno), "CdRetorno");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_MsgRetorno!= null) {
            context.startElement("", "msgRetorno");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _MsgRetorno), "MsgRetorno");
            } catch (java.lang.Exception e) {
                br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Ofertas == null)? 0 :_Ofertas.size());
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Ofertas == null)? 0 :_Ofertas.size());
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000"
+"\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\'com.s"
+"un.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001f"
+"Lcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.Eleme"
+"ntExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModel"
+"q\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\rp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000epp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\tq\u0000~\u0000\rpsr\u0000 c"
+"om.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tname"
+"Classq\u0000~\u0000\u000fxq\u0000~\u0000\u0003q\u0000~\u0000\rpsr\u00002com.sun.msv.grammar.Expression$Any"
+"StringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\f\u0001psr\u0000 com.sun.msv.gra"
+"mmar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClas"
+"s\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$EpsilonExpr"
+"ession\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u001apsr\u0000#com.sun.msv.grammar.SimpleN"
+"ameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnames"
+"paceURIq\u0000~\u0000!xq\u0000~\u0000\u001ct\u0000mbr.com.indrasistemas.vivoservices.atend"
+"imento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.O"
+"fertasTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~"
+"\u0000\u0007ppsq\u0000~\u0000\u0016q\u0000~\u0000\rpsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000"
+"\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000"
+"\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.dataty"
+"pe.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Buil"
+"tinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Concret"
+"eType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000!L\u0000\btypeNameq\u0000~\u0000!L\u0000\nwhiteSpacet"
+"\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://"
+"www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xs"
+"d.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.dat"
+"atype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.gr"
+"ammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom"
+".sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000!L\u0000\fnames"
+"paceURIq\u0000~\u0000!xpq\u0000~\u00002q\u0000~\u00001sq\u0000~\u0000 t\u0000\u0004typet\u0000)http://www.w3.org/20"
+"01/XMLSchema-instanceq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0007Ofertast\u0000\u0000q\u0000~\u0000\u001fsq\u0000~\u0000\u0007ppsq"
+"\u0000~\u0000\u000eq\u0000~\u0000\rp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\'q\u0000~\u0000\rpsr\u0000#com.sun.msv.datatype.xsd."
+"StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000,q\u0000~\u00001t\u0000\u0006stringsr\u0000"
+"5com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00004\u0001q\u0000~\u00007sq\u0000~\u00008q\u0000~\u0000Fq\u0000~\u00001sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0016q\u0000~\u0000\rpq\u0000~\u0000*q\u0000"
+"~\u0000:q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\tcdRetornoq\u0000~\u0000?q\u0000~\u0000\u001fsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u000eq\u0000~\u0000\rp\u0000sq\u0000"
+"~\u0000\u0000ppq\u0000~\u0000Csq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0016q\u0000~\u0000\rpq\u0000~\u0000*q\u0000~\u0000:q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\nmsgRet"
+"ornoq\u0000~\u0000?q\u0000~\u0000\u001fsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedH"
+"ash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef"
+"\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/gramm"
+"ar/ExpressionPool;xp\u0000\u0000\u0000\u000e\u0001pq\u0000~\u0000\u000bq\u0000~\u0000\bq\u0000~\u0000\u0015q\u0000~\u0000\u0012q\u0000~\u0000\u0006q\u0000~\u0000Bq\u0000~\u0000"
+"Pq\u0000~\u0000@q\u0000~\u0000Nq\u0000~\u0000%q\u0000~\u0000Jq\u0000~\u0000Qq\u0000~\u0000\u0014q\u0000~\u0000\u0005x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public static class OfertasTypeImpl implements br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.OfertasType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
    {

        protected java.lang.String _Tarifa;
        protected java.lang.String _Codigo;
        protected java.lang.String _Validade;
        protected java.lang.String _Grupo;
        public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.OfertasType.class);
        }

        public java.lang.String getTarifa() {
            return _Tarifa;
        }

        public void setTarifa(java.lang.String value) {
            _Tarifa = value;
        }

        public java.lang.String getCodigo() {
            return _Codigo;
        }

        public void setCodigo(java.lang.String value) {
            _Codigo = value;
        }

        public java.lang.String getValidade() {
            return _Validade;
        }

        public void setValidade(java.lang.String value) {
            _Validade = value;
        }

        public java.lang.String getGrupo() {
            return _Grupo;
        }

        public void setGrupo(java.lang.String value) {
            _Grupo = value;
        }

        public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            return new br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            if (_Grupo!= null) {
                context.startElement("", "grupo");
                if (_Grupo == null) {
                    context.getNamespaceContext().declareNamespace("http://www.w3.org/2001/XMLSchema-instance", null, true);
                }
                context.endNamespaceDecls();
                if (_Grupo == null) {
                    context.startAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                    try {
                        context.text("true", "Grupo");
                    } catch (java.lang.Exception e) {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                    context.endAttribute();
                }
                context.endAttributes();
                if (!(_Grupo == null)) {
                    if (_Grupo instanceof java.lang.String) {
                        try {
                            context.text(((java.lang.String) _Grupo), "Grupo");
                        } catch (java.lang.Exception e) {
                            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    } else {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handleTypeMismatchError(context, this, "Grupo", _Grupo);
                    }
                }
                context.endElement();
            }
            if (_Validade!= null) {
                context.startElement("", "validade");
                if (_Validade == null) {
                    context.getNamespaceContext().declareNamespace("http://www.w3.org/2001/XMLSchema-instance", null, true);
                }
                context.endNamespaceDecls();
                if (_Validade == null) {
                    context.startAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                    try {
                        context.text("true", "Validade");
                    } catch (java.lang.Exception e) {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                    context.endAttribute();
                }
                context.endAttributes();
                if (!(_Validade == null)) {
                    if (_Validade instanceof java.lang.String) {
                        try {
                            context.text(((java.lang.String) _Validade), "Validade");
                        } catch (java.lang.Exception e) {
                            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    } else {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handleTypeMismatchError(context, this, "Validade", _Validade);
                    }
                }
                context.endElement();
            }
            if (_Codigo!= null) {
                context.startElement("", "codigo");
                if (_Codigo == null) {
                    context.getNamespaceContext().declareNamespace("http://www.w3.org/2001/XMLSchema-instance", null, true);
                }
                context.endNamespaceDecls();
                if (_Codigo == null) {
                    context.startAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                    try {
                        context.text("true", "Codigo");
                    } catch (java.lang.Exception e) {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                    context.endAttribute();
                }
                context.endAttributes();
                if (!(_Codigo == null)) {
                    if (_Codigo instanceof java.lang.String) {
                        try {
                            context.text(((java.lang.String) _Codigo), "Codigo");
                        } catch (java.lang.Exception e) {
                            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    } else {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handleTypeMismatchError(context, this, "Codigo", _Codigo);
                    }
                }
                context.endElement();
            }
            if (_Tarifa!= null) {
                context.startElement("", "tarifa");
                if (_Tarifa == null) {
                    context.getNamespaceContext().declareNamespace("http://www.w3.org/2001/XMLSchema-instance", null, true);
                }
                context.endNamespaceDecls();
                if (_Tarifa == null) {
                    context.startAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                    try {
                        context.text("true", "Tarifa");
                    } catch (java.lang.Exception e) {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                    context.endAttribute();
                }
                context.endAttributes();
                if (!(_Tarifa == null)) {
                    if (_Tarifa instanceof java.lang.String) {
                        try {
                            context.text(((java.lang.String) _Tarifa), "Tarifa");
                        } catch (java.lang.Exception e) {
                            br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                        }
                    } else {
                        br.com.indrasistemas.jaxb.impl.runtime.Util.handleTypeMismatchError(context, this, "Tarifa", _Tarifa);
                    }
                }
                context.endElement();
            }
        }

        public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public java.lang.Class getPrimaryInterface() {
            return (br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.ListaBonusVOType.OfertasType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar."
+"ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar.trex.Ele"
+"mentPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/Na"
+"meClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aigno"
+"reUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lan"
+"g.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\bppsr\u0000 com.sun.msv.gra"
+"mmar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000bxq\u0000~"
+"\u0000\u0003ppsr\u0000\u001ccom.sun.msv.grammar.ValueExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/"
+"relaxng/datatype/Datatype;L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/String"
+"Pair;L\u0000\u0005valuet\u0000\u0012Ljava/lang/Object;xq\u0000~\u0000\u0003ppsr\u0000$com.sun.msv.da"
+"tatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xs"
+"d.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.C"
+"oncreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatyp"
+"eImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeN"
+"ameq\u0000~\u0000\u001cL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpace"
+"Processor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0007booleansr\u0000"
+"5com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xpsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalName"
+"q\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000 t\u0000\u0000sq\u0000~\u0000\u000e\u0001sr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespac"
+"eURIq\u0000~\u0000\u001cxr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0003ni"
+"lt\u0000)http://www.w3.org/2001/XMLSchema-instancesq\u0000~\u0000\u0000ppsr\u0000\u001bcom"
+".sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtq\u0000~\u0000\u0014L\u0000\u0006exceptq\u0000~\u0000\u0002L"
+"\u0000\u0004nameq\u0000~\u0000\u0015xq\u0000~\u0000\u0003q\u0000~\u0000\u000fpsr\u0000#com.sun.msv.datatype.xsd.StringTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0006stringsr\u00005com.sun"
+".msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\"\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsq\u0000~\u0000$q\u0000~\u00002q\u0000~\u0000\u001fsq\u0000~\u0000\bppsq\u0000~\u0000\u0011q\u0000~\u0000\u000fpsq\u0000~\u0000.pps"
+"r\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft"
+"\u0000\u0005QNameq\u0000~\u0000#q\u0000~\u00006sq\u0000~\u0000$q\u0000~\u0000=q\u0000~\u0000\u001fsq\u0000~\u0000(t\u0000\u0004typeq\u0000~\u0000,sr\u00000com.s"
+"un.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003"
+"q\u0000~\u0000\'psq\u0000~\u0000(t\u0000\u0005grupoq\u0000~\u0000&q\u0000~\u0000Bsq\u0000~\u0000\bppsq\u0000~\u0000\nq\u0000~\u0000\u000fp\u0000sq\u0000~\u0000\bpps"
+"q\u0000~\u0000\u0011ppq\u0000~\u0000\u0017sq\u0000~\u0000(q\u0000~\u0000+q\u0000~\u0000,sq\u0000~\u0000\u0000ppq\u0000~\u0000/sq\u0000~\u0000\bppsq\u0000~\u0000\u0011q\u0000~\u0000\u000f"
+"pq\u0000~\u0000:q\u0000~\u0000?q\u0000~\u0000Bsq\u0000~\u0000(t\u0000\bvalidadeq\u0000~\u0000&q\u0000~\u0000Bsq\u0000~\u0000\bppsq\u0000~\u0000\nq\u0000~"
+"\u0000\u000fp\u0000sq\u0000~\u0000\bppsq\u0000~\u0000\u0011ppq\u0000~\u0000\u0017sq\u0000~\u0000(q\u0000~\u0000+q\u0000~\u0000,sq\u0000~\u0000\u0000ppq\u0000~\u0000/sq\u0000~\u0000\b"
+"ppsq\u0000~\u0000\u0011q\u0000~\u0000\u000fpq\u0000~\u0000:q\u0000~\u0000?q\u0000~\u0000Bsq\u0000~\u0000(t\u0000\u0006codigoq\u0000~\u0000&q\u0000~\u0000Bsq\u0000~\u0000\b"
+"ppsq\u0000~\u0000\nq\u0000~\u0000\u000fp\u0000sq\u0000~\u0000\bppsq\u0000~\u0000\u0011ppq\u0000~\u0000\u0017sq\u0000~\u0000(q\u0000~\u0000+q\u0000~\u0000,sq\u0000~\u0000\u0000pp"
+"q\u0000~\u0000/sq\u0000~\u0000\bppsq\u0000~\u0000\u0011q\u0000~\u0000\u000fpq\u0000~\u0000:q\u0000~\u0000?q\u0000~\u0000Bsq\u0000~\u0000(t\u0000\u0006tarifaq\u0000~\u0000&"
+"q\u0000~\u0000Bsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexp"
+"Tablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000"
+"-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005"
+"countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Expres"
+"sionPool;xp\u0000\u0000\u0000\u0013\u0001pq\u0000~\u0000Eq\u0000~\u0000Oq\u0000~\u0000[q\u0000~\u0000Gq\u0000~\u0000\u0010q\u0000~\u0000\u0007q\u0000~\u0000Yq\u0000~\u0000\u0006q\u0000~"
+"\u0000\u0005q\u0000~\u0000-q\u0000~\u0000Jq\u0000~\u0000Tq\u0000~\u0000^q\u0000~\u0000\tq\u0000~\u0000Qq\u0000~\u00008q\u0000~\u0000Kq\u0000~\u0000Uq\u0000~\u0000_x"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public class Unmarshaller
            extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
                super(context, "---------------------");
            }

            protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 10;
                                eatText1(v);
                                continue outer;
                            }
                            break;
                        case  1 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 2;
                                eatText2(v);
                                continue outer;
                            }
                            break;
                        case  12 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 15;
                                eatText3(v);
                                continue outer;
                            }
                            break;
                        case  8 :
                            if (("codigo" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 9;
                                return ;
                            }
                            state = 11;
                            continue outer;
                        case  16 :
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        case  3 :
                            if (("validade" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 4;
                                return ;
                            }
                            state = 8;
                            continue outer;
                        case  4 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 7;
                                eatText4(v);
                                continue outer;
                            }
                            break;
                        case  11 :
                            if (("tarifa" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 12;
                                return ;
                            }
                            state = 16;
                            continue outer;
                        case  0 :
                            if (("grupo" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 1;
                                return ;
                            }
                            state = 3;
                            continue outer;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            private void eatText1(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Codigo = null;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText2(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Grupo = null;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText3(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Tarifa = null;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText4(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Validade = null;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 10;
                                eatText1(v);
                                continue outer;
                            }
                            break;
                        case  10 :
                            if (("codigo" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 11;
                                return ;
                            }
                            break;
                        case  2 :
                            if (("grupo" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 3;
                                return ;
                            }
                            break;
                        case  1 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 2;
                                eatText2(v);
                                continue outer;
                            }
                            break;
                        case  12 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 15;
                                eatText3(v);
                                continue outer;
                            }
                            break;
                        case  8 :
                            state = 11;
                            continue outer;
                        case  16 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  3 :
                            state = 8;
                            continue outer;
                        case  7 :
                            if (("validade" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 8;
                                return ;
                            }
                            break;
                        case  4 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 7;
                                eatText4(v);
                                continue outer;
                            }
                            break;
                        case  15 :
                            if (("tarifa" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 16;
                                return ;
                            }
                            break;
                        case  11 :
                            state = 16;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 17;
                                return ;
                            }
                            break;
                        case  1 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 19;
                                return ;
                            }
                            break;
                        case  12 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 13;
                                return ;
                            }
                            break;
                        case  8 :
                            state = 11;
                            continue outer;
                        case  16 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                        case  3 :
                            state = 8;
                            continue outer;
                        case  4 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 5;
                                return ;
                            }
                            break;
                        case  11 :
                            state = 16;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  9 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 10;
                                eatText1(v);
                                continue outer;
                            }
                            break;
                        case  20 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 2;
                                return ;
                            }
                            break;
                        case  14 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 15;
                                return ;
                            }
                            break;
                        case  1 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 2;
                                eatText2(v);
                                continue outer;
                            }
                            break;
                        case  6 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 7;
                                return ;
                            }
                            break;
                        case  18 :
                            if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                                state = 10;
                                return ;
                            }
                            break;
                        case  12 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 15;
                                eatText3(v);
                                continue outer;
                            }
                            break;
                        case  8 :
                            state = 11;
                            continue outer;
                        case  16 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                        case  3 :
                            state = 8;
                            continue outer;
                        case  4 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 7;
                                eatText4(v);
                                continue outer;
                            }
                            break;
                        case  11 :
                            state = 16;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  9 :
                                attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                                if (attIdx >= 0) {
                                    final java.lang.String v = context.eatAttribute(attIdx);
                                    state = 10;
                                    eatText1(v);
                                    continue outer;
                                }
                                state = 10;
                                eatText5(value);
                                return ;
                            case  5 :
                                state = 6;
                                eatText4(value);
                                return ;
                            case  1 :
                                attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                                if (attIdx >= 0) {
                                    final java.lang.String v = context.eatAttribute(attIdx);
                                    state = 2;
                                    eatText2(v);
                                    continue outer;
                                }
                                state = 2;
                                eatText6(value);
                                return ;
                            case  12 :
                                attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                                if (attIdx >= 0) {
                                    final java.lang.String v = context.eatAttribute(attIdx);
                                    state = 15;
                                    eatText3(v);
                                    continue outer;
                                }
                                state = 15;
                                eatText7(value);
                                return ;
                            case  8 :
                                state = 11;
                                continue outer;
                            case  16 :
                                revertToParentFromText(value);
                                return ;
                            case  3 :
                                state = 8;
                                continue outer;
                            case  4 :
                                attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                                if (attIdx >= 0) {
                                    final java.lang.String v = context.eatAttribute(attIdx);
                                    state = 7;
                                    eatText4(v);
                                    continue outer;
                                }
                                state = 7;
                                eatText8(value);
                                return ;
                            case  17 :
                                state = 18;
                                eatText1(value);
                                return ;
                            case  13 :
                                state = 14;
                                eatText3(value);
                                return ;
                            case  19 :
                                state = 20;
                                eatText2(value);
                                return ;
                            case  11 :
                                state = 16;
                                continue outer;
                            case  0 :
                                state = 3;
                                continue outer;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

            private void eatText5(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Codigo = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText6(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Grupo = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText7(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Tarifa = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText8(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Validade = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

        }

    }

    public class Unmarshaller
        extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----------");
        }

        protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("grupo" == ___local)&&("" == ___uri)) {
                            _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("validade" == ___local)&&("" == ___uri)) {
                            _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("codigo" == ___local)&&("" == ___uri)) {
                            _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("tarifa" == ___local)&&("" == ___uri)) {
                            _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  0 :
                        if (("Ofertas" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        if (("msgRetorno" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  3 :
                        if (("Ofertas" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("cdRetorno" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  9 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromLeaveElement((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                    case  8 :
                        if (("msgRetorno" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  9 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("Ofertas" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("cdRetorno" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromEnterAttribute((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  9 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromLeaveAttribute((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  9 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            _getOfertas().add(((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl) spawnChildFromText((br.com.indrasistemas.vivoservices.atendimento.retencao.tuxgateway.saida.getbonus.impl.ListaBonusVOTypeImpl.OfertasTypeImpl.class), 2, value)));
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText1(value);
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  9 :
                            revertToParentFromText(value);
                            return ;
                        case  4 :
                            state = 5;
                            eatText2(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _MsgRetorno = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CdRetorno = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
