#ifndef SVCWFATDGETCONSUL
#define SVCWFATDGETCONSUL

#define MSG_PARAMETROS_INVALIDOS "00W0001"
#define MSG_CONSULTOR_NAO_ENCONTRADO "00W0002"
#define MSG_ERRO_DATABASE "00W0003"
#define MSG_PROCESSO_NAO_ENCONTRADO "00W0004"

#define MSG_TEXT_PARAMETROS_INVALIDOS "Parâmetros de entrada inválidos"
#define MSG_TEXT_CONSULTOR_NAO_ENCONTRADO	"Consultor não encontrado"
#define MSG_TEXT_ERRO_DATABASE "Erro de Oracle"
#define MSG_TEXT_PROCESSO_NAO_ENCONTRADO	"Nenhum processo encontrado"

#define MSG_CODE_PARAMETROS_INVALIDOS 100
#define MSG_CODE_CONSULTOR_NAO_ENCONTRADO 101
#define MSG_CODE_ERRO_DATABASE 102
#define MSG_CODE_PROCESSO_NAO_ENCONTRADO 103


#endif
