
CREATE TABLE LOAD.CARGADOCUMENTOOFERTA_D (
	NRCPF 	VARCHAR(255),
	DTACAO 	date
);

COMMENT ON TABLE LOAD.CARGADOCUMENTOOFERTA_D IS 'Entidade para receber o arquivo de cancelamento gabrielacancelamento_aaaammddhh24mmss_nnnn.txt';
COMMENT ON COLUMN LOAD.CARGADOCUMENTOOFERTA_D.NRCPF IS 'Esta informacao deve ser chave do arquivo';
COMMENT ON COLUMN LOAD.CARGADOCUMENTOOFERTA_D.DTACAO IS 'Esta informacao deve ser preenchida com a data em que ocorreu a ativacao ou desativacao do cliente no parceiro';

ALTER TABLE LOAD.CARGADOCUMENTOOFERTA_D 
ADD CONSTRAINT CARGADOCUMENTOOFERTD_DCK1
CHECK (LENGTH(NRCPF) = 11);

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO BATCHPRO;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGADOCUMENTOOFERTA_D TO INDRALOG;


CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGADOCUMENTOOFERTA_D
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGADOCUMENTOOFERTA_D';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO BATCHPRO;
GRANT EXECUTE ON LOAD.TRUNC_CARGADOCUMENTOOFERTA_D TO INDRALOG;

