SET SQLPROMPT '';
SET TERMOUT ON;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

VARIABLE VO_CDERRO NUMBER
VARIABLE VO_DSERRO VARCHAR2(512)

DECLARE
	V_IDUSUARIO NUMBER := '&1';
BEGIN
	UPDATE /*+ PARALLEL(8) */
	  CUSTOMER.DOCUMENTOOFERTA D
	SET 
	  D.IDUSUARIOALTERACAO = V_IDUSUARIO,
	  D.DTULTIMAALTERACAO = SYSDATE,
	  D.INSTATUS = 0
	WHERE 
	  D.IDTIPODOCUMENTO = 1
	AND
	  D.NRDOCUMENTO IN (
		  SELECT /*+ PARALLEL(8) */
	      	NRCPF
		  FROM 
		    LOAD.CARGADOCUMENTOOFERTA_D
	  )  
	;

	COMMIT;
	:VO_CDERRO := 0;
	:VO_DSERRO := 'SUCESSO';
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		:VO_CDERRO := 99;
		:VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRICAO DO ERRO: ' || SQLERRM;
END;
/


SET TIMING OFF;

select CHR(10) from dual;
select 'VO_CDERRO', :VO_CDERRO from dual;
select 'VO_DSERRO', :VO_DSERRO from dual;

SET TERMOUT OFF;

VARIABLE V_FIELD_DELIMITER VARCHAR2(4);
EXECUTE :V_FIELD_DELIMITER := '&2';

-- Arquivo de registros criticados
SPOOL &3;
SELECT /*+ parallel(8) */ 
	L.NRCPF||:V_FIELD_DELIMITER||'D'||:V_FIELD_DELIMITER||L.DTACAO
FROM 
	LOAD.CARGADOCUMENTOOFERTA_D L
WHERE 
  L.NRCPF NOT IN (
    select D.NRDOCUMENTO
    from CUSTOMER.DOCUMENTOOFERTA D
		where D.IDTIPODOCUMENTO = 1
		and D.NRDOCUMENTO = L.NRCPF
    )
; 
SPOOL OFF;

EXIT :VO_CDERRO;

