SET TERMOUT OFF;
SET SQLPROMPT '';
SET FEEDBACK ON;
SET ECHO ON;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING ON;
SET SERVEROUTPUT ON;
SET TIME OFF;
SET TIMING ON;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 1024;
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 
BEGIN
	CUSTOMER.TRUNC_DOCUMENTOWHITELIST;
END;
/
EXIT 0;
