/*
  BATCH......: CARGALINHASPARCEIROS
  Criado por.: Eder Jani Martins (19/02/2015)
  Funcional..: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
	V_ROWCOUNT NUMBER;

BEGIN
	/*
		Insere os dados que existem na tabela LOAD.CARGALINHASPARCEIROS_02 mas somente aqueles
		que existem em LOAD.CARGALINHASPARCEIROS_01 e tambem existem SAPOIO_OW.LINHAINTERCEPTACAO
		Primeiro salva no historico, depois apaga (mas verifica o JOIN antes, pois so apaga quem existe)
	*/
    INSERT /*+ SYS_DL_CURSOR */ INTO LOAD.CARGALINHASPARCEIROS_02
	(
		CDAREAREGISTRO,
		NRLINHA,
		IDCLASSIFICACAOINTERCEPTACAO,
		IDUSUARIOINCLUSAO,
		IDLINHAINTERCEPTACAO,
		DTINCLUSAO
	)
	SELECT CLP.CDAREAREGISTRO, 
		   CLP.NRLINHA,
		   LI.IDCLASSIFICACAO,
		   LI.IDUSUARIOINCLUSAO,
		   LI.IDLINHAINTERCEPTACAO,
		   SYSDATE AS DTINCLUSAO
	  FROM LOAD.CARGALINHASPARCEIROS_01 CLP,
		   SAPOIO_OW.LINHAINTERCEPTACAO LI
	 WHERE CLP.NRLINHA = LI.NRLINHA
	   AND CLP.CDAREAREGISTRO = LI.CDAREAREGISTRO;

    V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inseridas em LOAD.CARGALINHASPARCEIROS_02: '||V_ROWCOUNT);
	/*
		Primeiro insere todos os registros na tabela de historico
		Apenas os registros que existem em SAPOIO_OW.LINHAINTERCEPTACAO
	*/
	INSERT INTO SAPOIO_OW.HISTORICOLINHAINTERCEPTACAO
	(
		IDHISTORICOLINHAINTERCEPTACAO,
		CDAREAREGISTRO,
		NRLINHA,
		IDCLASSIFICACAO,
		IDUSUARIOINCLUSAOLINHA,
		IDUSUARIOINCLUSAOHISTORICO,
		DTINCLUSAO
	)
	SELECT SAPOIO_OW.HISTORICOLINHAINTERCEPTACAOSQ.NEXTVAL,
		   CLP.CDAREAREGISTRO, 
		   CLP.NRLINHA,
		   LI.IDCLASSIFICACAO,
		   LI.IDUSUARIOINCLUSAO,
		   0 AS IDUSUARIOINCLUSAOHISTORICO,--Usuario de exclusao deste batch, indica que foi o BATCH quem apagou
		   CLP.DTINCLUSAO
	  FROM LOAD.CARGALINHASPARCEIROS_02 CLP,
		   SAPOIO_OW.LINHAINTERCEPTACAO LI
	 WHERE CLP.IDLINHAINTERCEPTACAO = LI.IDLINHAINTERCEPTACAO;

	V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inseridas em SAPOIO_OW.HISTORICOLINHAINTERCEPTACAO: '||V_ROWCOUNT);

	COMMIT;
	 
END;
/

/*
	Gera log de registros nao excluidos
*/
set termout off;
col arquivo new_value arquivo; 
select '&2'||'/err/'||'&3'||'.err' arquivo from dual; 
spool &arquivo append
SELECT 'R;'||li.CDAREAREGISTRO||li.NRLINHA||';'||li.IDCLASSIFICACAO||';Nao foram encontrados registros' 
  FROM SAPOIO_OW.LINHAINTERCEPTACAO LI
 WHERE NOT EXISTS
	  (
		SELECT 1
		FROM LOAD.CARGALINHASPARCEIROS_02 CLP
		WHERE CLP.IDLINHAINTERCEPTACAO = LI.IDLINHAINTERCEPTACAO
	  )
	  and rownum <= 100;
   
spool off
set termout on;

DECLARE

	V_ROWCOUNT NUMBER;
	
BEGIN

	 /*
	    Apos salvar os dados na tabela de historico entao apaga todos os dados em 
		SAPOIO_OW.LINHAINTERCEPTACAO que existem em LOAD.CARGALINHASPARCEIROS_02
	*/
	DELETE FROM SAPOIO_OW.LINHAINTERCEPTACAO LI
	WHERE EXISTS
		  (
			SELECT 1
			FROM LOAD.CARGALINHASPARCEIROS_02 CLP
			WHERE CLP.IDLINHAINTERCEPTACAO = LI.IDLINHAINTERCEPTACAO
		  );

    V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas apagadas em SAPOIO_OW.LINHAINTERCEPTACAO: '||V_ROWCOUNT);
	COMMIT;
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
