/*
  BATCH......: CARGALINHASPARCEIROS
  Criado por.: Eder Jani Martins (19/02/2015)
  Funcional..: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
	V_ROWCOUNT NUMBER;

BEGIN
	/*
		Insere os dados que existem na tabela LOAD.CARGALINHASPARCEIROS_01 e nao estao
		em SAPOIO_OW.LINHAPARCEIRO
		Foi usado o ALTER JOIN para retornar o campo para e retornar o campo LP.IDLINHAPARCEIRO e
		evitar milhoes de subselects (ficou com desempenho muito melhor)
	*/
	MERGE /*+ PARALLEL (64) */ INTO SAPOIO_OW.LINHAPARCEIRO LPMERGE
	USING (
		SELECT DISTINCT
			   LP.IDLINHAPARCEIRO,
			   CLP.CDAREAREGISTRO,
			   CLP.NRLINHA,
			   CLP.IDCLASSIFICACAO,
			   CLP.IDPARCEIRO,
			   0 AS IDUSUARIOINCLUSAO,
			   0 AS IDUSUARIOALTERACAO
		  FROM LOAD.CARGALINHASPARCEIROS_01 CLP,
			   SAPOIO_OW.LINHAPARCEIRO LP
		 WHERE CLP.CDAREAREGISTRO = LP.CDAREAREGISTRO (+)
		   AND CLP.NRLINHA = LP.NRLINHA (+)
		   AND CLP.IDPARCEIRO IS NOT NULL -- Eitar possíveis dados corropindo no arquivo de origem (sempre deve existir IDPARCEIRO) 
	) INCLUSAO
	ON ( INCLUSAO.CDAREAREGISTRO = LPMERGE.CDAREAREGISTRO AND INCLUSAO.NRLINHA = LPMERGE.NRLINHA )
	WHEN MATCHED THEN UPDATE SET 
		LPMERGE.IDCLASSIFICACAO = INCLUSAO.IDCLASSIFICACAO, 
		LPMERGE.IDPARCEIRO = INCLUSAO.IDPARCEIRO,
		LPMERGE.DTULTIMAALTERACAO = SYSDATE,
		LPMERGE.IDUSUARIOALTERACAO = INCLUSAO.IDUSUARIOALTERACAO
	WHEN NOT MATCHED THEN INSERT (
		LPMERGE.IDLINHAPARCEIRO,
		LPMERGE.CDAREAREGISTRO,
		LPMERGE.NRLINHA,
		LPMERGE.IDCLASSIFICACAO,
		LPMERGE.IDPARCEIRO,
		LPMERGE.DTINCLUSAO,
		LPMERGE.DTULTIMAALTERACAO,
		LPMERGE.IDUSUARIOINCLUSAO,
		LPMERGE.IDUSUARIOALTERACAO
	)VALUES(
		SAPOIO_OW.LINHAPARCEIROSQ.NEXTVAL,
		INCLUSAO.CDAREAREGISTRO,
		INCLUSAO.NRLINHA,
		INCLUSAO.IDCLASSIFICACAO,
		INCLUSAO.IDPARCEIRO,
		SYSDATE,
		SYSDATE,
		INCLUSAO.IDUSUARIOINCLUSAO,
		INCLUSAO.IDUSUARIOALTERACAO
	);

	V_ROWCOUNT:=SQL%ROWCOUNT;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inseridas em SAPOIO_OW.LINHAPARCEIRO: '||V_ROWCOUNT);
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
