/*
  BATCH......: CARGALINHASPARCEIROS
  Criado por.: Eder Jani Martins (19/02/2015)
  Funcional..: Marcia Santana Silva
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

DECLARE
	V_ROWCOUNT NUMBER;

BEGIN
	/*
		Insere os dados que existem na tabela LOAD.CARGALINHASPARCEIROS_01 e nao estao
		em SAPOIO_OW.LINHAINTERCEPTACAO
		Foi usado o ALTER JOIN para retornar o campo para e retornar o campo LP.IDLINHAPARCEIRO e
		evitar milhoes de subselects (ficou com desempenho muito melhor)
	*/
	MERGE /*+ PARALLEL (64) */ INTO SAPOIO_OW.LINHAINTERCEPTACAO LIMERGE
	USING (
		SELECT DISTINCT
			   LI.IDLINHAINTERCEPTACAO,
			   CLP.IDCLASSIFICACAO, 
			   CLP.CDAREAREGISTRO, 
			   CLP.NRLINHA, 
			   0 AS IDUSUARIOINCLUSAO,
			   0 AS IDUSUARIOALTERACAO
		  FROM LOAD.CARGALINHASPARCEIROS_01 CLP,
			   SAPOIO_OW.LINHAINTERCEPTACAO LI
		 WHERE CLP.CDAREAREGISTRO = LI.CDAREAREGISTRO (+)
		   AND CLP.NRLINHA = LI.NRLINHA (+)
	) INCLUSAO
	ON ( INCLUSAO.CDAREAREGISTRO = LIMERGE.CDAREAREGISTRO AND INCLUSAO.NRLINHA = LIMERGE.NRLINHA )
	WHEN MATCHED THEN UPDATE SET 
		LIMERGE.IDCLASSIFICACAO = INCLUSAO.IDCLASSIFICACAO, 
		LIMERGE.IDUSUARIOALTERACAO = INCLUSAO.IDUSUARIOALTERACAO,
		LIMERGE.DTULTIMAALTERACAO = SYSDATE
	WHEN NOT MATCHED THEN INSERT (
		LIMERGE.IDLINHAINTERCEPTACAO,
		LIMERGE.IDCLASSIFICACAO,
		LIMERGE.CDAREAREGISTRO,
		LIMERGE.NRLINHA,
		LIMERGE.IDUSUARIOINCLUSAO,
		LIMERGE.DTINCLUSAO,
		LIMERGE.IDUSUARIOALTERACAO,
		LIMERGE.DTULTIMAALTERACAO
	)
	VALUES (
		SAPOIO_OW.LINHAINTERCEPTACAOSQ.NEXTVAL,
		INCLUSAO.IDCLASSIFICACAO, 
		INCLUSAO.CDAREAREGISTRO, 
		INCLUSAO.NRLINHA, 
		INCLUSAO.IDUSUARIOINCLUSAO,
		SYSDATE,
		INCLUSAO.IDUSUARIOALTERACAO,
		SYSDATE
	);

	V_ROWCOUNT:=SQL%ROWCOUNT;
	DBMS_OUTPUT.PUT_LINE('Total de linhas inseridas em SAPOIO_OW.LINHAINTERCEPTACAO: '||V_ROWCOUNT);
	COMMIT;
END;
/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT
