/**
 * TecnologiaPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn;

public interface TecnologiaPortType extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.CriarTecnologiaResponse criarTecnologia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.CriarTecnologiaRequest criarTecnologiaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AlterarTecnologiaTipoFrequenciaResponse alterarTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AlterarTecnologiaTipoFrequenciaRequest alterarTecnologiaTipoFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AssociarTecnologiaTipoFrequenciaResponse associarTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AssociarTecnologiaTipoFrequenciaRequest associarTecnologiaTipoFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaTipoFrequenciaResponse buscarListaTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaTipoFrequenciaRequest buscarListaTecnologiaTipoFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaModeloPorTecnologiaResponse buscarListaModeloPorTecnologia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaModeloPorTecnologiaRequest buscarListaModeloPorTecnologiaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.ExcluirListaTecnologiaResponse excluirListaTecnologia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.ExcluirListaTecnologiaRequest excluirListaTecnologiaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarAssociacaoTecnologiaTpFrequenciaResponse buscarAssociacaoTecnologiaTpFrequencia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarAssociacaoTecnologiaTpFrequenciaRequest buscarAssociacaoTecnologiaTpFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaResponse buscarListaTecnologia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaRequest buscarListaTecnologiaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaPorModeloResponse buscarListaTecnologiaPorModelo(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaPorModeloRequest buscarListaTecnologiaPorModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaSimplesResponse buscarListaTecnologiaSimples(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.BuscarListaTecnologiaSimplesRequest buscarListaTecnologiaSimplesRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.DesassociarListaTecnologiaTipoFrequenciaResponse desassociarListaTecnologiaTipoFrequencia(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.DesassociarListaTecnologiaTipoFrequenciaRequest desassociarListaTecnologiaTipoFrequenciaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AssociarTecnologiaTipoFrequenciaValorResponse associarTecnologiaTipoFrequenciaValor(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.AssociarTecnologiaTipoFrequenciaValorRequest associarTecnologiaTipoFrequenciaValorRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.DesassociarTecnologiaTpFrequenciaVlResponse desassociarTecnologiaTpFrequenciaVl(br.com.vivo.catalogoPRS.ws.catalogoTecnologia.sn.DesassociarTecnologiaTpFrequenciaVlRequest desassociarTecnologiaTpFrequenciaVlRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoTecnologia.mc.geral.ErroInfo;
}
