#!/bin/ksh

. ./orabatch.cfg

sqlplus -s ${ORABATCH_CONNECTION} <<SQL 
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
DECLARE
  v_qtdias NUMBER :=10;
  
BEGIN

	  BEGIN
         SELECT TO_NUMBER (DSVALORPARAMETRO)
           INTO v_qtdias
         FROM APOIO.PARAMETRO
         WHERE CDPARAMETRO = 'LIMITE_DIAS_CONSULTA_HISTORICO_PROTOCOLO';
      EXCEPTION
      WHEN NO_DATA_FOUND
         THEN
            v_qtdias := 10;
      END;

  DELETE FROM ATENDIMENTO.CONSULTAPROTOCOLOHISTORICO WHERE DTPESQUISA <= (TRUNC(SYSDATE) -v_qtdias);
  COMMIT;
END;
/
EXIT;
SQL
