/***********************************************************
#  BATCH......: expurgoSincronismoAMDOCS
#  Criado por.: Lucas Gomes Fenelon de Moraes (12/04/2016)
#  Funcional..: Erika Brum
***********************************************************/
SET PAGESIZE 0
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET ECHO OFF
SET COLSEP "|"
SET TAB OFF
SET PAGESIZE 0
SET TRIMS ON
SET WRAP OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

	DELETE FROM CONVERGENTE_OW.LOG_SINCRONISMO_XML
     WHERE IDLOGSINCRONISMO IN
		(SELECT IDLOGSINCRONISMO
		   FROM CONVERGENTE_OW.LOG_SINCRONISMO
		  WHERE IDFILA IN
			(SELECT IDFILAAMDOCS 
			   FROM CONVERGENTE_OW.FILASINCRONISMOAMDOCS 
			  WHERE DTULTIMAALTERACAO < TO_DATE('&1', 'DDMMYYYY') - 
				 (
                  TO_NUMBER((SELECT DSVALORPARAMETRO 
							   FROM APOIO.PARAMETRO 
							  WHERE CDPARAMETRO = 'QTD_MES_EXPURGO_FILA_SINCRONISMO_AMDOCS' 
							    AND ROWNUM < 2
						   )) * 30
				 )
		    )
		 );
	/
    
	COMMIT;
	/

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT