SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

SPOOL &1;
SELECT 
  ID ||'|'||
  TERMINAL ||'|'||
  UF ||'|'||
  RAZAOSOCIAL ||'|'||
  CLASSIFICACAO ||'|'||
  VDN ||'|'||
  DEALER ||'|'||
  CANAL ||'|'||
  STATUS ||'|'
  AS RELATORIOPARCEIRO
FROM (
	SELECT /*+ PARALLEL(8) */
	  PARCEIRO.IDPARCEIRO AS ID ,
	  LINHAPARCEIRO.CDAREAREGISTRO
	  || LINHAPARCEIRO.NRLINHA      AS TERMINAL,
	  ENDERECOPARCEIRO.NMUF         AS UF,
	  PARCEIRO.NMPARCEIRO           AS RAZAOSOCIAL,
	  CLASSIFICACAO.DSCLASSIFICACAO AS CLASSIFICACAO,
	  CLASSIFICACAO.CDVDN           AS VDN,
	  PARCEIRO.CDADABAS DEALER,
	  DECODE(PARCEIRO.IDCANALATENDIMENTO,1,'LLPP',2,'LLAA',3,'Revenda',4,'Varejo',5,'Recarga',6,'CallCenter','Outros') AS CANAL,
	  DECODE(PARCEIRO.INSTATUS,1,'ATIVO','INATIVO')                                                                    AS STATUS
	FROM 
	  SAPOIO_OW.PARCEIRO,
	  SAPOIO_OW.ENDERECOPARCEIRO,
	  SAPOIO_OW.LINHAPARCEIRO,
	  SAPOIO_OW.CLASSIFICACAO
	WHERE 
		PARCEIRO.IDPARCEIRO            = ENDERECOPARCEIRO.IDPARCEIRO
	AND PARCEIRO.IDPARCEIRO            = LINHAPARCEIRO.IDPARCEIRO
	AND LINHAPARCEIRO.IDCLASSIFICACAO  = CLASSIFICACAO.IDCLASSIFICACAO
	AND CLASSIFICACAO.IDCLASSIFICACAO IN (7,11,2,9,3,12,14,1,10,4,13)
	AND PARCEIRO.INSTATUS              = 1
	ORDER BY 3,4,5 ASC
)
;
SPOOL OFF;

EXIT 0
