/**
 * MatrizOfertaPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn;

public interface MatrizOfertaPortType extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ObterExistenciaItemPrecoResponse obterExistenciaItemPreco(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ObterExistenciaItemPrecoRequest obterExistenciaItemPrecoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ObterVLAVistaVL10VezesResponse obterVLAVistaVL10Vezes(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ObterVLAVistaVL10VezesRequest obterVLAVistaVL10VezesRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemDataResponse alterarItemData(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemDataRequest alterarItemDataRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemPrecoResponse alterarItemPreco(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemPrecoRequest alterarItemPrecoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarCriticasImportacaoResponse buscarCriticasImportacao(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarCriticasImportacaoRequest buscarCriticasImportacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExportarMatrizOfertaArquivoItemResponse exportarMatrizOfertaArquivoItem(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExportarMatrizOfertaArquivoItemRequest exportarMatrizOfertaArquivoItemRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaResultadoImportacaoResponse buscarListaResultadoImportacao(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaResultadoImportacaoRequest buscarListaResultadoImportacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaNmMatrizResponse buscarListaNmMatriz(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaNmMatrizRequest buscarListaNmMatrizRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaStatusImportacaoResponse buscarListaStatusImportacao(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaStatusImportacaoRequest buscarListaStatusImportacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ImportarMatrizOfertaArquivoResponse importarMatrizOfertaArquivo(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ImportarMatrizOfertaArquivoRequest importarMatrizOfertaArquivoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.CriarCabecalhoResponse criarCabecalho(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.CriarCabecalhoRequest criarCabecalhoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaTipoMatrizResponse buscarListaTipoMatriz(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaTipoMatrizRequest buscarListaTipoMatrizRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarCabecalhoResponse alterarCabecalho(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarCabecalhoRequest alterarCabecalhoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemResponse alterarItem(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AlterarItemRequest alterarItemRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaCabecalhoResponse buscarListaCabecalho(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaCabecalhoRequest buscarListaCabecalhoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaVariaveisResponse buscarListaVariaveis(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaVariaveisRequest buscarListaVariaveisRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExcluirCabecalhoResponse excluirCabecalho(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExcluirCabecalhoRequest excluirCabecalhoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExcluirVariaveisResponse excluirVariaveis(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ExcluirVariaveisRequest excluirVariaveisRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AssociarVariaveisResponse associarVariaveis(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.AssociarVariaveisRequest associarVariaveisRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaItensResponse buscarListaItens(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaItensRequest buscarListaItensRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaNmOfSAPPorMatrizResponse buscarListaNmOfSAPPorMatriz(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaNmOfSAPPorMatrizRequest buscarListaNmOfSAPPorMatrizRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ImportarMatrizOfertaTipoContratoResponse importarMatrizOfertaTipoContrato(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ImportarMatrizOfertaTipoContratoRequest importarMatrizOfertaTipoContratoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaDetalhesImportacaoResponse buscarListaDetalhesImportacao(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarListaDetalhesImportacaoRequest buscarListaDetalhesImportacaoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarIdMatrizOfertaArquivoResponse buscarIdMatrizOfertaArquivo(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.BuscarIdMatrizOfertaArquivoRequest buscarIdMatrizOfertaArquivoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ProcessarMatrizOfertaArquivoResponse processarMatrizOfertaArquivo(br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.sn.ProcessarMatrizOfertaArquivoRequest processarMatrizOfertaArquivoRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoMatrizOferta.mc.geral.ErroInfo;
}
