/**
 * CaracteristicaPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn;

public interface CaracteristicaPortType extends java.rmi.Remote {
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.AlterarCaracteristicaResponse alterarCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.AlterarCaracteristicaRequest alterarCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.ExcluirListaCaracteristicaResponse excluirListaCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.ExcluirListaCaracteristicaRequest excluirListaCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaValorCaracteristicaResponse buscarListaValorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaValorCaracteristicaRequest buscarListaValorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaModeloPorCaracteristicaResponse buscarListaModeloPorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaModeloPorCaracteristicaRequest buscarListaModeloPorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaResponse buscarListaCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaRequest buscarListaCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarValorCaracteristicaPorIdResponse buscarValorCaracteristicaPorId(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarValorCaracteristicaPorIdRequest buscarValorCaracteristicaPorIdRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.CriarValorCaracteristicaResponse criarValorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.CriarValorCaracteristicaRequest criarValorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.ExcluirListaValorCaracteristicaResponse excluirListaValorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.ExcluirListaValorCaracteristicaRequest excluirListaValorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.CriarCaracteristicaResponse criarCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.CriarCaracteristicaRequest criarCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.DisponibilizarCaracteristicaResponse disponibilizarCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.DisponibilizarCaracteristicaRequest disponibilizarCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarModelosPorValorCaracteristicaResponse buscarModelosPorValorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarModelosPorValorCaracteristicaRequest buscarModelosPorValorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaComValorPorModeloResponse buscarListaCaracteristicaComValorPorModelo(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaComValorPorModeloRequest buscarListaCaracteristicaComValorPorModeloRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarCaracteristicaPorIdResponse buscarCaracteristicaPorId(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarCaracteristicaPorIdRequest buscarCaracteristicaPorIdRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.AlterarValorCaracteristicaResponse alterarValorCaracteristica(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.AlterarValorCaracteristicaRequest alterarValorCaracteristicaRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
    public br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaComValorResponse buscarListaCaracteristicaComValor(br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.sn.BuscarListaCaracteristicaComValorRequest buscarListaCaracteristicaComValorRequest, String username, String password) throws java.rmi.RemoteException, br.com.vivo.catalogoPRS.ws.catalogoCanalCaracteristica.mc.geral.ErroInfo;
}
