#
# $Id: makefile,v 1.1 2009/07/31 15:34:11 a5110702 Exp $
#

#Compile Tuxedo shared objects
#This makefile generate a shared object file
.SILENT:

#Variable Section
SO=get_apoiocampanha
PC=get_motivocampanha.pcpp get_submotivocampanha.pcpp get_canal.pcpp get_tipocampanha.pcpp get_campanha.pcpp get_statuscampanha.pcpp
CPP=
CUSTOBJ=

include $(HOME)/TUXEFO/campanha/commons/include/mklib.inc

