//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 11:56:26 AM BRT 
//


package br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl;

public class MsgBodyTypeImpl implements br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
{

    protected br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType _ValidaSenha;
    public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.class);
    }

    public br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType getValidaSenha() {
        return _ValidaSenha;
    }

    public void setValidaSenha(br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType value) {
        _ValidaSenha = value;
    }

    public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
        return new br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "ValidaSenha");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ValidaSenha), "ValidaSenha");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ValidaSenha), "ValidaSenha");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _ValidaSenha), "ValidaSenha");
        context.endElement();
    }

    public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0000pp\u0000sr\u0000\u001dcom."
+"sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000 com.sun.msv."
+"grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.Unary"
+"Exp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee"
+"\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004q\u0000~\u0000\u0011psr\u00002com.sun.msv.gr"
+"ammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000\u0010\u0001"
+"psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Ex"
+"pression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004q\u0000~\u0000\u0016psr\u0000#com.sun"
+".msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/"
+"lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001dxq\u0000~\u0000\u0018t\u0000[br.com.indrasistema"
+"s.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.Val"
+"idaSenhaTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq"
+"\u0000~\u0000\u000bppsq\u0000~\u0000\u0012q\u0000~\u0000\u0011psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003"
+"L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004name"
+"t\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004ppsr\u0000\"com.sun.msv.data"
+"type.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Bu"
+"iltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Concr"
+"eteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImp"
+"l\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001dL\u0000\btypeNameq\u0000~\u0000\u001dL\u0000\nwhiteSpac"
+"et\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http:"
+"//www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype."
+"xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.d"
+"atatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv."
+"grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bc"
+"om.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001dL\u0000\fnam"
+"espaceURIq\u0000~\u0000\u001dxpq\u0000~\u0000.q\u0000~\u0000-sq\u0000~\u0000\u001ct\u0000\u0004typet\u0000)http://www.w3.org/"
+"2001/XMLSchema-instanceq\u0000~\u0000\u001bsq\u0000~\u0000\u001ct\u0000\u000bValidaSenhat\u0000\u0000sr\u0000\"com.s"
+"un.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/s"
+"un/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.g"
+"rammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstream"
+"VersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000"
+"\u0004\u0001pq\u0000~\u0000!q\u0000~\u0000\u000fq\u0000~\u0000\fq\u0000~\u0000\tx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("statusText" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("statusCode" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("titularidadeSenha" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("tipoLinha" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("status" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("statCom" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("sexo" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("reason" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("primeiroNome" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("nome" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("e_mail" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("dtNasc" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("cdCodigoRetorno" == ___local)&&("" == ___uri)) {
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("ValidaSenha" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromLeaveElement((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("ValidaSenha" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromEnterAttribute((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromLeaveAttribute((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            _ValidaSenha = ((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl) spawnChildFromText((br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.class), 2, value));
                            return ;
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

    public static class ValidaSenhaTypeImpl implements br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType, com.sun.xml.bind.JAXBObject, br.com.indrasistemas.jaxb.impl.runtime.UnmarshallableObject, br.com.indrasistemas.jaxb.impl.runtime.XMLSerializable, br.com.indrasistemas.jaxb.impl.runtime.ValidatableObject
    {

        protected java.lang.String _StatusCode;
        protected java.lang.String _EMail;
        protected java.lang.String _TitularidadeSenha;
        protected java.lang.String _StatusText;
        protected java.lang.String _StatCom;
        protected java.lang.String _Status;
        protected java.lang.String _PrimeiroNome;
        protected java.lang.String _CdCodigoRetorno;
        protected java.lang.String _Sexo;
        protected java.lang.String _Nome;
        protected java.lang.String _TipoLinha;
        protected java.lang.String _DtNasc;
        protected java.lang.String _Reason;
        public final static java.lang.Class version = (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.JAXBVersion.class);
        private static com.sun.msv.grammar.Grammar schemaFragment;

        private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
            return (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType.class);
        }

        public java.lang.String getStatusCode() {
            return _StatusCode;
        }

        public void setStatusCode(java.lang.String value) {
            _StatusCode = value;
        }

        public java.lang.String getEMail() {
            return _EMail;
        }

        public void setEMail(java.lang.String value) {
            _EMail = value;
        }

        public java.lang.String getTitularidadeSenha() {
            return _TitularidadeSenha;
        }

        public void setTitularidadeSenha(java.lang.String value) {
            _TitularidadeSenha = value;
        }

        public java.lang.String getStatusText() {
            return _StatusText;
        }

        public void setStatusText(java.lang.String value) {
            _StatusText = value;
        }

        public java.lang.String getStatCom() {
            return _StatCom;
        }

        public void setStatCom(java.lang.String value) {
            _StatCom = value;
        }

        public java.lang.String getStatus() {
            return _Status;
        }

        public void setStatus(java.lang.String value) {
            _Status = value;
        }

        public java.lang.String getPrimeiroNome() {
            return _PrimeiroNome;
        }

        public void setPrimeiroNome(java.lang.String value) {
            _PrimeiroNome = value;
        }

        public java.lang.String getCdCodigoRetorno() {
            return _CdCodigoRetorno;
        }

        public void setCdCodigoRetorno(java.lang.String value) {
            _CdCodigoRetorno = value;
        }

        public java.lang.String getSexo() {
            return _Sexo;
        }

        public void setSexo(java.lang.String value) {
            _Sexo = value;
        }

        public java.lang.String getNome() {
            return _Nome;
        }

        public void setNome(java.lang.String value) {
            _Nome = value;
        }

        public java.lang.String getTipoLinha() {
            return _TipoLinha;
        }

        public void setTipoLinha(java.lang.String value) {
            _TipoLinha = value;
        }

        public java.lang.String getDtNasc() {
            return _DtNasc;
        }

        public void setDtNasc(java.lang.String value) {
            _DtNasc = value;
        }

        public java.lang.String getReason() {
            return _Reason;
        }

        public void setReason(java.lang.String value) {
            _Reason = value;
        }

        public br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
            return new br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.Unmarshaller(context);
        }

        public void serializeBody(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
            if (_CdCodigoRetorno!= null) {
                context.startElement("", "cdCodigoRetorno");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _CdCodigoRetorno), "CdCodigoRetorno");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_DtNasc!= null) {
                context.startElement("", "dtNasc");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _DtNasc), "DtNasc");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_EMail!= null) {
                context.startElement("", "e_mail");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _EMail), "EMail");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_Nome!= null) {
                context.startElement("", "nome");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Nome), "Nome");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_PrimeiroNome!= null) {
                context.startElement("", "primeiroNome");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _PrimeiroNome), "PrimeiroNome");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_Reason!= null) {
                context.startElement("", "reason");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Reason), "Reason");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_Sexo!= null) {
                context.startElement("", "sexo");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Sexo), "Sexo");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_StatCom!= null) {
                context.startElement("", "statCom");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _StatCom), "StatCom");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_Status!= null) {
                context.startElement("", "status");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _Status), "Status");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_TipoLinha!= null) {
                context.startElement("", "tipoLinha");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _TipoLinha), "TipoLinha");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_TitularidadeSenha!= null) {
                context.startElement("", "titularidadeSenha");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _TitularidadeSenha), "TitularidadeSenha");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_StatusCode!= null) {
                context.startElement("", "statusCode");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _StatusCode), "StatusCode");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
            if (_StatusText!= null) {
                context.startElement("", "statusText");
                context.endNamespaceDecls();
                context.endAttributes();
                try {
                    context.text(((java.lang.String) _StatusText), "StatusText");
                } catch (java.lang.Exception e) {
                    br.com.indrasistemas.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endElement();
            }
        }

        public void serializeAttributes(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public void serializeURIs(br.com.indrasistemas.jaxb.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException
        {
        }

        public java.lang.Class getPrimaryInterface() {
            return (br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.MsgBodyType.ValidaSenhaType.class);
        }

        public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
            if (schemaFragment == null) {
                schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000!com.sun.msv.grammar.InterleaveExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom."
+"sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/g"
+"rammar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expres"
+"sion\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L"
+"\u0000\u000bexpandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000"
+"ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.su"
+"n.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.gr"
+"ammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/"
+"msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~"
+"\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sr\u0000\u001fcom.sun.m"
+"sv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\u001bcom.sun.msv.gra"
+"mmar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatyp"
+"e;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000"
+"\u0003ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAl"
+"waysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnames"
+"paceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000#L\u0000\nwhiteSpacet\u0000."
+"Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://ww"
+"w.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd"
+".WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.data"
+"type.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.gr"
+"ammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom"
+".sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000#L\u0000\fnames"
+"paceURIq\u0000~\u0000#xpq\u0000~\u0000\'q\u0000~\u0000&sq\u0000~\u0000\u0011ppsr\u0000 com.sun.msv.grammar.Attr"
+"ibuteExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0014xq\u0000~\u0000\u0003q\u0000~\u0000\u0018ps"
+"q\u0000~\u0000\u001bppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000 q\u0000~\u0000&t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProces"
+"sor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000)q\u0000~\u0000,sq\u0000~\u0000-q\u0000~\u00005q\u0000~\u0000&sr\u0000#com.su"
+"n.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000#L\u0000\f"
+"namespaceURIq\u0000~\u0000#xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000co"
+"m.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0003sq\u0000~\u0000\u0017\u0001psq\u0000~\u00009t\u0000\u000fcdCodigoRetornot\u0000\u0000q\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~"
+"\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000"
+"\u0006dtNascq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011pps"
+"q\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0006e_mailq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011pps"
+"q\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?"
+"sq\u0000~\u00009t\u0000\u0004nomeq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000"
+"~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\fprimeiroNomeq\u0000~\u0000Cq\u0000"
+"~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~"
+"\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0006reasonq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq"
+"\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0004sexoq"
+"\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~"
+"\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0007statComq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000"
+"~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t"
+"\u0000\u0006statusq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011pp"
+"sq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\ttipoLinhaq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000"
+"\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q"
+"\u0000~\u0000?sq\u0000~\u00009t\u0000\u0011titularidadeSenhaq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p"
+"\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011ppsq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\nst"
+"atusCodeq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0011ppsq\u0000~\u0000\u0013q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0019ppq\u0000~\u0000\u001esq\u0000~\u0000\u0011pp"
+"sq\u0000~\u00000q\u0000~\u0000\u0018pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\nstatusTextq\u0000~\u0000Cq\u0000~\u0000?sr\u0000\""
+"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/L"
+"com/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun."
+"msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rs"
+"treamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;"
+"xp\u0000\u0000\u00003\u0001pq\u0000~\u0000\fq\u0000~\u0000\u000eq\u0000~\u0000/q\u0000~\u0000Gq\u0000~\u0000Nq\u0000~\u0000Uq\u0000~\u0000\\q\u0000~\u0000cq\u0000~\u0000jq\u0000~\u0000qq\u0000"
+"~\u0000xq\u0000~\u0000\tq\u0000~\u0000\u007fq\u0000~\u0000\u0086q\u0000~\u0000\u0007q\u0000~\u0000\u001aq\u0000~\u0000Fq\u0000~\u0000Mq\u0000~\u0000Tq\u0000~\u0000[q\u0000~\u0000bq\u0000~\u0000iq\u0000"
+"~\u0000pq\u0000~\u0000wq\u0000~\u0000~q\u0000~\u0000\u0085q\u0000~\u0000\u008dq\u0000~\u0000\u008cq\u0000~\u0000\u0094q\u0000~\u0000\u0093q\u0000~\u0000\u0005q\u0000~\u0000\u000bq\u0000~\u0000\rq\u0000~\u0000\u000fq\u0000"
+"~\u0000\u0006q\u0000~\u0000\bq\u0000~\u0000\u0012q\u0000~\u0000Dq\u0000~\u0000Kq\u0000~\u0000Rq\u0000~\u0000Yq\u0000~\u0000`q\u0000~\u0000gq\u0000~\u0000nq\u0000~\u0000uq\u0000~\u0000|q\u0000"
+"~\u0000\u0083q\u0000~\u0000\u008aq\u0000~\u0000\u0091q\u0000~\u0000\nq\u0000~\u0000\u0010x"));
            }
            return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
        }

        public class Unmarshaller
            extends br.com.indrasistemas.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
        {


            public Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context) {
                super(context, "---------------------------");
            }

            protected Unmarshaller(br.com.indrasistemas.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
                this(context);
                state = startState;
            }

            public java.lang.Object owner() {
                return br.com.indrasistemas.vivoservices.autenticacao.tuxgateway.saida.impl.MsgBodyTypeImpl.ValidaSenhaTypeImpl.this;
            }

            public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  0 :
                            if (("statusText" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 1;
                                return ;
                            }
                            if (("statusCode" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 3;
                                return ;
                            }
                            if (("titularidadeSenha" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 19;
                                return ;
                            }
                            if (("tipoLinha" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 9;
                                return ;
                            }
                            if (("status" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 25;
                                return ;
                            }
                            if (("statCom" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 7;
                                return ;
                            }
                            if (("sexo" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 5;
                                return ;
                            }
                            if (("reason" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 21;
                                return ;
                            }
                            if (("primeiroNome" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 17;
                                return ;
                            }
                            if (("nome" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 15;
                                return ;
                            }
                            if (("e_mail" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 23;
                                return ;
                            }
                            if (("dtNasc" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 13;
                                return ;
                            }
                            if (("cdCodigoRetorno" == ___local)&&("" == ___uri)) {
                                context.pushAttributes(__atts, true);
                                state = 11;
                                return ;
                            }
                            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                            return ;
                    }
                    super.enterElement(___uri, ___local, ___qname, __atts);
                    break;
                }
            }

            public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  0 :
                            revertToParentFromLeaveElement(___uri, ___local, ___qname);
                            return ;
                        case  14 :
                            if (("dtNasc" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  18 :
                            if (("primeiroNome" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  20 :
                            if (("titularidadeSenha" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  6 :
                            if (("sexo" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  2 :
                            if (("statusText" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  26 :
                            if (("status" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  16 :
                            if (("nome" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  10 :
                            if (("tipoLinha" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  8 :
                            if (("statCom" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  24 :
                            if (("e_mail" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  22 :
                            if (("reason" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  12 :
                            if (("cdCodigoRetorno" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                        case  4 :
                            if (("statusCode" == ___local)&&("" == ___uri)) {
                                context.popAttributes();
                                state = 0;
                                return ;
                            }
                            break;
                    }
                    super.leaveElement(___uri, ___local, ___qname);
                    break;
                }
            }

            public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  0 :
                            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                            return ;
                    }
                    super.enterAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    switch (state) {
                        case  0 :
                            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                            return ;
                    }
                    super.leaveAttribute(___uri, ___local, ___qname);
                    break;
                }
            }

            public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                int attIdx;
                outer:
                while (true) {
                    try {
                        switch (state) {
                            case  0 :
                                revertToParentFromText(value);
                                return ;
                            case  15 :
                                state = 16;
                                eatText1(value);
                                return ;
                            case  19 :
                                state = 20;
                                eatText2(value);
                                return ;
                            case  3 :
                                state = 4;
                                eatText3(value);
                                return ;
                            case  13 :
                                state = 14;
                                eatText4(value);
                                return ;
                            case  17 :
                                state = 18;
                                eatText5(value);
                                return ;
                            case  25 :
                                state = 26;
                                eatText6(value);
                                return ;
                            case  11 :
                                state = 12;
                                eatText7(value);
                                return ;
                            case  9 :
                                state = 10;
                                eatText8(value);
                                return ;
                            case  21 :
                                state = 22;
                                eatText9(value);
                                return ;
                            case  7 :
                                state = 8;
                                eatText10(value);
                                return ;
                            case  1 :
                                state = 2;
                                eatText11(value);
                                return ;
                            case  5 :
                                state = 6;
                                eatText12(value);
                                return ;
                            case  23 :
                                state = 24;
                                eatText13(value);
                                return ;
                        }
                    } catch (java.lang.RuntimeException e) {
                        handleUnexpectedTextException(value, e);
                    }
                    break;
                }
            }

            private void eatText1(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Nome = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText2(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _TitularidadeSenha = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText3(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _StatusCode = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText4(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _DtNasc = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText5(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _PrimeiroNome = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText6(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Status = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText7(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _CdCodigoRetorno = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText8(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _TipoLinha = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText9(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Reason = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText10(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _StatCom = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText11(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _StatusText = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText12(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _Sexo = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

            private void eatText13(final java.lang.String value)
                throws org.xml.sax.SAXException
            {
                try {
                    _EMail = value;
                } catch (java.lang.Exception e) {
                    handleParseConversionException(e);
                }
            }

        }

    }

}
