/*#########################################################
#  BATCH......: movimentacaoPupSdp
#  Criado por.: Williams Santos 16/09/2016
#  Funcional..: Erika Brum
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;
WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
     V_DATACORTE DATE := TO_DATE('&2', 'RRRRMMDD');     
BEGIN

    DBMS_OUTPUT.ENABLE (buffer_size => NULL); 
     
    DBMS_OUTPUT.put_line ('BEGIN');
    DBMS_OUTPUT.put_line ('RETRY:1001,2,5;');
    DBMS_OUTPUT.put_line ('MAX_PARALLELISM:10;');
    
    DBMS_OUTPUT.put_line ('COMMANDS');
     
    FOR R_LINHA IN ( SELECT DISTINCT 'CREATE:VIVOOPTSUB:MSISDN,55'|| A.CDAREAREGISTRO||A.NRLINHA||':TYPE,'|| (SELECT DECODE(SUM(INATIVO),0,1,2)||';' FROM  LINHA.PERMISSAOLINHAPUP B WHERE B.CDAREAREGISTRO=A.CDAREAREGISTRO AND B.NRLINHA=A.NRLINHA) STATUS      
      FROM LINHA.PERMISSAOLINHAPUP A WHERE TRUNC(A.DTULTIMAALTERACAO) = V_DATACORTE)
    LOOP      
      DBMS_OUTPUT.put_line (R_LINHA.STATUS);      
    END LOOP;
    
    DBMS_OUTPUT.put_line ('END');    
END;
/

SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT