/*#########################################################
#  BATCH......: movimentacaoPupSdp
#  Criado por.: Williams Santos 16/09/2016
#  Funcional..: Erika Brum
###########################################################*/
SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SPOOL &1;

WHENEVER OSERROR EXIT 9
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET COMMIT_LOGGING = 'IMMEDIATE'
ALTER SESSION SET COMMIT_WAIT = NOWAIT

VARIABLE VO_DATACORTE VARCHAR2(512)

DECLARE
     V_DATACORTE DATE := NULL;   
BEGIN
     
    SELECT TRUNC(DECODE(TO_DATE(NVL(DSVALORPARAMETRO, NULL), 'DD/MM/RRRR'), NULL, SYSDATE-1, TO_DATE(NVL(DSVALORPARAMETRO, NULL), 'DD/MM/RRRR')))   
    INTO  V_DATACORTE
    FROM APOIO.PARAMETRO 
    WHERE CDPARAMETRO = 'PARAM_DATAMOVIMENTACAO_PUP';
    
    :VO_DATACORTE := to_char(V_DATACORTE, 'RRRRMMDD');	
    
    UPDATE APOIO.PARAMETRO 
       SET DSVALORPARAMETRO = NULL, DTULTIMAALTERACAO = SYSDATE, IDUSUARIOALTERACAO = 700
     WHERE CDPARAMETRO = 'PARAM_DATAMOVIMENTACAO_PUP';
     
     COMMIT;
     
END;
/

select 'VO_DATACORTE', :VO_DATACORTE from dual;
SPOOL OFF
SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT