//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.26 at 04:03:59 PM GMT-03:00 
//


package br.com.indrasistemas.vivoservices.atendimento.servicos.desbloqueio.tuxgateway.entrada;


/**
 * Java content class for DesbloqueioGsmVOType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/Indra%20SDK/workspaces/VivoServicesEJB/src/br/com/indrasistemas/vivoservices/atendimento/servicos/desbloqueio/tuxgateway/entrada/desbloqueioIN.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="DesbloqueioGsmVOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPessoa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idGrupoAbertura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTipoRelacionamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdAreaRegistro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrLinha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrIMEI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nrSimLock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusConsulta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DesbloqueioGsmVOType {


    /**
     * Gets the value of the cdAreaRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCdAreaRegistro();

    /**
     * Sets the value of the cdAreaRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCdAreaRegistro(java.lang.String value);

    /**
     * Gets the value of the nrSimLock property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrSimLock();

    /**
     * Sets the value of the nrSimLock property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrSimLock(java.lang.String value);

    /**
     * Gets the value of the idTipoRelacionamento property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdTipoRelacionamento();

    /**
     * Sets the value of the idTipoRelacionamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdTipoRelacionamento(java.lang.String value);

    /**
     * Gets the value of the nrIMEI property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrIMEI();

    /**
     * Sets the value of the nrIMEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrIMEI(java.lang.String value);

    /**
     * Gets the value of the idTipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdTipoDocumento();

    /**
     * Sets the value of the idTipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdTipoDocumento(java.lang.String value);

    /**
     * Gets the value of the nrIP property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrIP();

    /**
     * Sets the value of the nrIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrIP(java.lang.String value);

    /**
     * Gets the value of the nrDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrDocumento();

    /**
     * Sets the value of the nrDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrDocumento(java.lang.String value);

    /**
     * Gets the value of the idPessoa property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdPessoa();

    /**
     * Sets the value of the idPessoa property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdPessoa(java.lang.String value);

    /**
     * Gets the value of the statusConsulta property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getStatusConsulta();

    /**
     * Sets the value of the statusConsulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setStatusConsulta(java.lang.String value);

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getErrorCode();

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setErrorCode(java.lang.String value);

    /**
     * Gets the value of the idGrupoAbertura property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdGrupoAbertura();

    /**
     * Sets the value of the idGrupoAbertura property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdGrupoAbertura(java.lang.String value);

    /**
     * Gets the value of the errorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getErrorDescription();

    /**
     * Sets the value of the errorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setErrorDescription(java.lang.String value);

    /**
     * Gets the value of the nrLinha property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNrLinha();

    /**
     * Sets the value of the nrLinha property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNrLinha(java.lang.String value);

}
