SET TERMOUT ON;
SET SQLPROMPT '';
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE 1000000;
SET TIME OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;
SET TIMING OFF;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;

VARIABLE VO_CDERRO NUMBER;
VARIABLE VO_DSERRO VARCHAR2(512);
VARIABLE VO_COUNT_MERGE NUMBER;

select SYSDATE, '[INICIO DO PROCESSAMENTO]' from dual;

declare
  VI_IDUSUARIOALTERACAO NUMBER := &1;

begin

  MERGE
  /*+ PARALLEL(8) */
  INTO LINHA.PLANOSERVICOSUBSEGMENTO P USING
  (SELECT PS.IDSERVICO ,
    PSS.ININFANCIA ,
    PSS.TPPLATAFORMA ,
    S.IDSUBSEGMENTO
  FROM LOAD.PLANOSERVICOSUBSEGMENTO PSS ,
    APOIO.SUBSEGMENTO S ,
    LINHA.PLANOSERVICO PS
  WHERE PSS.SGSUBSEGMENTO = S.SGSUBSEGMENTO
  AND PSS.SGSERVICO = PS.SGSERVICO
  ) L ON (P.IDSERVICO     = L.IDSERVICO)
  WHEN MATCHED THEN
    UPDATE
    SET P.IDSUBSEGMENTO    = L.IDSUBSEGMENTO ,
    P.ININFANCIA         = L.ININFANCIA ,
    P.TPPLATAFORMA       = L.TPPLATAFORMA ,
    P.IDUSUARIOALTERACAO = VI_IDUSUARIOALTERACAO ,
    P.DTUSUARIOALTERACAO = SYSDATE 
  WHEN NOT MATCHED THEN
    INSERT
    (
      P.IDSERVICO ,
      P.IDSUBSEGMENTO ,
      P.ININFANCIA ,
      P.TPPLATAFORMA ,
      P.IDUSUARIOALTERACAO ,
      P.DTUSUARIOALTERACAO
    )
    VALUES
    (
      L.IDSERVICO,
      L.IDSUBSEGMENTO ,
      L.ININFANCIA ,
      L.TPPLATAFORMA ,
      VI_IDUSUARIOALTERACAO ,
      SYSDATE
    ) ;

	:VO_COUNT_MERGE := SQL%ROWCOUNT;
    
  COMMIT;
  :VO_CDERRO := 0;
  :VO_DSERRO := 'Sucesso';
EXCEPTION
	WHEN OTHERS THEN
		:VO_CDERRO := 99;
		:VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRICAO DO ERRO: ' || SQLERRM;
    ROLLBACK;

end;
/

select SYSDATE, '[FIM DO PROCESSAMENTO]' from dual;

select CHR(10) from dual;
select 'VO_CDERRO', :VO_CDERRO from dual;
select 'VO_DSERRO', :VO_DSERRO from dual;
select 'VO_COUNT_MERGE', :VO_COUNT_MERGE from dual;

EXIT :VO_CDERRO;
