SET SQLPROMPT '';
SET TERMOUT OFF;
SET FEEDBACK OFF;
SET ECHO OFF;
SET AUTOTRACE OFF;
SET FLUSH ON;
SET HEADING OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET TIME OFF;
SET TIMING OFF;
SET TRIMOUT ON;
SET TRIMSPOOL ON;
SET PAUSE OFF;
SET SHOWMODE OFF;
SET SQLBLANKLINES OFF;
SET SQLNUMBER OFF;
SET TAB OFF;
SET VERIFY OFF;
SET WRAP OFF;
SET FEED OFF;
SET NEWPAGE NONE;
SET LINESIZE 32767;

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE 

SPOOL "log.txt";

DECLARE
    V_IDPESSOA            NUMBER;
    V_NMPESSOA            VARCHAR2(256);
    V_SGUF                VARCHAR2(3);
    V_INASSOCIACAO        VARCHAR2(1);
    V_NRDOCUMENTO         VARCHAR2(15) := &1;
    V_NRCNPJ              VARCHAR2(15);

    V_ROWID               VARCHAR2(256);
    V_CNT                 NUMBER;
    V_INCONSOLIDA         NUMBER;
    V_TIPODOCUMENTO       NUMBER;
    V_IDLINHATELEFONICA   NUMBER ;
    
    VO_CDERRO NUMBER ;
    VO_DSERRO VARCHAR2(512);

    CURSOR C_REMOVEDOC(P_NRDOCUMENTO VARCHAR2) IS
        SELECT ROWID FROM CUSTOMER.DOCUMENTOCONSOLIDADO WHERE NRDOCUMENTO = P_NRDOCUMENTO ;
    
    CURSOR C_SINCRONIZADOC(P_NRDOCUMENTO VARCHAR2) IS
		 SELECT IDPESSOA, NMPESSOA, SGUF, INASSOCIACAO,NRDOCUMENTOEMPRESA FROM 
		 (SELECT DISTINCT
					  P.IDPESSOA AS IDPESSOA, 
					  P.NMPESSOA AS NMPESSOA, 
					  AUF.SGUF AS SGUF, 
					  NVL(PGM.INASSOCIACAO, '0') AS INASSOCIACAO, 
					  PGM.NRDOCUMENTOEMPRESA AS NRDOCUMENTOEMPRESA ,              
					  DENSE_RANK() OVER (PARTITION BY P.IDPESSOA, P.NMPESSOA, AUF.SGUF,NVL(PGM.INASSOCIACAO, '0'),PGM.NRDOCUMENTOEMPRESA ORDER BY P.ROWID ASC) RANK
			FROM CUSTOMER.PESSOAGESTORMASTER PGM,
					  CUSTOMER.DOCUMENTO DOCUMENTO,
					  CUSTOMER.PESSOADEPARA PDP,
					  CUSTOMER.PESSOA P,
					  CUSTOMER.PESSOAENDERECO PE,
					  APOIO.UF AUF
		   WHERE PGM.NRDOCUMENTOEMPRESA = P_NRDOCUMENTO
				   AND PGM.NRDOCUMENTOEMPRESA = DOCUMENTO.NRDOCUMENTO
				   AND PDP.IDPESSOA = P.IDPESSOA
			 AND EXISTS (
					SELECT 1
					  FROM CUSTOMER.PESSOACONTA PC, CUSTOMER.CONTA
					 WHERE PDP.IDPESSOADEPARA = PC.IDPESSOADEPARA
					   AND CONTA.IDCONTA = PC.IDCONTA
					   AND (   (    CONTA.IDSTATUSCONTA = 0
								AND CONTA.IDTIPOCONTA IN (
									   SELECT IDTIPOCONTA
										 FROM APOIO.TIPOCONTA TIPOCONTA
										WHERE TIPOCONTA.SGTIPOCONTA IN
																	 ('VZ', 'V', 'Z'))
							   )
							OR (    CONTA.IDSTATUSCONTA = 1
								AND CONTA.IDTIPOCONTA IN (
									   SELECT IDTIPOCONTA
										 FROM APOIO.TIPOCONTA TIPOCONTA
										WHERE TIPOCONTA.SGTIPOCONTA IN
												 ('J', 'C', 'D', 'E', 'G', 'H', 'I',
												  'P', 'V', 'R', 'U', 'X', 'Z', 'SO',
												  'Y', 'PJ', 'G1', 'F1', 'ZF', 'ZC',
												  'VV', 'VZ', 'VC', 'VF', 'V4', 'V8',
												  'V7', 'V6', 'V2', 'V5', 'V1', 'FC',
												  'V3', 'DE', 'DT', 'VB'))
							   )
							OR CONTA.IDSTATUSCONTA IN (5, 10)
						   ))
			 AND EXISTS (
					SELECT 1
					  FROM APOIO.TIPODOCUMENTO TIPODOCUMENTO
					 WHERE TIPODOCUMENTO.IDTIPODOCUMENTO = DOCUMENTO.IDTIPODOCUMENTO
					   AND TIPODOCUMENTO.SGCLASSIFICACAO = 'CNPJ')
				   AND P.IDTIPOPESSOA = 2
				   AND PDP.IDPESSOA = PE.IDPESSOA
				   AND PE.IDPESSOA = P.IDPESSOA
			 AND EXISTS (SELECT 1
						   FROM CUSTOMER.UFOPERADORA UF
						  WHERE PE.IDUF = UF.IDUF AND AUF.IDUF = UF.IDUF)
				   AND PE.IDUF = AUF.IDUF
			 AND EXISTS (SELECT 1
						   FROM CUSTOMER.CONTAENDERECO CE
						  WHERE PE.IDPESSOAENDERECO = CE.IDPESSOAENDERECO)
			 AND EXISTS (
					SELECT 1
					  FROM CUSTOMER.PESSOADOCUMENTO PESSOADOCUMENTO
					 WHERE DOCUMENTO.IDDOCUMENTO = PESSOADOCUMENTO.IDDOCUMENTO
										 AND PESSOADOCUMENTO.IDPESSOA = PDP.IDPESSOA
										 AND PESSOADOCUMENTO.IDPESSOA = P.IDPESSOA
					   AND PE.IDPESSOA = PESSOADOCUMENTO.IDPESSOA)
		ORDER BY P.IDPESSOA, P.NMPESSOA, AUF.SGUF,  NVL(PGM.INASSOCIACAO, '0'), PGM.NRDOCUMENTOEMPRESA ,RANK) 
		WHERE RANK = 1;     
        

BEGIN
    VO_CDERRO := 00;
    VO_DSERRO := '>>> Sucesso na Sincronizacao <<<';
    
    
    select LPAD(V_NRDOCUMENTO,14,'0') INTO V_NRDOCUMENTO from dual ;

    DBMS_OUTPUT.ENABLE(buffer_size => NULL);
    DBMS_OUTPUT.PUT_LINE(' >>> Inicio de Processamento : ConsolidaDocumento ' || V_NRDOCUMENTO );
    
    V_CNT := 0 ;
    OPEN C_REMOVEDOC(V_NRDOCUMENTO);
    LOOP
        FETCH C_REMOVEDOC INTO V_ROWID ;
        EXIT WHEN C_REMOVEDOC%NOTFOUND;

        DELETE FROM CUSTOMER.DOCUMENTOCONSOLIDADO WHERE ROWID = V_ROWID ;
        V_CNT := V_CNT + 1;
        IF V_CNT > 100 THEN
           COMMIT;
           V_CNT := 1;
        END IF ;

    END LOOP;
    CLOSE C_REMOVEDOC;

    V_CNT := 0 ;
    OPEN C_SINCRONIZADOC(V_NRDOCUMENTO) ;
    DBMS_OUTPUT.PUT_LINE(' >>> Pesquisa ' || V_NRDOCUMENTO );
--    DBMS_APPLICATION_INFO.SET_MODULE('ConsolidaDocumento', 'Consulta CNPJ ' || V_NRDOCUMENTO );
    LOOP
        FETCH C_SINCRONIZADOC INTO V_IDPESSOA ,
                                    V_NMPESSOA ,
                                    V_SGUF ,
                                    V_INASSOCIACAO ,
                                    V_NRCNPJ ;

        EXIT WHEN C_SINCRONIZADOC%NOTFOUND;
        
        --DBMS_OUTPUT.PUT_LINE( 'V_IDPESSOA ' || V_IDPESSOA );
        --DBMS_OUTPUT.PUT_LINE( 'V_NMPESSOA ' || V_NMPESSOA );
        --DBMS_OUTPUT.PUT_LINE( 'V_SGUF ' || V_SGUF );
        --DBMS_OUTPUT.PUT_LINE( 'V_INASSOCIACAO ' || V_INASSOCIACAO );
        --DBMS_OUTPUT.PUT_LINE( 'V_NRCNPJ ' || V_NRCNPJ );
        
        -- Sistema insere um registro conforme descrito abaixo
        INSERT /*+ APPEND */ INTO CUSTOMER.DOCUMENTOCONSOLIDADO 
        (
            IDDOCUMENTOCONSOLIDADO ,
            IDPESSOA ,
            NMPESSOA ,
            SGUF ,
            INASSOCIACAO ,
            NRDOCUMENTO ,
            INTIPOPESSOA ,
            IDUSUARIO 
        ) 
        VALUES 
        (
            CUSTOMER.DOCUMENTOCONSOLIDADOSQ.NEXTVAL ,
            V_IDPESSOA ,
            V_NMPESSOA ,
            V_SGUF ,
            V_INASSOCIACAO ,
            V_NRDOCUMENTO ,
            2 ,
            1
        );
        
        V_CNT := V_CNT + 1;
        IF V_CNT > 100 THEN
           COMMIT;
           V_CNT := 1;
        END IF ;
        
    END LOOP;
    CLOSE C_SINCRONIZADOC;
    COMMIT;

    --DBMS_OUTPUT.PUT_LINE('CDERRO: '||:VO_CDERRO||', DSERRO: '||:VO_DSERRO);
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') || ' <<< Fim de Processamento : ConsolidaDocumento');

EXCEPTION
	WHEN OTHERS 
	THEN
        VO_CDERRO := 99;
        VO_DSERRO := 'ERRO NR.: ' || SQLCODE || ' - DESCRICAO DO ERRO: ' || SQLERRM;

        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('CDERRO: '||VO_CDERRO||', DSERRO: '||VO_DSERRO);
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') || ' <<< ERRO : Fim de Processamento : ConsolidaDocumento');
END;
/

spool off

SET ECHO OFF
SET TIMI OFF
SET TIME OFF
EXIT

