LOAD DATA
APPEND
INTO TABLE CUSTOMER.PROGRAMARELACIONAMENTOPOS
APPEND
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
	  NRDOCUMENTO,
	  NRLINHASOLICITANTE,
	  IDPROGRAMARELACIONAMENTO "1",
	  DTCADASTRO "SYSDATE",
	  DTULTIMAATUALIZACAO "SYSDATE",
	  IDUSUARIOATUALIZACAO "666",
	  IDPESSOAENDERECO "null",	  
	  INTIPOINSCRICAO "1",
	  DTEXCLUSAO
)
