LOAD DATA 
REPLACE
INTO TABLE LOAD.PEDIDORESSARCIMENTO
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	IDPEDIDORESSARCIMENTO,
	NRTELEFONE,
	DTINICIOINTERRUPCAO DATE 'DD/MM/YYYY HH24:MI:SS',
	DTFIMINTERRUPCAO    DATE 'DD/MM/YYYY HH24:MI:SS',
	SGUF,
	NMMUNICIPIO,
	DSTIPORESSARCIMENTO,
	DSTIPOREDE,
	DTULTIMAALTERACAO SYSDATE
)