set echo off
set feedback off
set heading off
set arraysize 50
set autotrace on
set flush off
set pages 0
set lines 32767
set trimspool on
set timi on
set time on
set termout off
set serveroutput on size 100000


set echo on

DECLARE
    TYPE R_IDPESSOADEPARA IS RECORD (IDPESSOADEPARA NUMBER, IDLINHATELEFONICA NUMBER, RID ROWID);
    TYPE T_IDPESSOADEPARA IS TABLE OF R_IDPESSOADEPARA;
    rPESSOADEPARA T_IDPESSOADEPARA;
    cC            SYS_REFCURSOR;
    V_LIMIT       NUMBER;
    V_PARALLEL    VARCHAR2(10);
    V_HORAMAXIMA  VARCHAR2(10);
    V_SQL         VARCHAR2(4000); 
BEGIN

  DBMS_APPLICATION_INFO.SET_MODULE('LINHA-OFERTA','IDENTIFICACAO IDPESSOADEPARA');

  -- PARALELISMO
  SELECT DSVALORPARAMETRO INTO V_PARALLEL FROM APOIO.PARAMETRO WHERE CDPARAMETRO = 'LINHAOFERTA_PARALLEL';
  -- HORA LIMITE
  SELECT DSVALORPARAMETRO INTO V_HORAMAXIMA FROM APOIO.PARAMETRO WHERE CDPARAMETRO = 'LINHAOFERTA_HORAMAXIMA';
  -- LIMIT
  SELECT TO_NUMBER(DSVALORPARAMETRO) INTO V_LIMIT FROM APOIO.PARAMETRO WHERE CDPARAMETRO = 'LINHAOFERTA_LIMIT';

  V_SQL := '
      SELECT /*+ USE_NL(LO) USE_HASH(AR) PARALLEL(LB '||V_PARALLEL||') PARALLEL(PL '||V_PARALLEL||') PARALLEL(LT '||V_PARALLEL||')  */
            PL.IDPESSOADEPARA, PL.IDLINHATELEFONICA, LO.ROWID AS RID
        FROM
            LINHA.LINHABASE LB
            JOIN APOIO.AREAREGISTRO AR USING (IDAREAREGISTRO)
            JOIN LINHA.LINHATELEFONICA LT USING (IDLINHABASE)
            JOIN LINHA.LINHAOFERTA LO USING (CDAREAREGISTRO,NRLINHA)
            JOIN CUSTOMER.PESSOALINHA PL ON (PL.IDLINHATELEFONICA = LT.IDLINHATELEFONICA)
        WHERE
            IDTIPORELACIONAMENTO = 2
            AND LO.IDPESSOADEPARA IS NULL
            AND (LT.DTEXPIRACAO IS NULL OR LT.DTEXPIRACAO > SYSDATE)
            AND LT.IDSISTEMAORIGEM IN (1,11)
  ';

  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || '============================================================');
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || ' - INICIO DO PROCESSO');
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || ' --- HORA MAXIMA ' || V_HORAMAXIMA);
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || ' --- PARALELISMO ' || V_PARALLEL);
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || ' --- BULK LIMIT  ' || V_LIMIT);


  OPEN cC FOR V_SQL;
  LOOP
      FETCH cC BULK COLLECT INTO rPESSOADEPARA LIMIT V_LIMIT;
      FORALL I IN rPESSOADEPARA.FIRST..rPESSOADEPARA.LAST
          UPDATE /*+ ROWID(LINHAOFERTA) */  LINHA.LINHAOFERTA
             SET IDPESSOADEPARA = rPESSOADEPARA(I).IDPESSOADEPARA,
                 IDLINHATELEFONICA = rPESSOADEPARA(I).IDLINHATELEFONICA
           WHERE ROWID = rPESSOADEPARA(I).RID;
          COMMIT;

      IF cC%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || 'FINALIZADO COM SUCESSO');
        EXIT;
      ELSIF TO_CHAR(SYSDATE,'HH24MI') > V_HORAMAXIMA AND V_HORAMAXIMA != '0000' THEN
        DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || 'FINALIZADO POR EXCEDER HORA MAXIMA DE EXECUCAO: '|| V_HORAMAXIMA);
        EXIT;
      END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI') || '============================================================');
  CLOSE cC;

END;
/

spool off;

set echo off
set feedback off
set heading off
set arraysize 100
set autotrace on
set flush off
set pages 0
set lines 32767
set trimspool on
set timi on
set time on
set termout off

exit;

