
CREATE INDEX LINHA.LINHAOFERTAIX1 ON LINHA.LINHAOFERTA (IDPESSOADEPARA) LOGGING PARALLEL 64;

ALTER INDEX LINHA.LINHAOFERTAIX1 NOPARALLEL;

EXEC dbms_stats.gather_table_stats(ownname =>'LINHA', tabname=> 'LINHAOFERTA', degree=> 64, cascade=>TRUE, estimate_percent => 100);
