spool spool.txt
SELECT
    /*+ parallel(t1) parallel(t3) parallel(c) */
    T1.NMGESTOR ||'|'|| 
    T1.NMSOBRENOMEGESTOR ||'|'||
    T1.NMPESSOAGESTOR ||'|'||
    'GC' ||'|'|| -- AS sigla
    T1.NRDOCUMENTO ||'|'||
    T1.NRTELEFONECELULARVIVO ||'|'||
    T1.NRTELEFONEFIXO ||'|'||
    NULL ||'|'|| -- AS nrdocumentoempresa
    T1.EMAIL ||'|'||
    C.CDCONTA ||'|'|| -- AS idconta
    T1.IDPESSOASISTEMAORIGEM ||'|'||
    TO_CHAR(T1.DTULTIMAALTERACAO,'DD/MM/YYYY HH24:MI:SS') ||'|'||
    TO_CHAR(T3.DTULTIMAALTERACAO,'DD/MM/YYYY HH24:MI:SS')
FROM
    CUSTOMER.PESSOAGESTOR T1,
    CUSTOMER.PESSOAGESTORCONTA T3,
    CUSTOMER.CONTA C
WHERE 
    T1.IDPESSOAGESTOR = T3.IDPESSOAGESTOR
    AND T3.IDCONTA = C.IDCONTA
    --AND T1.NRDOCUMENTO IN (SELECT CPFGESTOR FROM LOAD.CARGAGESTORES)
    AND C.CDCONTA IN (SELECT CDCONTASISTEMAORIGEM FROM LOAD.CARGAGESTORES) 
    ;
spool off