

CREATE TABLE LOAD.CARGAGESTORES (
	NOME VARCHAR2(128),
	SOBRENOME VARCHAR2(128),
	NMCOMPLETO VARCHAR2(256),
	SIGLA VARCHAR2(2),
	CPFGESTOR VARCHAR(32),
	CELVIVOGESTOR NUMBER,
	TELCOMERCIALGESTOR NUMBER,
	CPFCNPJCLIENTE VARCHAR(32),
	EMAILGESTOR VARCHAR(128),
	CDCONTASISTEMAORIGEM VARCHAR2(64),
	IDPESSOASISTEMAORIGEM VARCHAR2(32),
	DTATUALIZACAOCONTATO DATE,
	DTATUALIZACAOASSOCIACAO DATE
);

COMMENT ON TABLE LOAD.CARGAGESTORES IS 'Tabela de stage para atualizacao de dados dos gestores no Vivonet';
COMMENT ON COLUMN LOAD.CARGAGESTORES.NOME IS 'NOME';
COMMENT ON COLUMN LOAD.CARGAGESTORES.SOBRENOME IS 'SOBRENOME';
COMMENT ON COLUMN LOAD.CARGAGESTORES.NMCOMPLETO IS 'NOME COMPLETO';
COMMENT ON COLUMN LOAD.CARGAGESTORES.SIGLA IS 'SIGLA (GC ou GM)';
COMMENT ON COLUMN LOAD.CARGAGESTORES.CPFGESTOR IS 'CPF DO GESTOR';
COMMENT ON COLUMN LOAD.CARGAGESTORES.CELVIVOGESTOR IS 'CELULAR VIVO DO GESTOR';
COMMENT ON COLUMN LOAD.CARGAGESTORES.TELCOMERCIALGESTOR IS 'TELEFONE COMERCIAL DO GESTOR';
COMMENT ON COLUMN LOAD.CARGAGESTORES.CPFCNPJCLIENTE IS 'CPF ou CNPJ DO CLIENTE';
COMMENT ON COLUMN LOAD.CARGAGESTORES.EMAILGESTOR IS 'E-MAIL DO GESTOR';
COMMENT ON COLUMN LOAD.CARGAGESTORES.CDCONTASISTEMAORIGEM IS 'CODIGO CONTA SISTEMA ORIGEM';
COMMENT ON COLUMN LOAD.CARGAGESTORES.IDPESSOASISTEMAORIGEM IS 'IDPESSOASISTEMAORIGEM';
COMMENT ON COLUMN LOAD.CARGAGESTORES.DTATUALIZACAOCONTATO IS 'DATA DE ULTIMA ATUALIZACAO CONTATO';
COMMENT ON COLUMN LOAD.CARGAGESTORES.DTATUALIZACAOASSOCIACAO IS 'DATA DE ULTIMA ATUALIZACAO ASSOCIACAO';

GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO LOAD;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO CUSTOMER;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO BATCHDES;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO BATCHHV;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO BATCHHC;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOAD.CARGAGESTORES TO BATCHPRO;

