
CREATE OR REPLACE PROCEDURE LOAD.TRUNC_CARGAGESTORES
IS
BEGIN
	EXECUTE IMMEDIATE 'TRUNCATE TABLE LOAD.CARGAGESTORES';
END;
/

GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO LOAD;
GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO CUSTOMER;
GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO BATCHDES;
GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO BATCHHV;
GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO BATCHHC;
GRANT EXECUTE ON LOAD.TRUNC_CARGAGESTORES TO BATCHPRO;
