set echo on
set serveroutput on
set trimspool on
set pages 0
set serveroutput on size 1000000

spool cargaOportunidadeVenda.txt

SELECT 'CHAVE_END|CNL|COD_LOG|NUMERO|NOME|CPF|CONVERGENCIA|EMAIL|DETALHE_LINHA_FIXA|TELEFONE_LINHA_FIXA|VALOR_LINHA_FIXA|DT_AQUISICAO_LINHA_FIXA|NRC|COMPLEMENTO_ENDERECO|DETALHE_LINHA_MOVEL|TELEFONE_LINHA_MOVEL|VALOR_LINHA_MOVEL|ID_LINHA|DT_AQUISICAO_LINHA_MOVEL|DETALHE_BL|DT_AQUISICAO_BL|VALOR_BL|DETALHE_TV|DT_AQUISICAO_TV|VALOR_TV|VALOR_TOTAL_PRODUTOS|ERRO' FROM DUAL;
SELECT 
CDENDERECO || '|' || 
CDCNL || '|' || 
CDLOGRADOURO || '|' || 
NRLOGRADOURO || '|' || 
NMCLIENTE || '|' || 
NRCPFCLIENTE || '|' || 
DSCONVERGENCIA || '|' || 
DSEMAILCLIENTE || '|' || 
DSCOMPLEMENTOENDERECOCLIENTE || '|' || 
DSDETALHEPRODUTOFIXA || '|' || 
DTAQUISICAOPRODUTOFIXA || '|' || 
VLPAGOPRODUTOFIXA || '|' || 
NRLINHAFIXA || '|' || 
CDPRODUTOLEGADOFIXA || '|' || 
DSDETALHEPRODUTOMOVEL || '|' || 
DTAQUISICAOPRODUTOMOVEL || '|' || 
VLPAGOPRODUTOMOVEL || '|' || 
NRLINHAMOVEL || '|' || 
CDPRODUTOLEGADOMOVEL || '|' || 
DSDETALHEPRODUTOBANDALARGA || '|' || 
DTAQUISICAOPRODUTOBANDALARGA || '|' || 
VLPAGOPRODUTOBANDALARGA || '|' || 
DSDETALHEPRODUTOTV || '|' || 
DTAQUISICAOPRODUTOTV || '|' || 
VLPAGOPRODUTOTV || '|' || 
VLTOTALPRODUTO || '|' || 
DSMSG					
FROM SFA.OPORTUNIDADEVENDA_LDR
WHERE SGTIPOMSG = 'E';
	
spool off

set echo off
set serveroutput off
