LOAD DATA
INFILE  '/home/ytinos/testeDAT.txt'
BADFILE '/home/ytinos/bad/header.bad'
APPEND
INTO TABLE HEADER WHEN (1:2) = '00' 
FIELDS TERMINATED BY "\n"
TRAILING NULLCOLS
( 
	SQARQUIVO   POSITION(3:9)   CHAR(7),
	DTMOVIMENTO POSITION(10:17) CHAR(8)	
)