set echo off
set feed off
set pages 0
set lines 32767
set trimspool on
set timing off
set termout off
set verify off
 
spool data/&1

SELECT 'NOME_CONDOMINIO|TIPO DE CONDOMÍNIO|LAYOUT DO CONDOMÍNIO|QTDE_BLOCOS|QTDE_APTOS|ENDERECO|NUMERO|NUMERO 2|CEP|BAIRRO|CIDADE|UF|QTDE_ANDARES_BLOCO|QTDE_APTO_ANDAR|QTDE_DORM_APTO|METRAGEM_APTOS|SINDICO_NOME|SINDICO_APTO|SINDICO_TEL_RES|SINDICO_TEL_COML|SINDICO_TEL_CEL|ZELADOR_NOME|ZELADOR_APTO|ZELADOR_TEL_RES|ZELADOR_TEL_CEL|ZELADOR_TEL_COML|ZELADOR_TEL_PORTARIA|OBS|USUARIO_PROSPECTOR|DATA DE CRIAÇÃO' FROM DUAL;

SELECT  
        PREC.NMCONDOMINIO || '|' || 
        PREC.DSTIPOCONDOMINIO || '|' || 
        PREC.DSLAYOUTCONDOMINIO || '|' || 
        PREC.QTBLOCO || '|' || 
        PREC.QTAPARTAMENTO || '|' || 
        PREC.DSLOGRADOURO || '|' ||  
        PREC.NRLOGRADOURO || '|' ||  
        PREC.NRLOGRADOUROSECUNDARIO || '|' ||  
        PREC.CDCEP || '|' || 
        PREC.DSBAIRROLOGRADOURO || '|' ||  
        PREC.DSCIDADELOGRADOURO || '|' || 
        PREC.SGUF || '|' ||  
        PREC.QTAPARTAMENTOANDAR || '|' ||  
        PREC.QTDORMITORIOAPARTAMENTO || '|' ||  
        PREC.QTMETRAGEMAPARTAMENTO || '|' || 
        PREC.QTIDADECONDOMINIO || '|' ||  
        PREC.NMSINDICO || '|' ||  
        PREC.NRAPARTAMENTOSINDICO || '|' ||  
        PREC.NRTELRESSINDICO || '|' ||  
        PREC.NRTELCOMSINDICO || '|' ||  
        PREC.NRTELCELSINDICO || '|' ||  
        PREC.NMZELADOR || '|' ||  
        PREC.NRAPARTAMENTOZELADOR || '|' ||  
        PREC.NRTELRESZELADOR || '|' ||  
        PREC.NRTELCOMZELADOR || '|' ||  
        PREC.NRTELCELZELADOR || '|' ||  
        PREC.NRTELPORTARIACONDOMINIO || '|' ||  
        PREC.DSOBSERVACAO || '|' ||  
        PREC.CDUSUARIOPROSPECTOR || '|' ||  
        TO_CHAR(PREC.DTULTIMAALTERACAO, 'DD/MM/YYYY HH24:MI:SS')        
FROM    SFA.PRECADASTRO PREC
WHERE   PREC.DTULTIMAALTERACAO >= (SYSDATE - 7);

spool off

exit;